### ISSUE TITLE
Doplnit odkazy do webklienta AMČR

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#10]
Pod tlačítko "Odkazy" přidat možnost "Zobrazit v AMČR", který bude ukazovat na `[base_url_serveru]/id/[ident_cely]` (např. https://wamcr-test.aiscr.cz/id/C-200912958)

**Comment by motyc** [comment]
Zatím není implementováno.

**Comment by albertoh** [comment]
Pridano
