### ISSUE TITLE
Chyba skrývání lokalizací pro samostatné nálezy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#101]
I když nejsou samostatné nálezy viditelné kvůli přístupnosti, mapa je přesto zobrazuje ve výsledcích vyhledávání. Tím pádem jde také dovodit (a to poměrně přesně), odkud nálezy pocházejí.

Příklad: https://digiarchiv.aiscr.cz/results?entity=samostatny_nalez&mapa=true&loc_rpt=50.13570599159835,14.457723376930586,50.166993080701694,14.557762712668346&page=0

**Comment by albertoh** [comment]
Opraveno. Mozno testovat na testovacim serveru.

**Comment by motyc** [comment]
Potvrzuji, nasadit prosím jako v2.0.2

**Comment by albertoh** [comment]
Nasazeno
