### ISSUE TITLE
Pokud je u dokumentu neident. akce, zobrazuje se u opakovaně u více jednotek (částí) dokumentu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#102]
Pokud má dokument více jednotek (částí) dokumentu a na jednu z nich je připojena neidentifikovaná akce, zobrazuje se takto akce při rozbalení detailu u obou jednotek (částí) dokumentu

Příklad v Digiarchivu (chybně): https://digiarchiv.aiscr.cz/id/C-TX-200702284

Příklad v API (správně - neident. akce je jen u příslušné jednotky C-TX-200702284-D01): https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-TX-200702284&metadataPrefix=oai_amcr

Může teoreticky nastat i situace, kdy každá jednotka (část) dokumentu bude mít jinou neident. akci.

**Comment by albertoh** [comment]
Opraveno na testu

**Comment by motyc** [comment]
Skvěle. Lze nasadit jako 2.0.3.

**Comment by albertoh** [comment]
Je to tam
