### ISSUE TITLE
V souboru pro nastavení nápovědy nefunguje stylování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#103]
Jedná se o soubor var/lib/digiarchiv/texts/help.html

Když tam nějaké styly nastavím, smažou se (na výstupu). Je to problém kvůli tomu, že nemohu nápovědu vyrobit v nějaké koukatelné podobě. Potřeboval bych mít možnost používat standardní CSS.

**Comment by albertoh** [comment]
Zkus to na test, plz

**Comment by albertoh** [comment]
Defaultne, angular nedovoluje inline style od externich textu. Ted jsem to tam povolil. Pridej, treba, <span style="font-size: 36px;">neco</span>

**Comment by motyc** [comment]
Funguje, moc děkuji.

**Comment by motyc** [comment]
Ještě jsem se vlastně chtěl zeptat - je to teď povolené generálně pro aplikaci, nebo jen pro tento konkrétní soubor?

**Comment by motyc** [comment]
Skvěle, děkuji, zavírám.
