### ISSUE TITLE
 U samostatných nálezů se indexuje pouze první foto

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#107]
Zdá se, že index nezaznamená druhý soubor a indexuje pouze první foto. Princip by však měl být stejný jako u dokumentů. 

Příkladem je:
https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/M-202101534-N00001&metadataPrefix=oai_amcr
https://digiarchiv.aiscr.cz/id/M-202101534-N00001

**Comment by albertoh** [comment]
Opraveno na testu. Nejsou videt nahledy, ale pocet souboru je spravny

**Comment by motyc** [comment]
Lze nasadit.

**Comment by albertoh** [comment]
Je to na produkcnim. I ostatni take :)
