### ISSUE TITLE
Ořez foto v prohlížečce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#108]
Obrázky se v prohlížečce stále podivně ořezávají (pokud jsou příliš široké), místo aby se v případě přetečení okraje boxu zmenšily na šířku: 
![image](https://user-images.githubusercontent.com/20186892/114025425-60f1ff80-9875-11eb-9d47-35e40cf74ce1.png)

Úplně rozbitá je responzivita:
![image](https://user-images.githubusercontent.com/20186892/114025574-8d0d8080-9875-11eb-8f41-53a898235574.png)

**Comment by pkudela** [comment]
@motyc muzes mi prosim poslat link na tento konkretni zaznam s timto obrazkem?

**Comment by motyc** [comment]
Zde: https://digiarchiv.aiscr.cz/id/M-202101534-N00001

Vidět je to ale třeba i tu: https://digiarchiv.aiscr.cz/id/C-202010524-N00021

**Comment by pkudela** [comment]
@motyc jojo, ja uz na tom delam, vybral jsem jinou fotku, ale az to nasadim, tak to otestuju na tom co si poslal

**Comment by motyc** [comment]
Ono je tedy mimochodem divné i na stavení generátoru Thumbnail, protože ten šířkově ořezává taky a taky to vypadá ve výsledku dost divně: 
![image](https://user-images.githubusercontent.com/20186892/114147837-61dc6d00-9919-11eb-8366-7db738e6f7d9.png). Ale to je spíše na @albertoh?

**Comment by pkudela** [comment]
@motyc presne tak, to je na Alberta, pokud si zobrazis obrazek -> https://digiarchiv.aiscr.cz/api/img?id=1611677597170_C-202010524-N00021F1.jpg, tak uz je to spatne orezane

**Comment by pkudela** [comment]
Odladil jsem jeste paginaci a metadata, melo by to by ok, vic s tim asi neudelam.
![image](https://user-images.githubusercontent.com/16591052/114150544-79692500-991c-11eb-8510-2bb3e443ec37.png)

**Comment by pkudela** [comment]
az nasadim, prehodim na testovani

**Comment by albertoh** [comment]
Generovani malych nahledu je implementovano tak, aby nahledy mely presne 100x100 pixelu, a zaroven se nedeformovaly.
Tak jsme se domlouvali davno, pri implementaci stare verze.
Muzu menit tak, aby byl jeden z rozmeru, ten vetsi, 100 pixelu. Ale ten druhy uz bude mensi, a muze se stat, ze bude o hodne mensi, co bude vypadat divne, a nebo dokonce necitelne.
 Mam to tehdy zmenit?

**Comment by albertoh** [comment]
Opraveno. Generoval jsem nahledy snovu na produkcnim

**Comment by motyc** [comment]
Lze nasadit.

**Comment by motyc** [comment]
Zde je ještě jeden nedořešený problém pro @pkudela - je to viditelné hned na tom prvním obrázku, kde se ořezává obrázek z pravé strany místo toho, aby se zmenšil na šířku. Přitom když je okno užší, funguje to dobře. Ke skoku dochází mezi oknem 959-960px.

Celá obrazovka (chyba s ořezem):
![image](https://user-images.githubusercontent.com/20186892/114596385-e0c20480-9c8f-11eb-928d-abeb5fc4f17e.png)

Obrázek v reálu: https://digiarchiv.aiscr.cz/api/img?size=medium&id=1617709791996_M-202101534-N00001F1.jpg&page=0

Zmenšená obrazovka (chyba zmizí):
![image](https://user-images.githubusercontent.com/20186892/114596542-0f3fdf80-9c90-11eb-9e1d-c4b689187a10.png)

**Comment by pkudela** [comment]
hotovo, puhnuto, ale nemuzu overit chovani na ostrem, @albertoh prosim o nasazeni

**Comment by motyc** [comment]
Na test jsem dal foto k testování (https://digiarchiv-test.aiscr.cz/results?entity=samostatny_nalez)

**Comment by pkudela** [comment]
nasazeno, @motyc prosim otestuj

**Comment by motyc** [comment]
Hotovo, v pořádku.

**Comment by albertoh** [comment]
Je na prod

**Comment by motyc** [comment]
Funguje skvěle
