### ISSUE TITLE
Zvláštní chování facety

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#109]
Pokud roluji facetou období, tak v některých chvílích podivně poskočí, kvůli čemuž vlastně nejde vybrat některé hodnoty (zobrazení je přeskočí). Bude to asi způsobeno dynamickým načítáním ve spojení s dlouhými názvy.

Na stránce https://digiarchiv.aiscr.cz/results?entity=akce např. dojde k takovému skoku při rolování za "NEOLIT NESP."

![image](https://user-images.githubusercontent.com/20186892/114026608-b7ac0900-9876-11eb-998d-de1f74295ae1.png)

**Comment by albertoh** [comment]
Opraveno. Na testu. Problem zpusobily dlouhe nazvy, ktere se lamaly na dva radky. Ted jsem pridal ellipsis ... a tooltip pro plne zobrazeni tech hodnot. Musi to byt na jednom rade, presneji receno, vsechny hodnoty musi mit stejnou vysku, aby virtual scrolling fungoval spravne.

**Comment by motyc** [comment]
Perfektní, je to opravdu o moc příjemnější. Lze nasadit.
