### ISSUE TITLE
Chyby v responsivním chování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#110]
- [x]  Zvláštně se ořezává obsah pole "Zadejte vyhledávací dotaz":
![image](https://user-images.githubusercontent.com/20186892/114026035-11f89a00-9876-11eb-8dee-5a5414e8aa2d.png)

- [x]  Tlačítka u detailu záznamu splývají/chybně se zalamují a celkově hlavička působí neodladěně:
![image](https://user-images.githubusercontent.com/20186892/114026886-11143800-9877-11eb-9414-c66ec5ca23a1.png)

- [x]  V záhlaví chybí některé prvky nastavení, jako je způsob řazení, přechod na konkrétní stránku apod.:
![image](https://user-images.githubusercontent.com/20186892/114027139-5cc6e180-9877-11eb-8698-04e72d16d459.png)

- [x] Mapové okno není odladěné vůbec a v podstatě nejde použít:
![image](https://user-images.githubusercontent.com/20186892/114027372-94358e00-9877-11eb-98b2-8250455a0a6e.png)

![image](https://user-images.githubusercontent.com/20186892/114027548-c47d2c80-9877-11eb-9ca8-cd212c770b1b.png)

**Comment by pkudela** [comment]
1. hotovo, nicmene pokud zmensim uplne na hulvata, tak se placeholder stejne nevejde, ale o snad resit nebudeme :) Otazka je, do jakeho rozliseni vubec poskytovat prepnuti na mapu, repektive do jakeho rozliseni to ma pro uzivatele nejaky prinos a ne vopruz
![image](https://user-images.githubusercontent.com/16591052/114151839-d7e2d300-991d-11eb-9d9e-fcf3596b25e8.png)
![image](https://user-images.githubusercontent.com/16591052/114151912-ee892a00-991d-11eb-95c5-56a8bcbb9715.png)

**Comment by pkudela** [comment]
2. hotovo
![image](https://user-images.githubusercontent.com/16591052/114155423-c6032f00-9921-11eb-8a43-e150cea31557.png)
![image](https://user-images.githubusercontent.com/16591052/114155517-dfa47680-9921-11eb-848a-f7c72883ab6e.png)

**Comment by pkudela** [comment]
3. Tam je to hodne slozity, udelat to nejak rozume, pohral jsem si s tim a v podstate jsou 3 stavy viz. screenshots
![image](https://user-images.githubusercontent.com/16591052/114165047-4d55a000-992c-11eb-9b9f-040ef7e7e512.png)
![image](https://user-images.githubusercontent.com/16591052/114165095-5cd4e900-992c-11eb-9119-9b59bc31d27e.png)
![image](https://user-images.githubusercontent.com/16591052/114165145-69f1d800-992c-11eb-9d29-dbfc2d017b20.png)
![image](https://user-images.githubusercontent.com/16591052/114165171-7413d680-992c-11eb-89bb-dd9075fe18dc.png)
