### ISSUE TITLE
Ořez fotek v thumbnail generátoru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#111]
Nazuji na #108:

> Ono je tedy mimochodem divné i na stavení generátoru Thumbnail, protože ten šířkově ořezává taky a taky to vypadá ve výsledku dost divně:
> ![image](https://user-images.githubusercontent.com/20186892/114147837-61dc6d00-9919-11eb-8366-7db738e6f7d9.png)

Ten šířkový ořez je divný. Nejde generátor nakonfigurovat tak, aby Pouze zmenšoval do vybrané velikosti, ale neořezával?

**Comment by motyc** [comment]
> Generovani malych nahledu je implementovano tak, aby nahledy mely presne 100x100 pixelu, a zaroven se nedeformovaly.
> Tak jsme se domlouvali davno, pri implementaci stare verze.
> Muzu menit tak, aby byl jeden z rozmeru, ten vetsi, 100 pixelu. Ale ten druhy uz bude mensi, a muze se stat, ze bude o hodne mensi, co bude vypadat divne, a nebo dokonce necitelne.
> Mam to tehdy zmenit?

Odpovídám zde, ať se nám to nemotá dohromady. Máš pravdu, je to tak asi dlouho a a už delší dobu mi to přijde ne zcela praktické, teď na fotkách se to ale projevilo hodně. Ano prosím, uprav to tak, aby větší rozměr byl 100 px. Nečitelné je to mnohdy i tak, na tom se mnoho nezmění. Jde o ilustrativní náhled. Zejména u foto to však není takto moc dobré. Jde o to získat představu o tom, o jaký dokument jde.

**Comment by albertoh** [comment]
Nahledy opravene na produkcnim.
