### ISSUE TITLE
Problémy s responsivitou mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#112]
V rámci řešení #110 jsme narazili na problém chování mapového okna při práci na mobilu, které vyžaduje hlubší úpravu. Způsob chování totiž ve výsledku vylučuje možnost mapu použít. Jde o to, že:

- [x] - když je menu vysunuté, tlačítko na jeho zasunutí zmizí zcela mimo zobrazení -> řešením je dostat tlačítko na zasunutí přímo do menu
- [x] - když se menu vysune, mapa má v tu chvíli nulovou velikost (není pro ni na display místo) a tím pádem zmizí i výsledky, které před vysunutím menu byly na mapě viditelné; tím pádem se vůbec nejde na jednotlivé záznamy podívat -> řešení bude nastavit nějakou minimální velikost mapového okna, která se bude aplikovat na pozadí i při vysunutém menu nebo si nějak pamatovat rámec zobrazený před vysunutím menu

**Comment by motyc** [comment]
Funguje to skvěle. prosím @pkudela pouze o doladění dvou věcí:
- [ ] - když otevřu mapu na mobilu, zobrazí se ve výchozím režimu vysunuté menu, takže mapu nevidím - nechal bych ho defaultně zasunuté;
- [ ] - jako výchozí vrstvu mapy nastavit ČÚZK - Základní mapy ČR

**Comment by pkudela** [comment]
Po telefonickem rozhovoru bude sidenav defaultne skryty, jako je to na google maps. Jelikoz angular sidenav je dymicky, bylo by obtizne pri nejakem konkretnim breakpointu ho schovat. Take jsem upravil tlacitko pro export z mapy kvuli responsivnimu chovani pro 3 ruzne breakpointy:

![image](https://user-images.githubusercontent.com/16591052/146579459-0f4b3df6-11fd-4fdd-9819-d5438fcf85ca.png)

![image](https://user-images.githubusercontent.com/16591052/146579591-6466cd1f-b935-4c5b-8f7d-36446c2616ed.png)

![image](https://user-images.githubusercontent.com/16591052/146579693-8dce4038-3b44-4284-9020-7843768db49b.png)

**Comment by motyc** [comment]
Otestováno a řešení s výchozím skrytím je ok. Vyřešit je třeba:

- [ ] - V plném zobrazení na PC zvýraznit ikonu pro sidenav tím, že bude obsahovat text "Filtrace / Výsledky"

- [ ] - Při mobilním zobrazení nefunguje clustering (je jedno, zda na přímo na mobilu, nebo při zúženém okně na PC)

- [ ] - v podstatě nefunkční je otevírání detailu záznamu (při rozbalené sidenav se zdánlivě nic nestane, při zabalené je tam divná nudle)
![image](https://user-images.githubusercontent.com/20186892/146762015-ffaf5902-a25f-40c3-9157-aabe2daac2b8.png)

**Comment by motyc** [comment]
Ad nefunkční clustering - upřesňuji, že je to ve skutečnosti teď rozbité všude (bez ohledu na zařízení a velikost okna), jen jsem si toho nevšiml (chvilku před testováním tohoto issue to fungovalo dobře)...

**Comment by pkudela** [comment]
takze takto:
600 <
![image](https://user-images.githubusercontent.com/16591052/146805413-85eaec98-6e2a-48ab-ba42-e44c717214d2.png)

600 >
![image](https://user-images.githubusercontent.com/16591052/146805519-679f663e-9c34-42a8-8be9-4a56c758fda7.png)
![image](https://user-images.githubusercontent.com/16591052/146805594-7b3d3190-9068-4579-bf4a-e4affd6daa83.png)

Desktop
![image](https://user-images.githubusercontent.com/16591052/146805707-27fe26ae-3e03-4e88-8cc1-cbecb8846ab6.png)

Kompletni redesign ovladacich prvku mapy na zaklade dohody + zmeny v chovani ostatnich elementu, ktere s redesignem uzce souvisi.

**Comment by pkudela** [comment]
@motyc zitra probereme ten button

**Comment by pkudela** [comment]
@motyc prosim o otestovani mimo textoveho buttonu

**Comment by motyc** [comment]
@pkudela  Za mne to vypadá a chová se perfektně. Mám tam jedinou drobnost, která ale snad jde řešit snadno - když mám vysunuté menu na mobilu a kliknu na tu ikonu "i" u záznamu (abych si jej zobrazil), tak se zdánlivě nic nestane, protože je detail zcela schovaný za vysunutým menu - šlo by menu v tomto případě (pokud je menu přes celou šířku) po kliknutí na "i" automaticky zabalit?

Také mi přijde, že breakpoint pro menu (kdy je přes celé zobrazení) je nyní nastavený poměrně zbytečně vysoko (<960), nestačilo by méně?

**Comment by pkudela** [comment]
hotovo:

- brakpoint pro 100% delku sidenav dle dohody snizen na 599px
- s tim souvisi i chovani po kliku na icko, ktere od tohoto breakpointu zavira sidenav
- Alberto upravil service, takze ted uz by se ve vysledcih po kliku na button mapy mela zobrazit horni cast

**Comment by pkudela** [comment]
@motyc nasazeno na server, prosim otestovat

**Comment by motyc** [comment]
Potvrzuji, toto máme hotovo.

**Comment by motyc** [comment]
Drobná chyba z testování:
- [ ] Při prostorovém výběru nevyužívá sloupec s výsledky celou dostupnou vertikální plochu
![image](https://user-images.githubusercontent.com/20186892/151180443-8c232523-6d11-40aa-8136-7e5a3e8c3d7d.png)

**Comment by albertoh** [comment]
Hotovo
