### ISSUE TITLE
Komunikace s uživateli 

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#116]
Umožnit snadno reportovat chyby či komentáře uživatelů (např. klikem na ikonu u každého záznamu umožnit odeslat komentář na email AMČR).

**Comment by albertoh** [comment]
Mame to umoznit komu koli, nebo jen prihlasenim?

**Comment by motyc** [comment]
Klidně komukoli, ale šla by tam prosím do formuláře nasadit invisible reCAPTCHA v2 (https://www.google.com/recaptcha/about/)?

Pokud to půjde, pošli prosím případně Gmail účet, přidal bych tě do správy té CAPTCHA kvůli klíčům.

**Comment by pkudela** [comment]
hotovo, pripraveno ve vsech entitach, @albertoh  je to Tvoje

**Comment by albertoh** [comment]
@MichalKminek Potrebuju udaje pro konfiguraci mailu:
 SMTP server
 Uzivatel a pripadne heslo

**Comment by motyc** [comment]
@MichalKminek @albertoh Doplňuji jen, že cílová adresa bude info@amapa.cz; adresa odesílatele bude vyplněna podle vstupního formuláře.

**Comment by MichalKminek** [comment]
Reseni je nakonec jednodussi tim, ze prijemce mailu jsme my. SMTP server je mail.arup.cas.cz port 25. Overeni neni potreba pro tento pripad.

**Comment by motyc** [comment]
@albertoh Email přišel, k tomu poznámky:
- přišel 2x ve stejný čas - nevím, zda to bylo schválně nebo jde o nějakou chybku
- do předmětu prosím automaticky vložit "Digitální archiv AMČR - komentář k záznamu [ident_cely]" (ident_cely doplnit automaticky podle místa užití tlačítka)
- je implementována ta reCAPTCHA? (asi ne, když sis nemohl vzít ty klíče) Nebo je tam nějaký trabl?

**Comment by albertoh** [comment]
Muj ucet inovatiky je gmailovy. Muzes mi tam pridat?

**Comment by motyc** [comment]
Přidal jsem Tě tam, zkus to prosím (https://www.google.com/u/0/recaptcha/admin/site/495277694/settings)

**Comment by albertoh** [comment]
reCaptcha implementovana

**Comment by motyc** [comment]
Skvěle, email dorazil.

**Comment by motyc** [comment]
@albertoh dva dotazy:
1. Je nějak limitována maximální délka textu? Pokud ne, asi by bylo dobré dát třeba max. 1000 znaků.
2. Chodí kopie mailu i odesílateli? Opět pokud ne, prosím posílat mu ji.

**Comment by albertoh** [comment]
Pridam do konfigurace "feedBackMaxLength"

Pro to druhe je nutne mit prihlasovaci udaje na SMTP server. Ted nemame, viz vyse [#issuecomment-996600025](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/issues/116#issuecomment-996600025)

**Comment by motyc** [comment]
> Pro to druhe je nutne mit prihlasovaci udaje na SMTP server. Ted nemame, viz vyse [#issuecomment-996600025](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/issues/116#issuecomment-996600025)

@MichalKminek můžeš prosím potřebné dodat, jestli to není nějaká velká komplikace?

**Comment by MichalKminek** [comment]
Pripravil jsem specialni udaje pro overeni proti SMTP serveru, ulozeny v citelne podobe na produkcnim serveru ve /root

**Comment by motyc** [comment]
@MichalKminek Moc děkuji!

**Comment by albertoh** [comment]
Nejde mi to. Testuju na testu, a dostavam:
 
Sending the email to the following server failed : mail.arup.cas.cz:25
javax.mail.AuthenticationFailedException: 535 5.7.0 authentication failed

**Comment by MichalKminek** [comment]
Pri komunikacci a overeni na 25 se musi pouzit StartTLS, take je mozne komunikovat na TCP/465 SMTP se SSL a overeni jmenem a heslem.

**Comment by albertoh** [comment]
Hotovo. Poslal jsem test, a me dosel mail
