### ISSUE TITLE
Mapové zobrazení dat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#117]
- [x] Zajistit plynulejší překreslování mapy (omezit načítání až po dokončení operace zoomu/posunu) = debouncing
- [x] Pokud je na PIAN v mapě napojen jediný záznam aktuálního typu, rovnou otevírat jeho detail
- [x] Do tooltipu PIAN doplnit počet souvisejících záznamů jednotlivých typů.
- [x] Export ve standardních formátech (XML/GML, CSV/WKT, GeoJSON) - vždy geoprvek + základní popisné údaje + ID podřízených záznamů (jde o ekvivalent stávajícího exportu s přidáním potřebných dat/sloupců)

### Řešení převzít z https://github.com/ARUP-CAS/aiscr-webamcr

- [x] Plné mapové zobrazení dat (body, linie, polygony)
- [x] Volba mapových podkladů
- [x] Heatmapu doplnit či nahradit clusteringem (vyžít https://github.com/leaflet/Leaflet.markercluster)
- [x] Upravit symbologii pinu (buď zmenšit, nebo zcela vyměnit za jiný symbol - třeba navrhnout a otestovat)

------------
### Doplněno
- [ ] #170

------------

### Odloženo
- [ ] #152

**Comment by motyc** [comment]
První příspěvek aktualizován. U bodů, kde lze řešení převzít z WebAMČR, by byla vhodná koordinace s @pbartosova

**Comment by albertoh** [comment]
@pbartosova Bylo by mozne geom_gml dostat ve formatu GeoJSON? A souradnice v jine projekce, idealni asi mercator EPSG:3857 ?

**Comment by motyc** [comment]
@albertoh @pbartosova Spíš by se to muselo do API doplnit jako `<geom_json>`. PostGIS to určitě bude umět exportovat, významně tak ale nabude velikost exportu PIAN. Nevím, jak je to reálné to teď rychle upravovat. Jak moc velká komplikace je provedení převodu na straně Digiarchivu? V EPSG:3857 DB pracuje nativně, takže tam by to velká obtíž být nemusela.

Napadá mne - co to vzít v tomto případě dočasnou oklikou (než se API v příštím roce upraví v souvislosti s WebAMČR) a povolit zde indexaci přímo z DB? Stejně už tam tuším pro nějaké hesláře saháme.

**Comment by motyc** [comment]
@albertoh Jen pro úplnost doplňuji informaci, kterou jsme neměli nikde zapsanou:

PIAN s přesností 4 (tj. přesnost na katastr) není třeba převádět na polygony a jako polygony zobrazovat. Týká se jich pak případně odložené issue #152, kde bychom to řešili nějak konzistentně.

**Comment by albertoh** [comment]
"Export ve standardních formátech (XML/GML, CSV/WKT, GeoJSON)"
To ma byt export vysledku? PIANu?

**Comment by motyc** [comment]
Ideálně export toho, co je právě zobrazeno (podle typu entity).

**Comment by motyc** [comment]
Rozumím, myslel jsem to takto (pardon za nepřesnost):
- Dokumenty, Projekty, Akce, Lokality = PIAN
- Samostatné nálezy = lokalizace nálezu
- Knihovna 3D = lokalizace dokumentu (podle extra_data)

**Comment by motyc** [comment]
Ještě nad tím ale přemýšlím, že by to bylo dobré navázat spíše na zobrazené výsledky a k nim ty lokalizační údaje doplnit. Jinak by to nutilo uživatele si spojovat dílčí tabulky, aby dostali ucelenou informaci...

**Comment by albertoh** [comment]
Cluster a polygony jsou k testovani.
Polygony a linie se zobrazuju kdyz nemame clustery. 

Cluster ted se generuje pro velke cislo vysledku. Ale musel jsem to omezit na 20000
Otestuj, prosim

**Comment by motyc** [comment]
Díky za nasazení, myslím, že to je na velice dobré cestě. Zde návrhy a chyby z testování (k případné diskusi):

- [ ] - clusering myslím vypadá skvěle, při větším počtu záznamů (5000+) začne být ale odezva pro vykreslení clusterů velice pomalá a na mapě se zdánlivě nic nezobrazuje (progres bar už také neběží); řešení vidím v několika směrech:
-- do určitého měřítka/počtu záznamů (>5000; limit lze dát do konfigurace, nebo by šel možná nastavovat i uživatelsky?) by se nadále používala čistě heatmapa, jen bychom nad ní vůbec nezobrazovali jednotlivé body, protože je to matoucí (seznam výsledků by však zůstal, takže by přejít na konkrétní záznam šlo)
-- clustery by se načetly, jakmile by záznamů bylo <=limit heatmapy (výchozí 5000)
-- pokud to jde, tak by byl doplněn nějaký indikátor aktivity/progress bar i při načítání clusterů
-- od konkrétního měřítka by se již vykreslily linie a polygony (nyní se zdá dobré, jen nevím, jaké přesně je to kritérium - počet záznamů? kolik je nastaveno?)

- [ ] - chování mapy (heatmapa -> clustering -> zobrazení) by měly fungovat i pro samostatné nálezy a knihovnu 3D (ta mimochodem nezobrazuje žádná data na mapě)

- [ ] - linie by měly být alespoň 2 px široké, aby byly lépe vidět

- [ ] - je třeba pomocí symbologie odlišit piny, které symbolizují centroidy vykreslených ploch/středy linií, od skutečně bodových prvků (bodové PIAN, sam. nálezy, 3D); měly by být asi významně graficky potlačené

- [ ] - ideální by bylo spojit popisek přímo s plochou/linií, nikoli jen s centroidem (tam je ale pak třeba řešit případné překryvy, nicméně máme to hotové pro webAMČR - lze asi použít)

- [ ] - linie/plocha se nevykreslí, když v zobrazení nemám centroid/střed linie - to je extrémně nepraktické, zvláště když potřebuji zoomovat v rámci větší plochy a dívat se na detaily - viz např.: https://digiarchiv-test.aiscr.cz/results?mapa=true&loc_rpt=49.989325163837904,13.98263454437256,49.99978123434087,14.023468494415285&page=0&entity=lokalita&sort=datestamp%20desc

- [ ] - středové body linií bohužel často neleží přímo na linii, se kterou souvisí a vypadá to, že jde o jiný prvek; chtělo by to nějak korigovat

- [ ] - pokud kliknu na konkrétní PIAN a zapne se tak filtr, tento filtr je schovaný pod levým menu, takže jej člověk přehlédne a při vysunutém menu nejde vypnout (to je na @pkudela)

- [ ] - tu funkci automatického otevření detailu, pokud je u PIAN pouze jeden záznam jsem myslel nikoli tak, že se to otevře když jen hýbu s mapou a zrovna to vyjde na jediný záznam, ale tak, že pokud kliknu na záznam v mapě (viz předchozí bod), tak v tu chvíli se záznam rovnou otevře, pokud je u PIAN záznam jediný (v původní verzi se pouze zapnula filtrace podle PIAN); nynější implementace je problematická v tom, že když vidím jen jeden záznam a chci odzoomovat jinam, aplikace si všimne toho jediného záznamu a přitáhne mi zobrazení zpět; asi jsem to v úvodu popsal nepřesně, omlouvám se

- [ ] - potřebovali bychom odstranit spodní hranici pro zoom, protože zobrazení není pro některé situace dostatečně detailní (opět by mělo jít řešit stejně jako ve webAMČR, kde to funguje skvěle); někdy může být žádoucí zoomovat opravdu velice blízko

- [ ] - mezi vrstvami mi chybí možnost překrýt podkladové vrstvy katastrální mapou (parcely; viz webAMČR)

**Comment by albertoh** [comment]
Pokusim se odpovidat na vsechno:

 1.- Pridal jsem stupnovani heat -> cluster -> marker. Nove jsou v konfiguraci klice:
      "docsForMarker": 200, // maximalni pocet vysledku, pri kterych vidime rovnou markery
      "docsForCluster": 10000,  // maximalni pocet vysledku pro generovani clustery
     Pokud je pocet vysledku vetsi bude heatmapa
     Indikator aktivity mizi pozdej, po kalkulaci clusteru
     Linie a polygony se kresly zaroven s markery, tj, pocet vysledku mensi nez docsForMarker

  2. - Opraveno. Ale pozor, 3D vypada divne pri moc blizke priblizeni, jak vsechny body jsou na tom samem miste

  3. - Nove v konfiguraci:
          "shape": {
                "color": "#222",
                "fillColor": "#00f",
                "weight": 2,
                "fillOpacity": 0.3
              }

 4.- Petr pripravuje nove ikonky. Bude se odlisovat

 5.- "- linie/plocha se nevykreslí, když v zobrazení nemám centroid/střed linie - to je extrémně nepraktické, "
       To bude problem. Pro implementaci takovou moznosti by bylo nutne indexovat WKT a hledat v tvarech. Meni se zpusob hledani/indexaci. Budou problemy s velikostmi dat.

  6.- "středové body linií bohužel často neleží přímo na linii, se kterou souvisí a vypadá to, že jde o jiný prvek; chtělo by to nějak korigovat"
     Ja to nemuzu korigovat. To by melo prijit z API

  7.- Opraveno

  8.- Opraveno chovani. Otestuj.

  9.- Opraveno

  10.- Doplneno

**Comment by motyc** [comment]
Díky za úpravy (položky v pořádku nekomentuji).

Ad 5 - musíme tedy vymyslet nějaký efektivní způsob, jak to obejít; zatím mne napadá, že by se daly spočítat a indexovat bounding boxy (opsané obdélníky) polygonů a linií (ty lze definovat jen pomocí rohů, takže by tolik nerostl index) a zobrazovat linie/polygony vždy, když by existoval průsečík zobrazené mapy s bounding boxem (jehož střed by klidně mohl být mimo mapu); @albertoh co myslíš? Nebo Tě napadá něco jiného?

Ad 6 - mrknu na to, v čem je problém

Ad 8 - je to lepší, nicméně ještě trošku jinak, než bylo myšleno - nyní se mi otevře detail např. i pro: https://digiarchiv-test.aiscr.cz/results?entity=akce&mapa=true&loc_rpt=49.9980031420873,13.991171498480071,50.00528193928694,14.021101948973513&page=0&sort=datestamp%20desc&pian_id=P-1241-010040, přestože na PIAN je připojeno 8 akcí; čekal bych, že se to stane např. jen u https://digiarchiv-test.aiscr.cz/results?entity=akce&mapa=true&loc_rpt=49.9980031420873,13.991171498480071,50.00528193928694,14.021101948973513&page=0&sort=datestamp%20desc&pian_id=P-1241-000069, kde je skutečně právě jedna.

**Comment by pkudela** [comment]
@motyc nakonec jsem udelal sve vlastni piny, pro budouci pripadne zmeny. Jsou ostrejsi, protoze je to primy export z krivek a zmensil jsem ho o 5px na sirku, points maji cervenou tecku, tu jsem obecne take zvetsil, muzes porovnat:
novy
![image](https://user-images.githubusercontent.com/16591052/146766862-574aa256-e61c-49e9-a2a6-2967aa1e7700.png)
soucasny stav
![image](https://user-images.githubusercontent.com/16591052/146766895-1fb54f99-b648-46dc-9736-682e9c21c3c9.png)

**Comment by motyc** [comment]
@pkudela To vypadá dobře. Asi bych to ještě korigoval po nasazení, ale myslím, že by bylo dobré:
1. Červený zmenšit celkově cca o 1/3.
2. Bílý zmenšit o cca 1/2 (jde o pomocné body, tak ať tolik neruší).

Případně nejde vytáhnout velikost pinů do config, ať to nemusíme ladit takto?

**Comment by pkudela** [comment]
@motyc co myslis zmensit, to kolecko, nebo cely pin?

**Comment by motyc** [comment]
@pkudela celý pin

**Comment by motyc** [comment]
@albertoh  Ad https://github.com/ARUP-CAS/aiscr-digiarchiv-2/issues/112#issuecomment-997907485 (tam už dále neřeším, responsivity se to netýká) 

- [ ] - Občas clustering zdánlivě vypadne, resp. clustery se nechtějí načíst. Nevím proč se to děje; když změním entitu, většinou se to refreshne a naskočí.

- [ ]  - Také se občas data nenačtou, když odzoomuji - musím ještě posunout mapu, aby se načetla data pro nový výřez. Nevím, zda to spolu nějak souvisí.

Je to taková chyba nechyba, blbě se to stopuje, tak to píšu, abys o tom věděl, ale asi to bude chtít nějak sledovat, kdy se to děje a jestli se to stává na více PC (ten problém se zoomem je obecný, ten clustering ale zlobí jen někdy).

**Comment by pkudela** [comment]
@motyc prosim otestovat velikost pinu.

**Comment by albertoh** [comment]
"Export ve standardních formátech (XML/GML, CSV/WKT, GeoJSON)"
Porad nemam uplne jasne. Mohl bys mi poslat par prikladu jak maji vypadat soubory? 
Jde mi o tech formatech: jsou na vsechna pole, jen na geo data?
Nejvice by mi pomohly priklady :)

**Comment by motyc** [comment]
> "Export ve standardních formátech (XML/GML, CSV/WKT, GeoJSON)" Porad nemam uplne jasne. Mohl bys mi poslat par prikladu jak maji vypadat soubory? Jde mi o tech formatech: jsou na vsechna pole, jen na geo data? Nejvice by mi pomohly priklady :)

Zde jsem vyrobil příklad pro export u entity akce (obdobné to bude u Dokument, Projekt, Lokalita; pro Sam. nálezy a Knihovnu 3D to je jednodušší, tam prostě jen přibude definiční bod, ale nic se jinak nemění).

[Export_priklad.xlsx](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/files/7750902/Export_priklad.xlsx)

**Comment by albertoh** [comment]
A chceme vybrat format, nebo export vsech najednou?

**Comment by motyc** [comment]
@albertoh K tomu nefunkčnímu clusteringu jsem snad našel spolehlivou cestu, jak nasimulovat:
1. Vstup na homepage https://digiarchiv-test.aiscr.cz/
2. Otevřít mapu https://digiarchiv-test.aiscr.cz/results?mapa=true
3. Zoom např. na https://digiarchiv-test.aiscr.cz/results?mapa=true&loc_rpt=49.986587115036656,13.375637241620964,50.269961664299814,14.48538946620118&page=0
4. Na mapě nic není



> A chceme vybrat format, nebo export vsech najednou?
To je dobrá otázka. Asi by nebylo špatné, kdyby si šlo vybrat. Export tak nebude zbytečně velký.

**Comment by motyc** [comment]
Velikost pinů je za mne zatím ok, ale vrátíme se k tomu případně po otestování více lidmi. V tomto to asi bude chtít širší zpětnou vazbu.

**Comment by motyc** [comment]
@albertoh Odhalená ještě drobná chybka - při kliknutí na tlačítko u záznamu se zobrazí mapa a definiční bod, ale nevykreslí se polygon/linie (např. https://digiarchiv-test.aiscr.cz/results?page=0&entity=akce&sort=datestamp%20desc&mapa=true). To se stane až při nějakém dalším překreslení mapy.

**Comment by albertoh** [comment]
Problem s clusterem opraven. Bylo to pri otevreni bez entity, t.j. dokument

**Comment by albertoh** [comment]
Export je na testovani. Modre tlacitko vedle tlacitka mapy. Lze vybirat format.
Oteviram v novem okne, jako export dopusud. Pokud budeme chtit to jako download musime definovat format souboru. Predpokladam CSV.
 Zatim koukni tak.

**Comment by motyc** [comment]
Funkčně ok, ale jsou tam dvě chyby:

- [ ] - neexportuje obsah většiny sloupců (u Dokumentů, Akcí a Lokalit; u Projektů to vypadá ok):
![image](https://user-images.githubusercontent.com/20186892/146940641-1a8296a7-4b09-4a32-88ab-163dd17907ce.png)

- [ ] - export vůbec nefunguje pro Sam. nálezy a Knihovnu 3D

**Comment by albertoh** [comment]
"export vůbec nefunguje pro Sam. nálezy a Knihovnu 3D"
Asi meli bychom dat pryc moznosti exportu kdyz mame tyhle entity, ne? Ony nemaji PIANy

**Comment by motyc** [comment]
To nevadí, měl by se prostě udělat standardní export doplněný o definiční bod (jak jsem psal už tady: https://github.com/ARUP-CAS/aiscr-digiarchiv-2/issues/117#issuecomment-998586233). Kdyby to tlačítko nějak mizelo, tak se v tom nikdo nevyzná.

**Comment by albertoh** [comment]
Opraven export. Koukni

**Comment by albertoh** [comment]
Opraveno zobrazeni tvaru pri kliknuty na zaznamu

**Comment by motyc** [comment]
Export obsahově už ok, jen u Sam. nálezů a 3D úplně nedává smysl ten výběr (WKT / GML / JSON), tam bych rovnou zobrazil výsledky).

Zobrazení tvaru - již funguje, ale po zavření záznamu (křížkem vpravo) na mapě najednou není nic (zmizí i ten do té doby viditelný PIAN), přitom by tam měly být výsledky z daného výřezu (ty se zobrazí až po posunu okna).

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Oboje potvrzuji.

**Comment by motyc** [comment]
- [ ] v mapě na úrovni celé ČR vyberu rámečkem polovinu republiky, zobrazení hustoty výskytu zamrzne na typu heat-mapa, můžu pak zoomovat kam chci, ale zobrazení zůstane jako heat-mapa (tj. nezohledňuje se poloha okna a netvoří se podvýběr)
- [ ] Podobně, pokud jsem v mapě dost zazoomovaný, abych viděl clustering a aktivuji výběr rámečkem, můžu poté zoomovat, jak chci, ale PIANy uvidím jen jako body (žádné linie ani polygony)

**Comment by albertoh** [comment]
Chova se tak, protoze vysledky jsou vypocitame pro plochu ramecku. Ten ramecek urci nezasvisle od zoomu. Toto chovani je ted i na produkci
Jak si predstavujes ze se ma chovat? Pri zoomovani zrusit ramecek?

**Comment by albertoh** [comment]
Hotovo, otestuj

**Comment by motyc** [comment]
Nyní se chování vrátilo zpět do stavu před úpravou. Není omylem nasazena původní verze kódu?

**Comment by pkudela** [comment]
@albertoh vcera vecer jsem si pullnul a nasadil novou verzi, delal jsem upravy ohledne prekladu a pridani tlacitek v persistentnim odkazu, tak jestli to neni tim.

**Comment by albertoh** [comment]
Asi to bylo ono. Zkopiroval jsem znovu build, a vidim to dobre

**Comment by motyc** [comment]
Funguje to skvěle, potvrzuji!

**Comment by motyc** [comment]
@albertoh Přecijen tím ale vznikla jedna drobnost - když mapu zavřu, zůstane v aplikovaných fitrech zobrazená sice správná hodnota (box), ale aplikuje se poslední pozice okna z mapy. Při zavření mapy by se toto omezení "pohledem" aplikovat už nemělo.

**Comment by albertoh** [comment]
Zkus to ted. Pri otevirani mapy vidime celou republiku s vyberem, pokud je

**Comment by motyc** [comment]
Návrat na mapu se nyní chová moc pěkně - to určitě zachovejme. Mám dojem, že jsem se v jedné věci stále nepochopili. Jde o aplikaci mapového výběru při **odchodu** z mapy:
- mělo by platit, že když nad mapou udělám výběr a odejdu z mapy, tak zůstane filtr takto aplikovaný a počet výsledků i při zavřené mapě tomu odpovídá - z pohledu uživatele je to logické proto, protože "Mapový výběr" se přímo zobrazuje v části "Aktivní filtry" a zůstává tam i po zavření mapy - to je mimochodem chování i teď na produkci a je to chování žádoucí
Toto číslo:
![image](https://user-images.githubusercontent.com/20186892/152139554-42e3411e-e172-43e7-9a5d-b0c2a93690ef.png)

By mělo být shodné s tímto:
![image](https://user-images.githubusercontent.com/20186892/152139663-6fc3ef6d-161d-4c94-824b-4c2553ef9951.png)


V předchozím příspěvku jsem šlo pouze o to, že kromě výše popsaného filtru ("Mapový výběr") se automaticky aplikoval ještě filtr podle polohy okna, což je žádoucí chování při otevřené mapě, ale po jejím zavření by se nadále tato filtrace aplikovat neměla, protože přestane být relevantní.

**Comment by albertoh** [comment]
Opraveno. Chyba ve zpracovani dotazu pri zavrene mape

**Comment by motyc** [comment]
Je to perfektní, děkuji.

**Comment by motyc** [comment]
@albertoh  Omlouvám se, ale při tvorbě nápovědy k nové verzi jsem přišel ještě na jednu nejasnost v chování, která asi bude spíš pozůstatkem původního řešení, než záměrem - když mám otevřenou mapu a menu s výsledky má více stránek, tak:

1 - při listování na heatmapou se nic neděje - **to je ok**
2 - při listování nad clusteringem se výsledky nějak asi mění, ale není mi vůbec jasné, podle jakého klíče (logiku to moc nedává) -> **zobrazoval bych vždy to samé a výsledky na mapě neměnil**
3 - při plném zobrazení se asi zobrazují jen výsledky na daném listu. To mi vzhledem k novému nastavení přijde zbytečné, protože omezení počtu viditelných prvků je dáno již samotným typem zobrazení. -> **opět, bych při listování výsledky na mapě nijak neměnil (zobrazoval vše)**

Nebo je v současném řešení nějaký hlubší záměr a je k němu důvod?

**Comment by albertoh** [comment]
Zmenim chovani pri clustering aby nic se nezmenilo.

3.- to nevidim, neni listovani. Na mape jsou max 200 bodu, a vlevo vysledky maji taky do 200 zaznamu bez listovani

**Comment by motyc** [comment]
Ad 2 - potvrzuji, je to takto v pořádku.

Ad 3 - nevidíš, protože u sebe máš asi nastavenou jinak konfiguraci. Já jsem na testu počet navýšil, abych našel co nejlepší hranici. Myslel jsem, že to běhá dobře i s vyšší, jenže teď mi došlo, že se ve skutečnosti nic neměnilo, protože v tu chvíli začal fungovat efekt listování. Nejlepší bude to fakt zrušit, protože v tu chvíli to půjde plně řídit konfigurací.

**Comment by motyc** [comment]
Ten předchozí komentář je vyřešený, ale bohužel tam vznikla nějaká boty, kdy nyní při listování vůbec nefunguje (napři zapnuté heatmapě či clusteringu tam tam možnost sice je, ale při kliknutí na šipku vpravo se refreshne okno, ale další výsledky se nenačtou).

**Comment by albertoh** [comment]
Nevidim... ja muzu listovat
![image](https://user-images.githubusercontent.com/5946836/153220552-249a3302-05e4-47b9-9ed3-c88b898273ba.png)
![image](https://user-images.githubusercontent.com/5946836/153220615-2ca20388-4f2e-48fe-8fe4-dc020f846606.png)

**Comment by albertoh** [comment]
Opraveno.
Byl to ale nejen zakopany, ale i zapeklity pes, dalo mi to zabrat.
Vinik byl ten plugin pro mapovy vyber, ktere mi furt prenastavoval stranku

**Comment by motyc** [comment]
Potvrzuji, že je vše funkční.

Prosím, pokud by to šlo opravdu snadno jen změnou nějakého parametru, tak je nešikovné, jak ten výběr ve výchozím nastavení má ovládací prvky schované za interfacem. Pokud by šlo to výchozí zobrazení zůžit jak je cca naznačeno na obrázku, bylo by to super. Ale pokud je to zase nějaká pruda, už to nech být a vyřešíme to příště.
![image](https://user-images.githubusercontent.com/20186892/153388473-72a6eea7-ad95-4ea7-b053-64582d48807f.png)

**Comment by albertoh** [comment]
Pridal jsem nove do mapOptions:
"selectionInitPad": -0.90
Je to cislo o kolik se zmensi (zvetsi) vyber pri otevreni oproti mapovemu pohledu

**Comment by motyc** [comment]
Super, to je ideální!
