### ISSUE TITLE
Zobrazení data poslední změny záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#118]
Z API indexovat k hlavním typům záznamů také element record.header.datestamp a umožnit podle něj vyhledávat a řadit. Jedná se o datum poslední změny záznamu.

Toto datum vhodným způsobem zobrazit v hlavičce záznamu, např. takto:
![image](https://user-images.githubusercontent.com/20186892/133786265-eeb58dfb-079f-4314-984e-af047113865b.png)

**Comment by pkudela** [comment]
@albertoh pripraveno, staci doplnit naindexovanou hotnotu

![image](https://user-images.githubusercontent.com/16591052/145004429-23ac9170-1666-43ae-9bce-2046125e44dc.png)

**Comment by albertoh** [comment]
Az zkonci reindexaci. Ted uz je videt u lokalit
