### ISSUE TITLE
Chyba okna pro přihlášení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#119]
Když zadám chybné údaje pro přihlášení, okno se zacyklí v režimu načítání (nahoře stále dokola běhá lišta):

![image](https://user-images.githubusercontent.com/20186892/114193673-0cbb4e00-994f-11eb-825f-095aa3e96533.png)

**Comment by albertoh** [comment]
Opraveno na testu.

**Comment by motyc** [comment]
Lze nasadit
