### ISSUE TITLE
Google analytics v nové verzi

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#12]
Prosím aby nebylo opomenuto přesunutí kódu pro Google Analytics z původní verze do nové. Výpadek ve statistikách by byl velice na škodu.

**Comment by albertoh** [comment]
Je to tam

**Comment by motyc** [comment]
Perfektní díky.

**Comment by motyc** [comment]
Momentálně návštěvnost asi google nevidí. Měřící kód na stránce je:
`
--
  | <script>
  | (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){ (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  | ga('create', 'UA-79200582-3', 'auto');
  | //ga('send', 'pageview');
  | </script>`

Měřící kód od Googlu je (takže se to trošku liší, i když ID je stejné:
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-79200582-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-79200582-3');
</script>`

**Comment by motyc** [comment]
Upravil jsem původní komentář, protože se to špatně interpretovalo v zobrazení (přidáno jako TXT soubory).

**Comment by albertoh** [comment]
Zmeneno

**Comment by motyc** [comment]
Funguje, zavírám.
