### ISSUE TITLE
Typy záznamů doplnit o tooltipy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#124]
Při najetí na volbu typu záznamu na úvodní obrazovce i v seznamu výsledků umožnit zobrazení tooltipu z bližším popisem charakteristik daného typu záznamů.

**Comment by albertoh** [comment]
@motyc Prosim o dadani podrobnych popisu

**Comment by motyc** [comment]
@albertoh Šlo by prosím zatím jen vytvořit patřičné klíče v překladech a k nim doplnit lorem ipsum? Texty vyrobím během příštího týdne...

**Comment by pkudela** [comment]
@motyc ano, slo a je to hotove, pripravene, ale musel jsem zmenit strukturu klicu a tim padem predelat v kodu. Nyni je struktura klicu takovato:

![image](https://user-images.githubusercontent.com/16591052/144989142-5c6b4327-d324-4635-9bd1-2b0bf5c098a5.png)

**Comment by motyc** [comment]
Ok, jen prosím @pkudela  - bylo by možné v tooltipech (obecně) trošku zvětšit písmo? Pro řadu lidí to může být špatně čitelné.

**Comment by pkudela** [comment]
Ano, lze to udelat globalne, az to udelam, otestujes a potvrdis, jestli je to ok.
