### ISSUE TITLE
Změna ikony filtrace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#125]
Stávající ikona není pro uživatele úplně srozumitelná, změníme na filter_alt

- [ ] @motyc nezapomenout upravit v nápovědě

**Comment by motyc** [comment]
Zde prosím jen o kontrolu a nasazení.

**Comment by albertoh** [comment]
Opraveno na tetstu

**Comment by motyc** [comment]
Lze nasadit.
