### ISSUE TITLE
Nadpisy - sjednocení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#126]
Nadpisy v detailu jsou tučnější než nadpis celého záznamu (a tím pádem i více vystupují. Upravit font-weight nadpisu na 700:

PŘED
![image](https://user-images.githubusercontent.com/20186892/114209281-bc4bec80-995e-11eb-8823-0abf2bef1203.png)

PO
![image](https://user-images.githubusercontent.com/20186892/114209177-a0484b00-995e-11eb-99a9-87dc278ff093.png)

**Comment by albertoh** [comment]
Opraveno na testu

**Comment by motyc** [comment]
Lze nasadit
