### ISSUE TITLE
Na stránce persistentního linku zobrazovat parent záznamy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#128]
Jde o případy, kdy zobrazený záznam není přímo entitou (základním typem záznamu). V takovém případě parent záznam(y) zařadit do části "Související záznamy".

**Comment by motyc** [comment]
Nelze testovat, viz #139

**Comment by albertoh** [comment]
Viz #139

**Comment by motyc** [comment]
Funkčně ok, pouze graficky je tam chybka např. u https://digiarchiv-test.aiscr.cz/id/C-9115028A-K01, kdy část "Související záznamy" nemá ten šedý řádek na začátku. U https://digiarchiv-test.aiscr.cz/id/C-9115028A-D01 je to správně.

![image](https://user-images.githubusercontent.com/20186892/145991138-7e61f7d9-22ca-4959-8423-6f331f7301d3.png)

![image](https://user-images.githubusercontent.com/20186892/145991220-eb56eb74-9459-42f9-bbef-6544e6dd50cc.png)

To je tedy asi na @pkudela

**Comment by motyc** [comment]
Tak ještě doplňuji:
- [ ] - zlobí to pro komponenty dokumentu (viz https://digiarchiv-test.aiscr.cz/id/C-LD-000012218-K01?lang=cs) - nic se nezobrazí.
- [ ] - výškový bod se zobrazí, ale nemá související záznam: https://digiarchiv-test.aiscr.cz/id/ADB-PRAH72-6727-V0001?lang=cs
- [ ] - jednotka dokumentu - zobrazí se jen nadpis - https://digiarchiv-test.aiscr.cz/id/C-TX-199002099-D01?lang=cs (ale třeba toto funguje: https://digiarchiv-test.aiscr.cz/id/C-LD-000000457-D01?lang=cs)

**Comment by motyc** [comment]
Výše uvedené je již v pořádku, ale ještě to není úplně ideální:

- [ ] - funkční tlačítka (persistentní link a tisk) se někdy zobrazují (https://digiarchiv-test.aiscr.cz/id/C-TX-199002099-D01?lang=cs), jindy nikoli (https://digiarchiv-test.aiscr.cz/id/C-9135922A-K01?lang=cs), navíc jsou nestandardně zarovnány vlevo (běžně je máme vpravo)
![image](https://user-images.githubusercontent.com/20186892/146192648-bacbebac-6464-497f-bdb4-831a38173e89.png)

- [ ] - u výškového bodu se nadpis vypisuje fontem jako běžný text a vypadá to zvláštně
![image](https://user-images.githubusercontent.com/20186892/146192801-e89a63ac-7722-4808-a7de-d812f6877de6.png)

- [ ] - jako související záznam pro komponentu dokumentu (https://digiarchiv-test.aiscr.cz/id/C-LD-000012218-K01?lang=cs) by bylo lepší zobrazovat nadřazený dokument (https://digiarchiv-test.aiscr.cz/id/C-LD-000012218?lang=cs), nikoli nadřazenou obsahovou část/jednotku dokumentu (https://digiarchiv-test.aiscr.cz/id/C-LD-000012218-D01?lang=cs)

To by snad už mělo být vše.

**Comment by pkudela** [comment]
@motyc potrebuju ujasnit:
ad 1) https://digiarchiv-test.aiscr.cz/id/C-TX-199002099-D01?lang=cs To, ze se zarovnavaji tlacitka vlevo je zpusobeno tim, ze tam vlevo neni pocet akci, pocet souboru atd., jen se chci ujistit, je to spravny stav? Pokud ano, osetrim zarovnani vpravo. Dale -> https://digiarchiv-test.aiscr.cz/id/C-9135922A-K01?lang=cs to, ze tlaticka chybi uplne je spatne? Prosim o upresneni.
ad 2) Prosim posli konkretni odkaz na testu, at to mohu testovat oproti konkretnimu zaznamu
ad 3) Tady jsem se ztratil, vubec nerozumim tomu, co po me chces. Prosim, udelej nejaky screenshot, nebo si kvuli tomu pak zavolame.

**Comment by motyc** [comment]
@pkudela
ad 1) no, ono to je celkem logické, že to tam u některých těch podřazených entit není, protože by to nedávalo úplně smysl; na druhou stranu pokud by pomohlo to tam vypisovat, nemám s tím problém;

ad 2) https://digiarchiv-test.aiscr.cz/id/ADB-PRAH72-6727-V0001?lang=cs

ad 3) tohle je spíš na @albertoh; problém je, že nyní se vypíše toto:
![image](https://user-images.githubusercontent.com/20186892/147221470-20c7d31c-22a5-44ca-bec5-a4196fa5dae6.png)

V souladu s logikou jinde (a lepší pro praktické užití) by však bylo spíše toto:
![image](https://user-images.githubusercontent.com/20186892/147221648-a3f2fb47-1010-418f-be5a-746f90622da3.png)

**Comment by pkudela** [comment]
@motyc ad 1) neni to nutne vypisovat, ja se jen ptal,, abych si byl jist, jakym zpusobem to osetrit, jestli je to logicke ci ne me v podstate nezajima :) ad 2) dik ad 3) nechavam na aleberta, pripadne se s nim dohodnu

**Comment by albertoh** [comment]
Bod 3 hotovy

**Comment by pkudela** [comment]
@motyc hotovo, nasazeno, prosim o oestovat

**Comment by motyc** [comment]
Původní opravy ok, ale ještě na dvě chybky jsem narazil (oboje asi na @albertoh):
- [ ] - tlačítko pro persistentní link se nyní chová jinak, než v seznamu záznamů (chybí rozbalovací menu implementované podle #149)
- [ ] - u https://digiarchiv-test.aiscr.cz/id/ADB-PRAH72-6727?lang=cs se nevypíšou data pro výškové body (jen odrážky a formátování)

Petře (@pkudela) teď když to vidím, byl by ještě velký problém tam přecijen tam tlačítka Persistentní link, Tisk a Odeslat komentář dávat vždy? Ono je trošku matoucí, jak to tam někdy je a jindy není a tyto by mělo jít použít vždy, bez ohledu na charakter záznamu (zbylá, tj. Zobrazit na mapě a BibTeX by zůstaly jen tam, kde jsou nyní, tj. u hlavních entit). Pardon, že jsem to nezadal rovnou. Jestli nejsou hodiny, tak se domluvíme zvlášť.

**Comment by pkudela** [comment]
ad 1) je na me ad 2) je na @albertoh a to pod tim udelam

**Comment by pkudela** [comment]
bod 1 hotov, komentar pod tim take, ale zatim jen u jednotky-dokumentu viz. screenshot, pokud to ma byt i jinde prosim @motyc spefifikuj kde

**Comment by pkudela** [comment]
@motyc prosim hod mi sem persistentni odkazy na vsechny typy, abych mohl overit, jestli lze doplnit vsude buttony. Prosim v nasledujicim tvaru:
nazev typu -> pers. odkaz na testovaci server

**Comment by motyc** [comment]
@pkudela zde to je:

- Dokument - https://digiarchiv-test.aiscr.cz/id/C-TX-201900674?lang=cs
- Projekt - https://digiarchiv-test.aiscr.cz/id/M-202100128?lang=cs
- Akce - https://digiarchiv-test.aiscr.cz/id/M-202100128A?lang=cs
- Lokalita - https://digiarchiv-test.aiscr.cz/id/C-N9000375?lang=cs
- Samostatný nález - https://digiarchiv-test.aiscr.cz/id/M-202004181-N00001?lang=cs
- Model - https://digiarchiv-test.aiscr.cz/id/C-3D-202100001?lang=cs
- Dokumentační jednotka - https://digiarchiv-test.aiscr.cz/id/C-9000547A-D01?lang=cs
- Komponenta - https://digiarchiv-test.aiscr.cz/id/C-9000547A-K01?lang=cs
- ADB - https://digiarchiv-test.aiscr.cz/id/ADB-PRAH72-6727?lang=cs
- Výškový bod - https://digiarchiv-test.aiscr.cz/id/ADB-PRAH72-6727-V0001?lang=cs
- PIAN - https://digiarchiv-test.aiscr.cz/id/P-1211-100648?lang=cs
- Obsahová část (jednotka dokumentu) - https://digiarchiv-test.aiscr.cz/id/C-DT-100005205-D01?lang=cs
- Komponenta dokumentu - https://digiarchiv-test.aiscr.cz/id/C-LD-000000030-K01?lang=cs
- Let - https://digiarchiv-test.aiscr.cz/id/C-LET-00158?lang=cs

**Comment by pkudela** [comment]
@motyc, dival jsem se na ty odkazy a zkoumal v kodu a neni to opravdu tak jednoduche, jak jsem Ti uz rikal po skype. Cili prosim vytvor separatni issue, popis to a vloz tam ty odkazy a dej jako enhacement pro dalsi kolo, jak jsme si rekli minuly tyden. Nasadim novou verzi a dam k testovani, toto issue by tim padem melo byt snad hotove.

**Comment by pkudela** [comment]
@motyc respektive ted k testovani nemuzu dat, protoze mam rozdelane ty klice, takze nektere preklady jsou rozbite.

**Comment by motyc** [comment]
@pkudela Zapomněl jsem toto otestovat - zde drobné korekce. Řeším jen položky, kde již nějaká tlačítka máme, takže by tam neměl nastávat problém při doplnění (pokud ano, řešme to v #172):
- [ ] u PIAN (https://digiarchiv-test.aiscr.cz/id/P-1211-100648?lang=cs) chybí: Odkazy, Feedback
- [ ] u letu (https://digiarchiv-test.aiscr.cz/id/C-LET-00158?lang=cs) chybí: Odkazy, Feedback

Jinak je vše v pohodě.

**Comment by motyc** [comment]
Vše ok
