### ISSUE TITLE
Chyba indexace projektů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#129]
Indexace v logu (catalina.2021-04-11.log) hlásí: Misshaped element at 1463539 [character 98 line 34291]

Selhala jak automatická indexace, tak pokus o reindex.

Je to chyba v API, nebo na straně Digiarchivu?

**Comment by albertoh** [comment]
Po dlouhe badani, vidim tohle:
Volani na OAI pro resumptionToken 2021-04-12.oai_amcr.36000.projekt.36000.1000...t opakovane hodi vyjimku pri parsovani odpoved. Na browseru to vypada v poradu, ale pri debugovani vidim chybu
Internal transformation error
pri zpracovani identifikatoru 
`<identifier>https://api.aiscr.cz/id/C-202100852</identifier>`
Tento identifikator ale neexistuje.

Prosim o kontrolu generovane OAI odpoved.

**Comment by albertoh** [comment]
Jeste dodam: pri indexaci pouzivame uzivatel admin, ktery dostava vic zaznamu, nez bezne volani

**Comment by motyc** [comment]
Záznam vypadá takto, pouze jsem vymazal osobní údaje. Co by na něm mělo být chybně?

```
<?xml version="1.0" encoding="UTF-8"?><OAI-PMH xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openarchives.org/OAI/2.0/">
<responseDate>2021-04-12T08:02:35Z</responseDate>
<request verb="GetRecord" metadataPrefix="oai_amcr" identifier="https://api.aiscr.cz/id/C-202100852">https://api.aiscr.cz/dapro/oai</request>
<GetRecord>
<record>
<header>
<identifier>https://api.aiscr.cz/id/C-202100852</identifier>
<datestamp>2021-01-27</datestamp>
<setSpec>projekt</setSpec>
</header>
<metadata>
<oai_amcr:amcr xmlns:oai_amcr="https://api.aiscr.cz/schema/oai_amcr" xmlns="" xsi:schemaLocation="https://api.aiscr.cz/schema/oai_amcr https://api.aiscr.cz/dapro/media/oai_amcr.xsd">
<projekt>
<ident_cely>C-202100852</ident_cely>
<stav>1</stav>
<typ_projektu>záchranný</typ_projektu>
<datetime_born>2021-01-27 12:22:00</datetime_born>
<okres>CHRUDIM</okres>
<katastr>NASAVRKY</katastr>
<podnet>Nasavrky, U Školky č. p. 246 – přeložka KNN</podnet>
<lokalita>Nasavrky</lokalita>
<parcelni_cislo>st. 343/1, 76/1</parcelni_cislo>
<planovane_zahajeni>únor 2021</planovane_zahajeni>
<objednatel>smazáno_DN</objednatel>
<odpovedna_osoba>smazáno_DN</odpovedna_osoba>
<adresa>smazáno_DN</adresa>
<telefon>-</telefon>
<email>-</email>
<organizace_zapisu>Muzeum Chrudim</organizace_zapisu>
<datum_zapisu>2021-01-27</datum_zapisu>
<odpovedny_pracovnik_zapisu>Rohlenová, Michaela</odpovedny_pracovnik_zapisu>
</projekt>
</oai_amcr:amcr>
</metadata>
</record>
</GetRecord>
</OAI-PMH>
```

**Comment by albertoh** [comment]
Problem neni v zaznamu, ale v odpovedi na volani 
https://api.aiscr.cz/dapro/oai?verb=ListRecords&resumptionToken=2021-04-12.oai_amcr.36000.projekt.36000.1000...t
jako prihlaseni uzivatel

**Comment by motyc** [comment]
Pak to je prosím na @pbartosova.
@albertoh Nebylo by možné ale zajistit, aby indexace na podobných výjimkách nekolabovala?

**Comment by motyc** [comment]
@albertoh Beru zpět svůj předchozí dotaz. Samozřejmě je to nesmysl, když další data API vůbec nepodá. Pardon.

**Comment by motyc** [comment]
Issue zde zavírám, nadále řešíme v https://github.com/ARUP-CAS/aiscr-dapro/issues/68

**Comment by pbartosova** [comment]
Chyba se poprvé objevila při sobotní indexaci. Zkusíme najít logy z toho dne.
