### ISSUE TITLE
Tlačítko aplikovat filtr

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#13]
- [ ] Mám silnou obavu, že uživatelé si neuvědomí (zvlášť vzhledem ke zvyku z původní verze), jak pracovat s tlačítkem "aplikovat filtr", resp. že jej musí stisknout po výběru hodnot z facet. Bylo by možné, aby se po výběru nějaké položky ve facetě tlačítko graficky zvýraznilo (zvětšilo/rozsvítilo/cokoli podobného)?

- [ ]  tlačítko „aplikovat filtr“, pokud není vybrána žádná hodnota, funguje jako zabalení nabídky;  bylo by lepší, aby nemělo by dvě funkce; teoreticky lze řešit tak, že sbalit facetu půjde skutečně jen tou šipkou vpravo.

**Comment by motyc** [comment]
Doplněno o druhý bod

**Comment by pkudela** [comment]
Na zaklade konzultace s Davidem odstranena ikona filtru z headeru facetu a aplikovan button "aplikovat filter" vzdy na konci seznamu facet.

![image](https://user-images.githubusercontent.com/16591052/101333662-2a7c8780-3877-11eb-942a-425735ecac01.png)

**Comment by pkudela** [comment]
@albertoh prosim o nasazeni
