### ISSUE TITLE
Chyba zobrazení třetí fotky u sam. nálezů

### ISSUE THREAD

**Issue by petrpajdla** [ARUP-CAS/aiscr-digiarchiv-2#131]
U samostatných nálezů, které mají dva a více souborů, se nezobrazuje vždy **třetí** fotka.

Čtvrtý soubor se už zase zobrazuje bez problémů, např. [M-202101534-N00031](https://digiarchiv.aiscr.cz/id/M-202101534-N00031)

**Comment by motyc** [comment]
Ještě jsem to zkoušel a zdá se mi, že to může být závislé jen na stavu generování náhledů, ale nejsem si jistý. Zde třeba vidím všechny foto: https://digiarchiv.aiscr.cz/id/M-202101534-N00031

**Comment by albertoh** [comment]
Regeneroval jsem nahledy. Jsou tam.
Nevim jak se stalo, ale mohlo byt, ze soubory nebyly na disku, zrovna kdy proces bezel. Nic jineho nenapada. Kod nema zadnou vyjimku pro "treti" soubor :)

**Comment by motyc** [comment]
V pořádku, zavírám, díky.

**Comment by petrpajdla** [comment]
Znovu otevírám. U záznamů přidaných včera se problém opakuje. Je to fakt divné, že se to děje jen u těch třetích souborů...

Např.
[M-202101534-N00048](https://digiarchiv.aiscr.cz/id/M-202101534-N00048)
[M-202101534-N00060](https://digiarchiv.aiscr.cz/id/M-202101534-N00060)
[M-202101534-N00061](https://digiarchiv.aiscr.cz/id/M-202101534-N00061)

**Comment by motyc** [comment]
@albertoh mám nápad, čím to může být - složka var/lib/digiarchiv/thumbs/F3 má oprávnění root, nikoli tomcat; je tedy možné, že tomcatem spouštěný skript do ní nedokáže zapisovat

**Comment by albertoh** [comment]
jojo, to urcite je ono. Menim majiteli adresare na tomcat
