### ISSUE TITLE
U samostatných nálezů chybí faceta organizace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#133]
Filtrace přímo ze záznamu přitom funguje.

**Comment by albertoh** [comment]
Chapu ze musime pouzivat pole predano_organizace. Ma to pole preklad v heslari?
Chceme aby facet se zobrazoval jako uz existujici facet "organizace", nebo novy facet predano_organizace?

**Comment by motyc** [comment]
Ano, mělo by to být součástí facety "organizace". Heslář se používá standardně stejný.

**Comment by albertoh** [comment]
Opravil jsem kod. Musim reindexovat samostatny nalez, ale OAI api na test vrati error.
https://api-test.aiscr.cz/dapro/oai?verb=ListRecords&metadataPrefix=oai_amcr&set=samostatny_nalez

Muzu to delat na ostrem primo, ten ma OAI funkcni

**Comment by motyc** [comment]
Přepnul jsem na testu API na produkční, reindexoval a funguje to. Lze to dát na produkci (2.0.6).

**Comment by albertoh** [comment]
Nasazeno

**Comment by motyc** [comment]
Díky, jen prosím:
- tady na GitHub nevidím commit, nemáme tu tedy aktuální kód
- je třeba to dát i na test, kde zůstala v2.0.5

**Comment by albertoh** [comment]
Je to tam

**Comment by motyc** [comment]
Díky
