### ISSUE TITLE
Konfigurace pro vyhledávání v katastrech

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#138]
Dotaz 1: https://digiarchiv.aiscr.cz/results?entity=dokument&q=Vep%C5%99ek&page=0&kategorie_dokumentu=texty

Dotaz 2: https://digiarchiv.aiscr.cz/results?entity=dokument&page=0&kategorie_dokumentu=texty&f_katastr=VEP%C5%98EK:and

Oba dotazy vrátí podobné výsledky, nikoli však stejné (to by nebylo úplně překvapivé). Důvodem ale je, že se v prvním případě fulltextem nevyhledají dokumenty, kde je katastr "Vepřek" poděděný z akce a nikoli součástí neident. akce. Dokážu nějak při současném stavu upravit konfiguraci, aby to prohledávalo oba případy fulltextem?

**Comment by albertoh** [comment]
Melo by jit pres konfiguraci serverove casti. Do seznamu "indexFieldsByType" pod klic "dokument" pridat
"parent_akce_okres",
"parent_akce_katastr"

Po te reindexovat

**Comment by motyc** [comment]
Díky, vyzkouším

**Comment by motyc** [comment]
Funguje, zavírám.
