### ISSUE TITLE
Pokud jsem v anglické verzi a kliknu na persistentní link, nový tab je v češtině

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#139]
Jazyk by se měl ideálně zachovat.

**Comment by motyc** [comment]
Nelze testovat, stránka persistentního linku je zcela rozhozená:

![image](https://user-images.githubusercontent.com/20186892/145981314-c2860c20-dc3b-468a-ae67-d56de8c05bf2.png)

**Comment by albertoh** [comment]
service pro nodejs nebyla restartovana
@pkudela Po nazaseni nove verze musi se restartovat:
  systemctl restart  nodejs_digiarchiv2.service

**Comment by motyc** [comment]
V pořádku.

**Comment by motyc** [comment]
Ještě jsem přišel na jednu věc - totéž se děje při tisku, bylo by prosím možné řešení replikovat i tam?
