### ISSUE TITLE
Thumbs generator nic negeneruje

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#14]
Na produkci se ani nyní nevygenerovaly náhledy pro samostatné nálezy. Vzhledem k tomu, že tato část kódu se patrně neměnila, bude třeba to opravit a opravu zahrnout i do nové verze Digiarchivu. Automatické generování tam zjevně selhává.

**Comment by albertoh** [comment]
Spustil jsem generator nahledu rucne, bez jakych koli zmen, a nahledy se vygenerovaly spravne.
Nevim jak je nastaven cron pro automaticke generovani.
Taky jsem reindexoval samostatne_nalezy, aby aplikace spravne nasla bez volby "zahrnout dokumenty bez náhledu"

**Comment by motyc** [comment]
Cron musí běžet, protože jinak by se negenerovaly náhledy z ostatních typů dokumentů. Nemůže tam být nějaký špatný parametr? Kdo to případně může prohlédnout @pbartosova nebo @MichalKminek ? Dali byste se výpis z cronu k Digiarchivu?

**Comment by MichalKminek** [comment]
O nahledy se stara sluzba thumbs_generator.service, ktera spousti /usr/bin/java -Xmx35g -Damcr_app_dir=/var/lib/archeo/amcr/ -jar /usr/share/ThumbsGenerator/ThumbnailsGenerator-1.0.jar, po ukonceni ceka 1h a pak se spusti znovu.

**Comment by motyc** [comment]
@albertoh Na novém serveru se to asi bude nastavovat nově, tak to prosím nezapomeňte odladit. Nebo to s nasazením nové verze nesouvisí?

**Comment by motyc** [comment]
Po nasazení nové produkce přestal asi Thumbs Generator fungovat úplně. Prosím o prověření a brzkou opravu.

**Comment by motyc** [comment]
Mimochodem - zdá se mi, že kód aplikace není přenesen do tohoto nového repozitáře a zůstal zde: https://github.com/ARUP-CAS/aiscr-digiarchiv/tree/master/ThumbnailsGenerator

**Comment by albertoh** [comment]
Kod jsem pridal
