### ISSUE TITLE
Do samostatného nálezu doplnit údaje

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#147]
Viz https://docs.google.com/document/d/15bllyvwT-qX6gYm4-KszoiWC3meL_C2V/edit#

Pozor - souřadnice jsou údaj chráněný na základě přístupnosti.

**Comment by motyc** [comment]
Výpis kategorie v pořádku. Definiční bod se ale vypisuje jen tady: https://digiarchiv-test.aiscr.cz/id/C-202009779-N00001?lang=cs

Když se na totéž dívám přes výsledky (https://digiarchiv-test.aiscr.cz/results?entity=samostatny_nalez&pristupnost=A:or&page=0), tak tam souřadnice nejsou.

**Comment by albertoh** [comment]
Opaveno

**Comment by motyc** [comment]
Potvrzuji
