### ISSUE TITLE
Přidat proklik do API

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#149]
U každého záznamu umožnit přechod na jeho ekvivalent v API. Např. pro https://digiarchiv.aiscr.cz/id/M-202101534-N00266 přidat proklik na https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/M-202101534-N00266&metadataPrefix=oai_amcr

- [x] - přidat mezi ovládací prvky (u Zobrazit detail)
- [x] - umožnit volbu metadatového formátu (AMČR, Dublin Core, CIDOC-CRM) - podle toho se zvolí metadataPrefix

**Comment by pkudela** [comment]
hotovo.
