### ISSUE TITLE
Nefunguje landing page persistentních linků

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#15]
Zůstane zaseklé při načítání.

**Comment by albertoh** [comment]
Opraveno. Zmena v konfiguraci

**Comment by motyc** [comment]
Ano, již ok.

**Comment by motyc** [comment]
Tak ještě znovu otevírám - už to zase nefunguje.

**Comment by albertoh** [comment]
Nasel jsem problem. Pri restartu aplikaci se konfigurace resetovala. 
Opraveno
