### ISSUE TITLE
V citaci se v případě organizace vypisuje klíč, nikoli překlad

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#151]
Je to dobře viditelné na testu, kde jsem aktualizoval heslář organizací: https://digiarchiv-test.aiscr.cz/id/C-TX-202100001

Je tam "Muzeum Plzeň", mělo by být "Západočeské muzeum v Plzni, p.o.". Stejně je to vidět i při přepnutí CS/EN

(bude patrně platit i pro BibTeX)

**Comment by albertoh** [comment]
Hotovo
