### ISSUE TITLE
Doladění mapy u persistentního linku

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#16]
- [ ]  někam zmizel ten detail záznamu, když mám otevřenou mapu pro daný záznam
- [x]  když v této verzi mapy zoomuji, tak tam hrozně problikává patička a působí to velice divně

**Comment by albertoh** [comment]
Detail zmizel po domluve. Tady mame detail zaznamu pred tim s celou strukturou rozbalenou...
Blikani opravim

**Comment by albertoh** [comment]
Blikani opraveno

**Comment by motyc** [comment]
Ad ten detail - to jsme se možná špatně pochopili (ale samozřejmě už si to přesně nepamatuju) - já myslím, že šlo jen o to, aby detail právě nebyl rovnou rozbalený, ale normálně se zobrazil zabalený a rozbalit šel na vyžádání. Šlo by to, nebo už je to zas komplikovaný zásah?
Ad blikání - potvrzuji, bez problémů.

**Comment by albertoh** [comment]
Pokud bude ten detail zobrazen, bude mozne tu kartu zavrit? Kdyz se zavre uz nebude mozne otevrit (neni seznam vlevo)

**Comment by motyc** [comment]
Stačilo by, aby šla zabalit/rozbalit, ale úplně zavírat ji myslím není třeba (vždy tam budou jen lokalizace daného záznamu, takže se to pohodlně vejde).

**Comment by albertoh** [comment]
opraveno
