### ISSUE TITLE
Chybná interpretace datumů při vyhledávání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#169]
Doplňuji jeden odhalený bug související s vyhledáváním:

- [x]  Když vyhledám https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc&let_datum=1992-06-24,1992-06-24:or, najdou se fotky, u nichž datum letu odpovídá 1992-06-25 (tj. o den později, než je stanoveno výše).

Při zadání https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc&let_datum=1992-06-25,1992-06-25:or to nenalezne nic.

- [x]  Zadání https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc&datum_provedeni=2021-02-01,2021-02-01:or dává úplně nesmyslné výsledky.

Naproti tomu https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc&extra_data_datum_vzniku=1992-06-24,1992-06-24:or funguje dobře.

Je to zjevně celé nějaké zmatené a je třeba to blíže prověřit (v různých případech) a opravit. Nevím, zda to řešit spolu se stávajícími úpravami, nebo odděleně, ale je třeba s tím něco provést.

**Comment by albertoh** [comment]
Opraveno na testu
Jednalo se o problem s posunem na letni cas

**Comment by motyc** [comment]
Ano, potvrzuji opravu prvního problému, ale ten druhý zůstal (https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc&datum_provedeni=2021-02-01,2021-02-01:or) - vůbec si nedokážu vysvětlit, na základě čeho se výsledky zobrazují.

**Comment by albertoh** [comment]
Tady je problem v datech.
Vsechny tri nalezene dokumenty maji neident_akce s datum ukonceni driv nez datum zahajeni:

ident_cely: "C-TX-196804340-D01"
katastr: "SEMICE U PÍSKU"
lokalizace: "Osada Flekačky   .trať  \"Havírky\", ppč. .2374."
okres: "PÍSEK"
rok_ukonceni: 1967
rok_zahajeni: 1968
vedouci: "Kudrnáč, Jaroslav"

ident_cely: "C-TX-199201892-D01"
katastr: "KARDAŠOVA ŘEČICE"
lokalizace: "Zbytky hradu v Kardašově Řečici."
okres: "JINDŘICHŮV HRADEC"
rok_ukonceni: 1991
rok_zahajeni: 1992
vedouci: "Durdík, Tomáš"

  ident_cely: "C-TX-197600893-D01"
  katastr: "HRADIŠTĚ U PÍSKU"
  lokalizace: "V Dolinách a Na Čapíku."
  okres: "PÍSEK"
  rok_ukonceni: 1895
  rok_zahajeni: 1898

**Comment by motyc** [comment]
Aha, teď si vzpomínám, že už jsme o tom kdysi mluvili. Omlouvám se, moje chyba, že jsem to zapomněl a v datech jsme to nevyřešili. Opravu potvrzuji.
