### ISSUE TITLE
Chyby po nasazení produkční verze 2.1.0

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#177]
- [ ] Chyba indexace u nálezů (chybí náhledy a datum poslední změny) 
![image](https://user-images.githubusercontent.com/20186892/153707264-2ee47bc5-eedc-459e-b354-a4ca52ba51f9.png)

- [x] Když zadám neplatný persistentní link, nevyskočí chybová hláška - místo toho se stránka zacyklí.
![image](https://user-images.githubusercontent.com/20186892/153707416-e21da7c1-a07a-4b19-86d9-159fe53076fb.png)

- [x] Chybějící překlad na stránce persistentního linku
![image](https://user-images.githubusercontent.com/20186892/153706922-3551f591-252e-4174-a6d3-b795a821419e.png)

**Comment by albertoh** [comment]
Je to i na produkci

**Comment by motyc** [comment]
@albertoh Stále tam ale zůstává problém, že u samostatných nálezů nejsou vidět žádné náhledy.

**Comment by albertoh** [comment]
Promin, to jsem si nevsiml. Uz je opraveno

**Comment by motyc** [comment]
V pořádku, potvrzuji a zavírám. Lze sloučit ty branche. Moc děkuji!
