### ISSUE TITLE
Chyba oddělovače jmen v "Citujte jako"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#178]
Původně v datech je středník bez mezer ("Motyková-Šneidrová, Karla;Palečková, Hana"). Zobrazuje se čárka bez mezery (např. "Motyková-Šneidrová, Karla,Palečková, Hana"). Ideálně nahradit dlouhou pomlčkou s mezerami na obou stranách (např. "Motyková-Šneidrová, Karla – Palečková, Hana").

**Comment by albertoh** [comment]
opraveno

**Comment by motyc** [comment]
V pořádku
