### ISSUE TITLE
Při stahování otvírat soubory v novém tabu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#183]
Zejména při stahování PDF je problém v tom, že pokud se PDF po stažení otevře ve stejném okně, nejde se snadno vrátit na stejné místo v aplikaci. Směřování downloadu do nového tabu to vyřeší.

**Comment by albertoh** [comment]
To plati? Ted soubory se stahujou jako attachment, tj, primo do stazene soubory prihlizece

**Comment by motyc** [comment]
Máš pravdu, tohle je asi už úplně irelevantní...
