### ISSUE TITLE
Chybná citace při stahování fotky samostatného nálezu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#185]
Při zobrazení citace samostatného nálezu při stahování fotky se zobrazuje chybná verze citace (neodpovídá citaci na stránce persistentního odkazu: https://digiarchiv.aiscr.cz/id/C-202111632-N00044).

![image](https://user-images.githubusercontent.com/20186892/161621335-0ea3d1ec-a3b7-4706-9930-6f7496f95621.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
V pořádku.
