### ISSUE TITLE
Provést merge do hlavního branche

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#188]
Tím milestone uzavřeme.

**Comment by albertoh** [comment]
Hotovo

**Comment by motyc** [comment]
Díky, můžu tedy původní https://github.com/ARUP-CAS/aiscr-digiarchiv-2/tree/dev_v.2.1.0 odstranit?

**Comment by albertoh** [comment]
Muzeme

**Comment by motyc** [comment]
Hází mi to nějakou chybu, zkusil bys to prosím ty?

**Comment by motyc** [comment]
Povedlo se, zavírám.
