### ISSUE TITLE
Zlepšit zobrazení menu na úvodní stránce na mobilu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#196]
- [x] Při použití tlačítka u dokumentu na mobilu se submenu rozbalí mimo zobrazení, takže to vypadá, že se nic nestalo. Zobrazit hned pod položkou Dokumenty.

![image](https://user-images.githubusercontent.com/20186892/170126736-496f6434-4fd2-472d-8409-b5277d479ce7.png)

![image](https://user-images.githubusercontent.com/20186892/170127167-951105ae-f600-403a-87c8-24569e69cb48.png)

- [x] Ještě doplňuji druhý problém, a to je zobrazení výsledků, kde máme na prvním místě menu s ovládacími prvky, facety atd., tj. než doroluji k výsledkům, hrozně to trvá:
![image](https://github.com/user-attachments/assets/3d008de2-6783-4306-8287-46d623c50bc1)

Rychlým řešením by bylo zobrazit Typy záznamů a Filtrace automaticky zabalené + doplnit možnost zbalit všechny Facety jako celek. Nejlepší by ale bylo, pokud by menu mělo nějakou ikonu, která by jej jako plovoucí vysunula kdykoli z boku jako overlay přes výsledky. To by zajistilo, že kdykoli mohu mezi obojím přecházet a nemusím rolovat jak zběsilý.

**Comment by pkudela** [comment]
Ahoj @motyc  po precteni me napadlo, jestli to neudelat tak, jako jsem to kdysi udelal u mobilniho zobrazeni krameria? Cili defaultne pri nejakem rozliseni, ktere si rekneme se nahore objevi ovladaci lista s ikonou filtru, defaultne jsou zobrazeny vyznamove dulezitejsi vysledky, ale kliknutim na ikonu si zobrazis filtry a po zvoleni filtru Te to hodi zase na vysledky s aplikovanym filtrem viz. screenshoty nize. Chovani si muzes vyzkouset napr. zde -> https://kramerius.knihovna-pardubice.cz/search?access=open

Musim ale nejdrive prozkoumat kod, jestli to pujde, uz nevim jak je nastaveny layout, pro ted je to jen napad / navrh, jak to vyresit.

![Image](https://github.com/user-attachments/assets/03da3c9b-cdec-4482-99ef-f85fd1dee47e)

![Image](https://github.com/user-attachments/assets/13a7c0ed-9932-4358-b3a4-4c722e5208d2)

**Comment by motyc** [comment]
@pkudela Ahoj, jo, to je přesně to řešení, které bych si představoval jako ideální :)

**Comment by motyc** [comment]
Ano, přesně tak, můžeš.

**Comment by pkudela** [comment]
@motyc ten prvni bod bude docela kompikovany, ty hlavni karty se generuji v cyklu, ty spodni jsou staticke, cili budu muset nejak vymyslet kombinaci poradi v cyklu a konkretniho breakpointu. Nyni jsou tam 4 stavy:

- zakladni - defaultni zobrazeni vsech karet na jednom radku
- bp - 959px - zobrazuji se 3 karty na radek
- bp - 599px - zobrazuji se 2 karty na radek
- bp - nizsi - zobrazuje se 1 karta na radek

Muj dotaz zni, chces to chovani aby se zobrazovaly ty doplnkove karty pod tou hlavni pro vsechny 3 mobilni zobrazeni, nebo staci jen pro to nejnizsi, cili 1 karta na radek?

**Comment by motyc** [comment]
@pkudela Zkoušel jsem si to simulovat a přišlo by mi nejlepší, kdyby vždy byly hned pod tou kartou, tj. jakmile je více než jeden řádek karet, aby se rozbalily mezi prvním a druhým řádkem.

**Comment by pkudela** [comment]
> @pkudela Zkoušel jsem si to simulovat a přišlo by mi nejlepší, kdyby vždy byly hned pod tou kartou, tj. jakmile je více než jeden řádek karet, aby se rozbalily mezi prvním a druhým řádkem.

sem si to myslel :-) uz to testuju, je to kvui tomu cyklu pakarna, ale pujde to, teda doufam

**Comment by pkudela** [comment]
Ahoj @motyc tak ta prvni vec je odladena, doufam, ale malem u toho zarval stul :-) Mrkni, otestuj a dej vedet.

**Comment by motyc** [comment]
Ahoj, je to bez závad :) Moc děkuju. Všiml jsem si u toho jen jedné věci - je tam hranice, kdy nám ikona překrývá nápis:
![image](https://github.com/user-attachments/assets/03795e79-e432-4eac-a072-722faf06c0f7)
Asi by stačilo posunout hranici přepnutí na dvouřádkové zobrazení tak, aby se to nemohlo stát...

**Comment by pkudela** [comment]
Ahoj, uplne si nejsem jist, to by se na to dvouradkove zobrazeni prepnulo zbytecne brzo, spis bych to resil tak, aby se pocet zaznamu zalomil o malinko drive.

Takto je to nyni:
<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/7f1c256d-62de-480f-bc8e-6d9e5d930775" />

A pri stejnem breakpointu by se to chovalo takto do chvile, nez se to prepne na dvouradkove zobrazeni:
<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/d655c1f4-68a4-40c8-a5f9-db5c794e4bcd" />

Souhlas?

**Comment by motyc** [comment]
@pkudela Ta prostřední varianta mi přijde bezva:
<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/d655c1f4-68a4-40c8-a5f9-db5c794e4bcd" />

**Comment by pkudela** [comment]
> [@pkudela](https://github.com/pkudela) Ta prostřední varianta mi přijde bezva: <img alt="Image" width="1030" src="https://private-user-images.githubusercontent.com/16591052/396186885-d655c1f4-68a4-40c8-a5f9-db5c794e4bcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjgyNzAsIm5iZiI6MTczNDM2Nzk3MCwicGF0aCI6Ii8xNjU5MTA1Mi8zOTYxODY4ODUtZDY1NWMxZjQtNjhhNC00MGM4LWE1ZjktZGI1Yzc5NGU0YmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDE2NTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MjZiNmNhMDJlZGE0NzNjM2IwNjczZWFjOTY4ZTRiYWQ5YzgxYWNkODI4ZWQyZWNhMGFiOTJhNDQ1YjU2ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.014AX9kUIHi-1OdnQ3lEso1uqJMB_2A5gScLW17Ri-Y">

ok, udelam a dam k testovani

**Comment by pkudela** [comment]
Hotovo, nasazeno, prosim otestuj a a dej vedet. 

Jeste jsem tam fixnul jednu vec, ktera me iritovala. Pokud mas mensi breakpoint nez je 600px, tak se vyska karty o trochu zmensi a paticka karty, kde je pocet dokumentu a pripadne button je nalepena na dolni okraj karty viz. screenshoty nize. Cili jsem nastavil minimalni vysku karty a uz by to melo byt v poradku, vyska karty je vzdy stejna.

Pred opravou:
<img width="622" alt="Image" src="https://github.com/user-attachments/assets/400abf5f-de30-4e99-a648-6d6b0d302b52" />

Po oprave:
<img width="629" alt="Image" src="https://github.com/user-attachments/assets/2b49679a-1918-4969-aa2f-de89664a0213" />

**Comment by motyc** [comment]
Perfekt, otestováno, zavírám.

**Comment by motyc** [comment]
@pkudela Chová se to perfektně a takto jsem si to představoval. Narazil jsem na jediný detail, a to že když z facet vyberu nějaký filtr, tak se po zavření filtru (resp. jeho aplikaci) seznam výsledků neposune nahoru, ale zůstane na pozici, kde byl ten vybraný filtr, což trošku mate. Mělo by se to asi posunout při té aplikaci nového filtru vždy na začátek seznamu výsledků.

**Comment by albertoh** [comment]
Scroll fixnut

**Comment by pkudela** [comment]
> Scroll fixnut

Ano, testoval jsem to ted i na mobilu na lokalni IP a funguje to perfektne, diky @albertoh! @motyc prosim otestuj a pripadne zavri.

**Comment by motyc** [comment]
Hoši jsem starej prudič a ještě jsem našel jednu situaci, kdy to není ošetřené, a to když se použije rychlý filtr přímo ze záznamu. Tam se to ale netýká jen mobilní verze, ale i klasického zobrazení.

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Bez problémů, zavírám.
