### ISSUE TITLE
Problém s načítáním většího počtu souvisejících záznamů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#197]
Pokud je souvisejících záznamů příliš mnoho, aplikace zamrzá po otevření detailu (https://digiarchiv.aiscr.cz/results?q=C-201805538A&page=0&entity=akce&sort=datestamp%20desc), nebo vrátí error 502 (https://digiarchiv.aiscr.cz/id/C-201805538A?lang=cs). Bude asi třeba řešit asynchronním načítáním souvisejících dat, nebo listováním. Nyní to každopádně vede k chybovému chování...

Problém chápu jako nutnou optimalizaci, která jde nad rámec správy systému. Prosím o odhad hodin a objednáme to jako drobný rozvoj.

**Comment by albertoh** [comment]
Ja bych jeste v ramci toho vylepsil zobrazovani katastru pro dokumenty, kdyz tech akci je hodne. Na priklad:
https://digiarchiv.aiscr.cz/results?lang=cs&q=C-9137312A&page=0

Zobrazil bych jen unikatni, neopakujici katastr (okres).

**Comment by motyc** [comment]
@albertoh To by bylo super - rozhodně souhlas, díky!

**Comment by motyc** [comment]
@albertoh Ano, jen by možná šlo při nějakém vyšším počtu (nevím od kolika to začíná být problém) zobrazit upozornění, že načtení může trvat déle? Jde o to, aby to nepůsobilo "zasekle".

**Comment by albertoh** [comment]
Pracuju na tom. Nejaky zpusob aby to zamrzlo, nejak dat info o nacitani, a zaroven pripravit na tisk.
Prodlouzi se mi toto issue :) Je tech zakrytych problem vic. Ale uz jsem na spravne ceste

**Comment by motyc** [comment]
@albertoh V pořádku, rozumím.

**Comment by albertoh** [comment]
Pri hledani:
https://digiarchiv-test.aiscr.cz/results?q=C-201805538A&page=0&entity=akce&sort=datestamp%20desc

Persistentni link:
https://digiarchiv-test.aiscr.cz/id/C-201805538A?lang=cs

Katastry jen neopakujici:
https://digiarchiv-test.aiscr.cz/results?q=C-9137312A&page=0

**Comment by albertoh** [comment]
Problem s katastry opraven.

Procent jsem pridal i na results

S tiskem moc nemuzu delat. Je to interni renderovani prohlizece. Pridal jsem napis "printing" (potom muzeme prekladat), aby bylo jasne co se deje.

Nahledy vidim vsechny (myslim nenahled :) )

**Comment by albertoh** [comment]
Beha rychleji, proto ze jsem udelam dalsi optimizace :)

**Comment by motyc** [comment]
Šikovný :)

**Comment by motyc** [comment]
- [ ] Funguje to dobře s jedinou výjimkou - při tisku https://digiarchiv.aiscr.cz/print/C-201805538A?lang=cs mi to vygenerovalo PDF, ve kterém ale nejsou všechny náhledy - od C-201805538A-DT-120 dále náhledy chybí (viz https://filesender.cesnet.cz/?s=download&token=36298ab0-8223-4d79-b970-ea94fa63e79b)
- [ ] Také jsem si všiml, že se ty související záznamy vypisují nějak napřeskáčku, šlo by je prosím ještě řadit abecedně podle ident_cely?

**Comment by motyc** [comment]
Ještě doplňuji, že to chování je pokaždé jiné - teď se mi třeba zobrazil v tisku jen jeden náhled (u téhož záznamu)...

**Comment by albertoh** [comment]
Problem je v tom, ze nez se nacitaji obrazky, prohlizec uz dava stranku do tisku, a tim padem, nema vsechny obrazky. Pokazde jinak, podle taho jak rychle se dani obrazek v danni okamzik natahuje. A navic prohlizec obrazky nejak cachuje.

Zkusim neco vymyslet

**Comment by motyc** [comment]
@albertoh Narazil jsem ještě na chybu:

- [ ] když otevřu záznam dokumentu (např. https://digiarchiv.aiscr.cz/id/C-TX-202200346), kde je archivovaný dokument, ale odkazovaný záznam (akce) není k dispozici (obvykle ještě nebyl archivován), tak se zobrazení landing page/detailu záznamu zacyklí a zdánlivě se stále načítá.

**Comment by albertoh** [comment]
Vidim ten problem. Nevim ale jak by se mel spravne chovat. Zobrazit bez odkazovanou akci? To ale stejne bude delat problemy (nejasnosti) pri zobrazovani zaznamu, protoze katastr se bere z te akce...

**Comment by motyc** [comment]
@albertoh Ano, zobrazit bez té akce a klidně i bez katastru (je to prostě tak, jako by ta akce v systému vůbec nebyla).

**Comment by albertoh** [comment]
Abych zobrazil bez katastru musim menit indexer: ten dokument ma vazbu na akce primo v OAI record.
Odstranit problem s "loading bar" muzu primo menit chovani v UI.

Trochu mi mate skutecnost, ze ten zaznam ma vazbu, ikdyz neni jeste hotove...

**Comment by albertoh** [comment]
Spravne bude odstranit pri indexaci. Jinak prijdou do UI "nevalidni" data

**Comment by motyc** [comment]
@albertoh Ono to tak bylo i dříve, jen se s tím Digiarchiv dokázal poprat (nevím proč). K tomu zmatení - ona ta vazba skutečně existuje, ale pravidla indexace stanovená při vývoji říkají, že nepracujeme s nearchivovanými záznamy. Při jiných užitích mimo Digiarchiv to ale relevantní být může. Nejde tak o chybu dat, jen o jejich správnou interpretaci.

Za mne jde v důsledku jen o to odstranění problému s "loading bar". Pokud tam katastr zůstane, nevadí to. Ale rozhodnutí o nejlepším řešení nechám na tobě (ať s tím neztrácíš příliš času).

**Comment by albertoh** [comment]
Kdyz odstranim loading bar jenom, stejne bude dole misto pro "souvejci zaznamy" ale prazdny. Muzu ho potom schovat, ale take to bude divne, ze nazactku je, a najednou zmizi.
Pracuju na indexer. Dneska bude na testu, spolu s tim problemem s tiskem

**Comment by albertoh** [comment]
Je to na produkci. Reindexuje

**Comment by motyc** [comment]
Zkouším to ještě na produkci a je tam drobný bug - když zadám https://digiarchiv.aiscr.cz/id/C-201805538A?lang=cs, tak to z nějakého důvodu na zobrazuje "loading images", i když vše funguje a stránka normálně běží. Ve skutečnosti se to ale zasekne na jednom procentu a procenta začnou naskakovat tak, jak hýbu scrollem skrz související záznamy:
![image](https://user-images.githubusercontent.com/20186892/187850769-feab45d8-cf04-4070-af4d-847a53742d05.png)

Pro https://digiarchiv.aiscr.cz/print/C-201805538A?lang=cs to funguje v pořádku.

**Comment by albertoh** [comment]
Opraveno na testu

**Comment by motyc** [comment]
Původní problém odstraněn, ale zdá se mi, že je tam ještě jedna věc. Když se podívám na https://digiarchiv-test.aiscr.cz/results?lang=cs&q=C-201805538A&page=0&entity=akce&sort=ident_cely%20desc, tak mi to dává správně jednu akci a 882 dokumentů. Stejně tak je u akce C-201805538A uveden počet 882 dokumentů. Problém ale je, že mezi dokumenty v souvisejících záznamech myslím nejméně jeden chybí, a to C-TX-202000445. Seznam končí už u ID C-201805538A-DT-879:
![image](https://user-images.githubusercontent.com/20186892/187872168-0453c93d-d5e1-4801-a777-f397d3723456.png)

Když přejdu na https://digiarchiv-test.aiscr.cz/id/C-201805538A?lang=cs tak dokonce začíná až od ID C-201805538A-DT-020 a končí ještě dříve:
![image](https://user-images.githubusercontent.com/20186892/187872687-24cbd3df-d952-45e7-b91c-84f3427c0a90.png)

Při tisku je to taky špatně, jen opět jinak (končí u C-201805538A-DT-799)

**Comment by albertoh** [comment]
Vsechno je tam. Problem je v usporadani. Zaznamy se pridavaji asynchrone, kvuli performance, a jsou "nahodne" serazene.
Treba ted vidim "C-TX-202000445" na 20. pozici. Ale muze to byt jinak pri dalsim cteni.

Muzu se pokusit jeste seradit jak to vraci API, ale zase bude trochu klesat rychlost. Zkusim

**Comment by albertoh** [comment]
Jde to na test

**Comment by motyc** [comment]
Funguje to perfektně, lze dát na produkci. Moc děkuji!

**Comment by albertoh** [comment]
Je to tam

**Comment by motyc** [comment]
Hotovo, zavírám
