### ISSUE TITLE
Chyby persistentních landing page

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#198]
- [x] Pro komponentu 3D modelu chybí související záznam (https://digiarchiv.aiscr.cz/id/C-3D-202100067-K01?lang=cs)
![image](https://user-images.githubusercontent.com/20186892/170324931-e82fbd95-b095-4ebe-8408-b969d3bea2d3.png)

- [x] Pro obsahovou část chybí podřazené komponenty (https://digiarchiv.aiscr.cz/id/C-3D-202100067-D01?lang=cs; https://digiarchiv.aiscr.cz/id/M-LN-000002460-D01?lang=cs)
![image](https://user-images.githubusercontent.com/20186892/170325448-19120633-44c2-4bae-87a2-b5a9976108ce.png)

**Comment by motyc** [comment]
@albertoh Prosím jen nezapomenout zvednout verzi na 2.1.2

**Comment by motyc** [comment]
@albertoh Na produkci je nějaká chyba v kódu, kvůli které se na stránkách záznamů zobrazuje v záhlaví toto a je špatně ikona:
![image](https://user-images.githubusercontent.com/20186892/181468923-f88391f0-47de-40cf-bdfe-9f1c83c3c8e5.png)

Zajímavé je, že na testu se to neděje, jak je to možné?

**Comment by motyc** [comment]
Někdy to úplně rozbije záznam:
![image](https://user-images.githubusercontent.com/20186892/181469736-93559fb2-90c5-44ad-9598-30917568d366.png)

**Comment by albertoh** [comment]
Spatne se restartoval service. Uz je to

**Comment by motyc** [comment]
Super, funguje, zavírám.
