### ISSUE TITLE
U dokumentu bez náhledu zobrazit místo náhledu ikonu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#199]
Cílem je, aby se šlo prokliknout do prohlížečky a dokument alespoň stáhnout, i když samotný náhled není k dispozici. Reaguje na problém se smazáním existujících náhledů v důsledku #4. Výhodné to však bude dlouhodobě.

Graficky řešit nějak takto:

![image](https://user-images.githubusercontent.com/20186892/170964099-f91890ee-58d8-44e4-b151-957df59c06bb.png)

![image](https://user-images.githubusercontent.com/20186892/170964360-a2767a27-481b-4bbe-840c-32ed8a695c18.png)

**Comment by albertoh** [comment]
Je to na testu. Ale tam download nefunguje spravne, protoze nemame skutecne soubory.

**Comment by motyc** [comment]
Funkčně ok, jen je to omezené na textové dokumenty. Dal bych to všude, kde se pracuje s náhledy souborů (foto, samostatné nálezy, 3D...).

**Comment by albertoh** [comment]
Je to pro vsechny
