### ISSUE TITLE
Indexer není zabezpečený

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#2]
Reindexovat nyní může kdokoli. Musí být spojeno s přihlášením administrátora, jako tomu bylo doposud (testováno na http://192.168.254.3:28080/amcr/api/index/translations)

**Comment by albertoh** [comment]
Opraveno.
Je to nastaveni v konfiguraci. Na tom testu jsem to zmenil naschval na "A", protoze jsem musel reindexovat casto.
Vychozi nastaveni je "E"

**Comment by motyc** [comment]
Aha, díky za vysvětlení. Pak úplně v pořádku.
