### ISSUE TITLE
Doplnění ikon z záznamům

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#20]
K záznamům by bylo vhodné na začátek dát odpovídající ikonu a celkově je opticky lépe vydělit z pozadí. Nyní mají tendenci záznamy opticky splývat, zvlášť při rozbaleném detailu. Navrhuji něco jako:

![image](https://user-images.githubusercontent.com/20186892/100124973-8fe67680-2e7c-11eb-84d2-be62fc39d6d1.png)

**Comment by pkudela** [comment]
@albertoh prosim o nasazeni na server
