### ISSUE TITLE
Zamrznutí mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#200]
Při zadání https://digiarchiv.aiscr.cz/results?entity=akce&f_obdobi=en.kul:or&f_obdobi=en.riv:or&page=0&mapa=true mapa zamrzne při načítání.

Prosím o rychlou opravu, ve čtvrtek plánujeme Digiarchiv prezentovat.

**Comment by motyc** [comment]
@albertoh Mapa se chová celkově divně (výsledky se zobrazují jen někdy, celkově to zlobí).

**Comment by albertoh** [comment]
Je na testu. Stalo se to kvuli rychlosti ziskani dat. Nektere elementy jeste nebyly pripravene v ui, a nerenderovalo.
Zmenil jsem logiku nahravani komponentu (zpozdil jsem na zlomek vteriny)

**Comment by albertoh** [comment]
Muzu to na prod rovnou pokud souhlasis
