### ISSUE TITLE
Indexace nepotvrzených PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#203]
Ve specifických případech se indexují i nepotvrzené PIAN - lze rozpoznat podle "N" v identifikátoru (např. https://digiarchiv.aiscr.cz/id/N-1223-330566). Jde o situace, kdy je rozpracovaná akce připojena k již archivovanému dokumentů. PIAN se asi v takovém případě načte, i když by se to stát nemělo. Nepotvrzené PIAN neindexovat.

**Comment by albertoh** [comment]
Je nutne reindexovat PIAN. Na testu je.
