### ISSUE TITLE
Alert, confirm a prompt budou deprecated v Chrome

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#205]
Chrom již nebude podporovat některé funkce, které pravděpodobně používáme pro zobrazování oznámení uživatelům. Více viz: https://developer.chrome.com/blog/deps-rems-91/

Jako možný workaround jsem našel toto: https://stackoverflow.com/questions/68492434/javascript-dialogs-alert-confirm-and-prompt-in-cross-origin-iframe-does-n

Je třeba navrhnout a implementovat řešení.

**Comment by albertoh** [comment]
To se tyka jenom v iframe. To nemame

**Comment by motyc** [comment]
Super, pak tedy zavírám.
