### ISSUE TITLE
Chybějící náhledy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#206]
Po smazání náhledů řady dokumentů v souvislosti s bugem u #4 stále chybí několik nedogenerovaných náhledů a není úplně jasné, čím to je. Jde např. o:
https://digiarchiv.aiscr.cz/id/C-202111632-N00050
https://digiarchiv.aiscr.cz/id/C-202109132-N00050
https://digiarchiv.aiscr.cz/id/C-202109175-N00050
https://digiarchiv.aiscr.cz/id/M-202104086-N00031
https://digiarchiv.aiscr.cz/id/M-202101534-N00357
https://digiarchiv.aiscr.cz/id/M-202101534-N00061
https://digiarchiv.aiscr.cz/id/C-201805538A-DT-024
(atd.)

Prosím o zjištění, proč se náhledy nevyrobí a případné řešení.

**Comment by albertoh** [comment]
Pustil jsem generovani nahledu na uvedene pripady, a probehlo to bez chyb.

Nemuzu ale najit log starych procesu, abych zjistil, co se stalo. Prosim, @MichalKminek, kde jsou logy? Jak je konfigurovan cron?

**Comment by motyc** [comment]
@albertoh
Ono je hlavně divné, že to přeskakuje tak nějak náhodně jen některé soubory.

Ty logy také nevidím a přijde mi divné, že by se mazaly. Spíš ty soubory vůbec nevznikají.

@MichalKminek je bohužel tento týden na dovolené, tak asi nebude úplně reagovat.

**Comment by motyc** [comment]
Kdyby to tak bylo, neměly by se ale v takovém případě díry doplnit při dalším běhu generování?

**Comment by MichalKminek** [comment]
Spouštěcí skript /opt/scripts/remove_deleted.sh svůj výstup ukládá do /var/log/indexace/remove_deleted.log zde jsou případně vidět chyby aplikace.
Uvnitř skriptu je vidět jak se aplikace spouští, nebudu to tady uvádět.
Po spuštění vzniká soubor txt se jménem obsahujícím datum běhu - /var/lib/digiarchiv/thumbs/toberemoved.20220716.txt, obsahuje seznam souborů ke smazání. Tyto txt soubory zůstávají v adresáři /var/lib/digiarchiv/thumbs. Zmíněný runner se nevyužívá.

**Comment by albertoh** [comment]
Potreboval bych ten normalni skript, ne na mazani ale na generovani :)

**Comment by albertoh** [comment]
Dik, podivam se

**Comment by albertoh** [comment]
Vypada to tak, ze nektere slozky v /var/lib/digiarchiv/thumbs/ maji jako vlastnik root. 
Potom ten proces, ktery bezi pod uzivatelem tomcat, nema prava zapisu. A proto, negeruje nahledy.

Kdyz ja to pustim rucne, bezi jako root, a ten ma prava.

Z toho plyne, ze nesmim poustet rucne ten proces jako root.

Meli bychom zmenit hromadne prava vsech souboru a slozek tam, aby patrili tomcatu

**Comment by MichalKminek** [comment]
Je to tak. Nastavil jsem vsude vlastnika tomcat. Thumbs generator musi bezet vzdy pod uzivatelem tomcat, jinak vytvari struktury podle aktualniho uzivatele, napr. roota. Slo o slozku F7 ze 16 May 30 23:40.

**Comment by motyc** [comment]
@albertoh Tím je to tedy asi vyřešené, jen na to prosím do budoucna dávejme pozor. Máš možnost to generování ručně spouštět i pod tomcat, nebo k tomu ještě něco potřebuješ od nás?

**Comment by albertoh** [comment]
Nepotrebuju, mam moznost. Dam si pozor :)
