### ISSUE TITLE
Vyhledávání podle ident_cely

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#207]
Systém z nějakého důvodu fulltextově nevyhledává podle ident_cely u některých projektů a samostatných nálezů. Jde např. o:
https://digiarchiv.aiscr.cz/results?entity=samostatny_nalez&q=C-202204925-N00030&page=0
https://digiarchiv.aiscr.cz/results?entity=projekt&q=C-202204925&page=0

Oboje přitom v systému existuje:
https://digiarchiv.aiscr.cz/id/C-202204925-N00030
https://digiarchiv.aiscr.cz/id/C-202204925

Dotazy na jiné případy přitom fungují (u projektů):
https://digiarchiv.aiscr.cz/results?entity=projekt&q=C-202008162&page=0

Prověřit, zda se něco podobného neděje i pro jiná pole/typy záznamů.

**Comment by motyc** [comment]
Předpokládám, že toto je nasazeno i na produkci, kde to najednou funguje v pořádku?

**Comment by albertoh** [comment]
Neni uplne :) Kdyz jsem nasadil jine zmeny na produkci, tohle jsem mel opraveno pro projekt a samostatne nalezy. Ale potom jsem upravil i jine entity (lokalita), ktere take mely problemy.
 Na testu je vsechno.

**Comment by motyc** [comment]
Ok. Já jen vůbec nevím, jak to otestovat jinak, než na těch konkrétních a u nich to funguje. Tak snad to bude ok :)
