### ISSUE TITLE
Titulní strana - celé boxy aktivní proklik

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#21]
Na titulní straně by bylo vhodnější, aby na proklik reagovaly celé barevné boxy, nikoli jen popisky v nich (případně alespoň celá část nad počtem záznamů, pokud by byla problém kolize s rozbalovacím menu u dokumentů).

**Comment by pkudela** [comment]
hotovo, po dohode jsem routerLink presunul z elementu a na element mat-card-header vcetne query parametrs

**Comment by pkudela** [comment]
@albertoh prosim o nasazeni
