### ISSUE TITLE
Skrytí facety f_kulturni_pamatka

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#210]
Prosím v rámci nadcházejících oprav o skrytí facety `f_kulturni_pamatka`. Hodnoty jsou pro uživatele spíše zavádějící a nemá smysl s ní pracovat. V detailu záznamu jsme to již skryli dříve.

**Comment by motyc** [comment]
@albertoh Vidím správně, že je to i na produkci? A jak je to udělané, když k tomu nevidím žádný commit?

**Comment by albertoh** [comment]
Projevilo se to na produkci, protoze to bylo opraveno driv, v ramci jineho issue (#194) s commitem (https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commit/2cd96b489b3308de7eaaab11abe6b497a2f75fec). Tady zmena byla v konfigurace solru

**Comment by motyc** [comment]
Aha, já právě myslel, že to už šlo na produkci dříve a myslel jsem, že to nefungovalo (proto jsem dělal toto issue). Tím je to jasné :)
