### ISSUE TITLE
Nasazování nových config souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#215]
V repozitáři jsem během posledních měsíců aktualizoval config soubory:
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/main/web/src/main/ng/src/assets/config.json
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/main/web/src/main/resources/cz/inovatika/arup/digiarchiv/web/server_config.json

Je mi ale divné, že se změny v při deploymentu nepropsaly na servery. Je mi jasné, že to jde řešit zápisem do `var/lib/digiarchiv/config.json`, cílem ale bylo soubory zbavit nadbytečných údajů a přenést "neměnná" nastavení do výchozích configů. Jak to s konfigurací funguje, je nějaký důvod, proč se při nasazení konfigurační soubory neaktualizují? (zdůrazňuji, že nemyslím ten uživatelský `var/lib/digiarchiv/config.json`, ale ty výchozí).

**Comment by albertoh** [comment]
Tyto soubory jsou vychozi konfiguraci aplikace. Zmeny v nich se budou promitat jen kdyz v konfiguracni adresari nebudou prepsane.
 Tj, pokud neco zmenime ve vychozim souboru, ale v /var/lib/digiarchiv/config.json ten klic existuje, ma prednost.
 Pokud neexistuje, zmeny plati.
 Konfiguraci ne nacita pri startu aplikace. Pokud zmenime neco pri bezicim tomcatu, aby zmeny se projevily je nutne reloadnout konfiguraci. Lze to delat dvema zpusoby:
  - restartem aplikace (treba touch web.xml)
  - volanim  https://digiarchiv.aiscr.cz/config?reset=true

**Comment by motyc** [comment]
Tomu všemu rozumím, ale nevím, proč ta výchozí konfigurace skutečně nasazená na serveru (dívám se na `192.168.254.25/usr/share/apache-tomcat-9.0.40/webapps/amcr/assets/config.json`) neodpovídá tomu, co je nyní v souborech na GitHub...? Tím pádem když odeberu některé klíče z `192.168.254.25/var/lib/digiarchiv/config.json`, protože by měly být ve výchozím stavu správně, tak je nastavení špatné (neodpovídá GitHub). Totéž myslím platí na produkci.

Možná se dívám na špatné místo, ale každopádně chování je takové, jaké popisuji (lze testovat např odstraněním
```
"choiceApi": [
    {"label": "AMČR", "metadataPrefix": "oai_amcr"}
  ],
```
z `192.168.254.25/var/lib/digiarchiv/config.json`

Pokud by to fungovalo dobře, nic by se nemělo změnit, nyní se ale menu odkazů změní do stavu podle `192.168.254.25/usr/share/apache-tomcat-9.0.40/webapps/amcr/assets/config.json`.

**Comment by albertoh** [comment]
Na testu byl spatne zkopirovan soubor v assets

**Comment by motyc** [comment]
V pořádku, zavírám :)
