### ISSUE TITLE
Chyba zabezpečení katastrů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#216]
Pravděpodobně po poslední opravě došlo k tomu, že se katastry propisují k dokumentům i v případě, kdy nemají být viditelné na základě přístupnosti. Např. zde: https://digiarchiv.aiscr.cz/id/C-DL-200800010

Prosím o rychlou opravu.

**Comment by albertoh** [comment]
Je to na testu. Ale je nutne reindexovat.

**Comment by motyc** [comment]
Reindexuji na testu a potvrdím. Jen prosím o změnu verze na 2.1.3

**Comment by motyc** [comment]
Zkusil jsem na testu a i po reindexu se nic nezměnilo (viz https://digiarchiv-test.aiscr.cz/id/C-DL-200800010).

**Comment by albertoh** [comment]
reindexovano. verze zmenena

**Comment by motyc** [comment]
@albertoh Jak jsem psal výše, vypadá to stále stejně. Nevím ale, jestli jsme se nějak nepotkali s tím reindexem. Myslel jsem, že to mám spustit já...

**Comment by albertoh** [comment]
Koukni ted. Restartoval jsem nodejs

**Comment by motyc** [comment]
Koukám na to a uvedený příklad už je ok. Jen mám pocit, že se to celé nějak trošku pomotalo.

- Není viditelný katastr zde u projektu: https://digiarchiv-test.aiscr.cz/id/C-201772807A (viz související záznamy), přestože by měl být viditelný a po rozkliknutí projektu přímo (https://digiarchiv-test.aiscr.cz/id/C-201772807) viditelný je.
- U tohoto projektu naopak viditelný být nemá, ale je: https://digiarchiv-test.aiscr.cz/id/C-202111632 (platí jen na testu)
- Zde se zase katastr do hlavičky vůbec nevypíše, i když je v neident. akci (viz detail dokumentu); filtrace však funguje dobře: https://digiarchiv-test.aiscr.cz/id/C-TX-194802620
- V sam. nálezech (podobně i v lokalitách a akcích) jde filtrovat i podle skrytých (!) katastrů: https://digiarchiv-test.aiscr.cz/results?entity=samostatny_nalez&page=0&sort=datestamp%20desc&f_katastr=MIKULOV%20NA%20MORAV%C4%9A:or (platí jen na testu)

Mám-li rekapitulovat související pravidla:
- pro akce, lokality a sam. nálezy se katastr vypisuje jen při dostatečném oprávnění
- pro dokumenty se vždy vypisuje katastr z neident. akce + katastry ze souvisejících akcí/lokalit, pokud jsou tyto přístupné (mám oprávnění je vidět)
- pro projekty se katastr vypisuje, pokud jsou mezi potomky přístupné záznamy (mám oprávnění je vidět)
- pro filtraci platí vše jako pro výpis

**Comment by albertoh** [comment]
Rekapitulace... :)

Uvedene problemy videl jsem i na produkci. Tj, nebyly zanesene vcerejsimi opravami, ale s tou velkou zmenou (pokud byly nekde uplne v poradku)
 

- https://digiarchiv-test.aiscr.cz/id/C-201772807A : opraveno
- https://digiarchiv-test.aiscr.cz/id/C-202111632 : je videt okres, ne katastr. Tady jsem nasel jinou chybou. V projektu je vice vazeb na samostatne akci nez mame v indexu. To zpusobilo, ze se ukazovalo "loading" porad. Opravil jsem to. Akorat nerozumim, proc pises "(platí jen na testu)". I na produkci je spatne.
- https://digiarchiv-test.aiscr.cz/id/C-TX-194802620 : Opraveno 
- V sam. nálezech (podobně i v lokalitách a akcích) jde filtrovat i podle skrytých (!) katastrů : Tomu nerozumim. Prece vysledek je nula nalezu.

**Comment by albertoh** [comment]
Jeste reindexuje, az zkonci dam label

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Je to ok, kromě toho abecedního řazení. Je divné, že s každým refreshem okna se to vypíše jinak (https://digiarchiv-test.aiscr.cz/id/C-202111632?lang=cs).

Tady je to přitom po otevření detailu dobře vždycky: https://digiarchiv-test.aiscr.cz/results?entity=projekt&q=C-202111632&page=0

**Comment by albertoh** [comment]
Razeni opraveno

**Comment by motyc** [comment]
Je to super, potvrzuji a lze to celé nasadit na produkci. Díky moc.

**Comment by albertoh** [comment]
Je to tam. Ale musi se reindexovat. Nevim jestli ted je vhodna chvile. Necham to na tobe :)

**Comment by motyc** [comment]
Asi to nechám reindexovat normálně přes noc, ať z toho lidi nejsou zmatení :) Bude třeba i restartovat i ten nodejs, nebo to už se stalo?

**Comment by albertoh** [comment]
to jsem udelal
ale reindex je nutny ted
udelam to postupne, at nemazeme zaznamy
