### ISSUE TITLE
U samostatných nálezů chybí poznámka a hloubka

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#217]
Z nějakého důvodu se nevypisují pole `poznamka` a `hloubka` u samostatných nálezů.
Viz https://digiarchiv.aiscr.cz/id/C-202111632-N00192?lang=cs + https://docs.google.com/document/d/15bllyvwT-qX6gYm4-KszoiWC3meL_C2V/edit

![image](https://user-images.githubusercontent.com/20186892/199467675-3d5730f5-78d3-4ef4-8522-35d9545554a6.png)

Prosím o vyřešení též pro v2.1.3

**Comment by albertoh** [comment]
Hloubka se nezobrazovala pokud byla 0. Javascript je vtipny...
Poznamka tam vubec nebyla od zacatku.

**Comment by motyc** [comment]
Potvrzuji, díky
