### ISSUE TITLE
Nejde otevřít Knihovna 3D

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#22]
Nenačte se

**Comment by albertoh** [comment]
Co presne nejde otevrit? Ja to vidim, jak vysledky tak persistetni link

**Comment by motyc** [comment]
Tak jsem to také zkoušel a ukázalo se, že to nefunguje jen tehdy, když jsem přihlášený.

**Comment by albertoh** [comment]
Opraveno
