### ISSUE TITLE
Chyba zobrazení roku u dokumentu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#221]
Dokument https://digiarchiv.aiscr.cz/id/C-201017191B-DT-0979?lang=cs nemá vyplněný rok (to si vyřešíme v datech). Na persistentním odkazu se to zobrazuje s nulou, což je logické:
![image](https://user-images.githubusercontent.com/20186892/205906395-dfbb96cd-9c43-4871-bafc-d28b26329726.png)

Při vyhledání přes https://digiarchiv.aiscr.cz/results?entity=dokument&sort=rok_vzniku%20asc&page=0 se ale zobrazuje "2000":
![image](https://user-images.githubusercontent.com/20186892/205906538-3054f67d-aaff-4e71-bcae-c7100764e08e.png)

**Comment by albertoh** [comment]
To asi jste vyresili problem v datech, jo? Ted nemuzu reprodukovat problem...

**Comment by motyc** [comment]
Ano, v datech jsme to už opravili, pardon :( V API se to projevovalo tak, že element s rokem úplně chyběl, tak si to můžeš nasimulovat nějak podle toho.

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Toto asi neotestuji, tak to nasaďme a uvidíme...
