### ISSUE TITLE
V mapovém zobrazení se nezobrazují související záznamy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#226]
Zde chybí akce: https://digiarchiv.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc&f_obdobi=no-in:or&f_obdobi=in.2:or&f_obdobi=in.1:or&f_obdobi=in:or&f_obdobi=no.2:or&f_obdobi=no.1:or&f_obdobi=novove:or&mapa=true&loc_rpt=49.54751852331313,12.280537239027739,49.79625532679884,13.245469050502921&pian_id=P-2121-000096

Zde je vidět: https://digiarchiv.aiscr.cz/id/C-TX-199401671?lang=cs

**Comment by albertoh** [comment]
Opraveno na testu

**Comment by motyc** [comment]
V pořádku
