### ISSUE TITLE
Nekonečné načítání stránky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#228]
Pokud otevřu záznam https://digiarchiv.aiscr.cz/id/M-TX-194800015, načítání nikdy nedoběhne (podobně při rozevření detailu ve výpisu dokumentů). Myslím, že to může být tím, že použita následující konstrukce s druhou vazbou, kterou jsme dosud moc nepoužívali:

![image](https://user-images.githubusercontent.com/20186892/214693361-c8d7ab52-765e-49cc-87ac-e938d17efba3.png)

**Comment by albertoh** [comment]
Problem je v tom, ze akce M-9112025A ma stav=1, a neni dohledatelna.
Nejsem si jist, jak tady postupovat

**Comment by motyc** [comment]
@albertoh To se může stávat celkem běžně. V podstatě je mi jedno, zda se akce úplně skryje a napojení nebude vidět, nebo tam bude vidět napojení, ale akce nepůjde rozkliknout. Je na Tobě, co je jednodušší. Měl jsem pocit, že to bylo ošetřené, ale asi to nějak ovlivnily změny v létě. Každopádně platí, že akce ve stavu 1 nejdou přes Digiarchiv otevřít (to je tedy v pořádku).

**Comment by albertoh** [comment]
Na testu

**Comment by motyc** [comment]
Lze nasadit.
