### ISSUE TITLE
Generování náhledů - přeskočené soubory

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#229]
Pro část nově přidaných PDF aplikace nevygeneruje náhledy. Jde např. o: 

https://digiarchiv.aiscr.cz/id/M-TX-195001154
https://digiarchiv.aiscr.cz/id/M-TX-195001131
https://digiarchiv.aiscr.cz/id/M-TX-195001132

Jsou zaznamenány i ve `var/lib/digiarchiv/thumbs/skipped.txt`, nicméně není jasné, proč náhled nevznikne. Nejde o nějaké obrovské soubory a nic speciálního na nic není.

Obecně by bylo fajn analyzovat důvody, proč jsou některé soubory přeskakovány a případně opravit generátor či jeho nastavení, aby co nejvíce náhledů vzniklo. Pokud je to o přidělených prostředcích pro službu, jde se zkusit domluvit na jejich navýšení.

**Comment by albertoh** [comment]
Maji velke obrazky (pixely). Error je takovy:
  WARNING: skipping page 0 in file 1674149572146_MTX195001154.pdf. Image size 2392.000000 x 3443.000000
Existuje v konfiguraci klic:
    "maxPixels": 5000000.
Napriklad, prvni pdf ma 2392 x 3443 = 8235656

Lokalne jsem zvetsil hodnotu klicu, a proslo

**Comment by motyc** [comment]
@albertoh Co znamená "lokálně" - pro daný server? Myslím, že tam byl problém v tom, že nám to v některých případech pak padalo. Jak jsme na tom nyní s využitím prostředků, nehrozí, že po navýšení zase začne služba padat?

**Comment by albertoh** [comment]
Lokalne znamena u mne na pocitaci :)
Ja bych zmenil ten parametr, a sledoval bych chovani. Jinak to nejde delat.

**Comment by motyc** [comment]
@albertoh Ok, tak to tak zkusme.
