### ISSUE TITLE
Oblíbené - doladění

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#23]
Pokud si otevřu nabídku oblíbené, tak u záznamů nesvítí tlačítko pro zařazení mezi oblíbené žlutě, přestože už tam všechny záznamy musí být zařazené. Pro odstranění ze seznamu je třeba nejdříve opět přidat a pak následně odebrat.

**Comment by albertoh** [comment]
Opraveno
