### ISSUE TITLE
Chybějící související záznamy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#232]
Narazil jsem na další problém se souvisejícími záznamy, kdy se nezobrazují pro PIAN (https://digiarchiv.aiscr.cz/id/P-1224-103353) a ADB (https://digiarchiv.aiscr.cz/id/ADB-PRAH71-7569).

**Comment by albertoh** [comment]
Chybi reindexaci. Uz to bezi

**Comment by motyc** [comment]
@albertoh Buď ještě nedoběhla (divil bych se), nebo to bohužel nepomohlo...

**Comment by albertoh** [comment]
Jeste bezi

**Comment by albertoh** [comment]
Potrebuju jeste restartovat tomcat (kvuli zmene v jar pro org,json). Ale lidi ted tam jsou. Pockam na vecer

**Comment by albertoh** [comment]
Restartovano. Vidim to dobre

**Comment by motyc** [comment]
V pořádku, zavírám.
