### ISSUE TITLE
Chyba zalamování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#235]
https://digiarchiv.aiscr.cz/id/M-202105745A?lang=cs

Tento záznam se zobrazuje správně pouze v Mozille, v Chrome a Edge nefunguje správně zalamování (srovnání níže).
![image](https://user-images.githubusercontent.com/20186892/224001533-d10eb6ed-72eb-497f-9b9e-5fe7ee0ce09d.png)

![image](https://user-images.githubusercontent.com/20186892/224001876-526bfe5d-254d-45d2-9644-ed117447d37e.png)

**Comment by pkudela** [comment]
hotovo, po nasazeni by to melo vypadat takto

<img width="1505" alt="image" src="https://github.com/ARUP-CAS/aiscr-digiarchiv-2/assets/16591052/76d00d41-3e08-4c30-9dc9-47849336a2e0">

**Comment by pkudela** [comment]
nasazeno na testu -> https://digiarchiv-test.aiscr.cz/id/M-202105745A?lang=cs prosim, zkontroluj a dej vedet, pak nasadime na produkci

**Comment by motyc** [comment]
@pkudela Rovněž v pořádku. Lze tedy nasadit, jen prosím nezapomenout změnit verzi releasu (v2.1.5) - na testu to není dobře.

**Comment by pkudela** [comment]
hotovo, nasazeno se spravnym cislem verze na test a produkci, prosim o kontrolu a pripadne zavreni

**Comment by motyc** [comment]
V pořádku, zavírám

**Comment by motyc** [comment]
@pkudela Nasazení ukázalo, že to není vyřešeno dobře. Nyní to někdy úplně zbytečně zalamuje po slovech. Např. zde: https://digiarchiv.aiscr.cz/id/C-9113414A

![image](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/assets/20186892/5d3e0321-ec79-44be-b95a-86c9dabfd946)

**Comment by pkudela** [comment]
tak snad to uz bude v poradku, testovano v chrome, ff, safari, safari (edge), prosim otestuj pro jistotu pod windows
https://digiarchiv-test.aiscr.cz/id/M-202105745A?lang=cs
https://digiarchiv-test.aiscr.cz/id/C-9113414A

<img width="1435" alt="image" src="https://github.com/ARUP-CAS/aiscr-digiarchiv-2/assets/16591052/c36f83dc-7bb4-4f3c-a990-7e61e0e05768">
<img width="823" alt="image" src="https://github.com/ARUP-CAS/aiscr-digiarchiv-2/assets/16591052/70936b9f-9e6a-4d1d-8187-6a84912cd123">

**Comment by motyc** [comment]
@pkudela Otestováno, ve všech variantách ok. Lze dát do produkce (prosím také o merge commitů sem na GitHub.

**Comment by pkudela** [comment]
Nasazeno na produkci, prosim o test. 

- https://digiarchiv.aiscr.cz/id/M-202105745A?lang=cs
- https://digiarchiv.aiscr.cz/id/C-9113414A

+ zkus prosim jeste otestovat jeste nejake jine podobne zaznamy kde tusis, takovy dlouhy retezec.

**Comment by motyc** [comment]
@pkudela Vypadá to v pořádku, děkuji.
