### ISSUE TITLE
Problémy s pozicováním tooltipu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#236]
Tooltip se nyní zobrazuje nikoli podle polohy myši, ale podle polohy prvku, ke kterému se vztahuje. Bylo by mnohem praktičtější, kdyby výchozí poloha tooltipu byla odvozována od polohy myši, a to tak že bude zobrazen vpravo dole vedle myši (staticky, nemusí se s ní pak hýbat). Jde o to, že nyní tooltip má tendenci překrývat jiné prvky (zejména ve facetách), takže musím čekat než zmizí, abych se mohl podávat či kliknut na další položku. Je potřeba, aby svislá i vodorovná osa byly pro pohyb myši a výběr přirozeně volné.

![image](https://user-images.githubusercontent.com/20186892/224002645-f6b4e629-52b5-489b-9d53-16e831d4a2ca.png)

**Comment by pkudela** [comment]
zmenu jsem provedl i u hlavniho facetu "Typ zaznamu"

<img width="636" alt="image" src="https://github.com/ARUP-CAS/aiscr-digiarchiv-2/assets/16591052/362b754c-dbea-4e49-a591-0fb0400319fb">

**Comment by pkudela** [comment]
nasazeno na testu -> https://digiarchiv-test.aiscr.cz/results?lang=cs&page=0 prosim zkontroluj a dej vedet, pak nasadime na produkci

**Comment by motyc** [comment]
@pkudela Ano, takto je to perfektní, díky.

**Comment by motyc** [comment]
V pořádku, zavírám

**Comment by motyc** [comment]
V pořádku, zavírám
