### ISSUE TITLE
Aktualizace indexeru pro webAMČR

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#238]
- [x] Na základě #237 bude třeba upravit indexer Digiarchivu. Změny jsou zřejmé z tohoto [changelogu](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/files/10974043/oai_amcr_230222_changelog_230314.xsd.zip) a případně též z dokumentu https://docs.google.com/document/d/1IQbFyAwEhTVEbnHRTL0nhyXNq0afs0vW/edit?usp=sharing&ouid=109460807413445640605&rtpof=true&sd=true
- [x] Do indexu doplnit i všechny nové elementy a atributy zachycené v [XSD](https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/xml_generator/definitions/amcr.xsd) (příklad odpovědi je [zde](https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/xml_generator/definitions/metadata.xml))
- [x] Indexace heslářů nově neprobíhá přímo z DB, ale rovněž z Fedory (set `heslo`); indexer to musí zohlednit. Odtud se nově berou i anglické překlady hesel.
- [x] Upravit je třeba i [ThumbnailsGenerator](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/tree/main/ThumbnailsGenerator), protože se pro něj změnil zdroj dat na Fedoru.
- [x] Detaily záznamů upravit podle https://docs.google.com/document/d/1IQbFyAwEhTVEbnHRTL0nhyXNq0afs0vW/edit?usp=sharing&ouid=109460807413445640605&rtpof=true&sd=true (viz sledování změn). Většina změn se týká pouze změny mapování, nicméně je tam pár přidaných položek, pokud přibyla metadata a změny podmínek pro indexaci k zobrazení.
- [x] Chráněné údaje jsou nově vždy označeny elementem `<amcr:chranene_udaje>`. Není tak již třeba skrývat celý detail, stačí chránit konkrétní obsažené údaje. Díky tomu není třeba blokovat ani rozbalování detailu záznamů v žádném z případů.
- [x] Element `{projekt/oznamovatel}` se indexuje pouze pro potřeby API, v zobrazení a vyhledávání v Digiarchivu nikdy nefiguruje a chová se jako skrytý.
- [x] Přidat facety pro `archeologicky_zaznam/lokalita/zachovalost` a `archeologicky_zaznam/lokalita/jistota`

Indexaci lze provádět po jednotlivých setech na základě volání: `https://fedora.aiscr.cz/rest/[server]/model/[set]`

Pro zrychlení lze denní indexaci též provádět na základě data poslední změny objektů v `https://fedora.aiscr.cz/rest/[server]/record/`, viz: https://wiki.lyrasis.org/display/FEDORA6x/Simple+Search (např.: `https://fedora.aiscr.cz/rest/fcr:search?condition=fedora_id%3DAMCR-test%2Frecord%2F*&condition=modified>%3D2023-12-15T00%3A00%3A00.000Z&offset=0&max_results=100`)

**Comment by albertoh** [comment]
Je upravený ThumbnailsGenerator?

 Jsou tam uz soubory na testovani? 
napr: rest/AMCR-test/record/C-202009779-N00006/file/127472e5-9675-4ca7-b2c2-700796f8ec76

**Comment by albertoh** [comment]
> Je úplně rozbitá stránka persistentního linku (nezobrazují se loga atd., nefunguje přihlášení…); zdá se také, že to vůbec nečte data z v3, ale odjinud (viz např. http://192.168.254.25:8080/v3/id/C-202210975?lang=cs)


Toto bude trochu krkolomny v soucasnem testovacim prostredi. Tyto stranky poskytuje nodejs (kvuli server side rendering).
Musim nejak to vymyslet, aby se to dalo namontovat tam...

**Comment by albertoh** [comment]
> Organizace - všude zobrazovat obsah pole organizace/nazev (resp. organizace/nazev_en pro angličtinu) z hesláře organizací; nyní se zobrazuje organizace/nazev_zkraceny

Zaznamy nemaji vyplneny pole nazev_en. To zpusobuje chybu. Zatim necham zkraceny, ten je

**Comment by motyc** [comment]
> > Je upravený ThumbnailsGenerator?
> 
> Jsou tam uz soubory na testovani? napr: rest/AMCR-test/record/C-202009779-N00006/file/127472e5-9675-4ca7-b2c2-700796f8ec76

Nyní jsou dostupné soubory k testování u těchto záznamů:
C-TX-202200694 (dokument)
M-TX-202200712 (dokument)
C-200913914A-DT-03473 (dokument)
C-DL-200800001 (dokument)
C-202109132-N00262 (nález)

3D zatím nemám, protože je aktuálně rozbitý interface AMČR a nemůžu tam soubor nahrát.

**Comment by albertoh** [comment]
ThumbnailsGenerator je upraven. Ale nevim jak ho dat na server, abychom mohli testovat. Je trochu komplikovane vedle soucasneho...

**Comment by motyc** [comment]
@albertoh Stačí mi vědět, že je to připraveno. Můžeme třeba po novém roce pomalu odstavit původní test, dát tam už novou verzi a vyzkoušet to na tom. Doladilo by se to případně poté.

**Comment by albertoh** [comment]
OK

**Comment by motyc** [comment]
### Testování 25. 11. 2023
Moc se omlouvám, že otestování tak trvalo, ale prioritu má AMČR jako taková a bohužel jsem se k tomu dříve nedostal kvůli času. Prošel jsem znovu jednotlivé části a vyplynulo následující:
- [ ] Chyby zobrazení opět zaneseny do (označeno červeně + komentáře): https://docs.google.com/document/d/1dCp9OAEiOq_3zmr-uLziC75eiDAWRDaa/edit (je to lepší, ale chyby stále zůstaly)
- [ ] `K zobrazení data poslední změny přidat tooltip, kde se zobrazí údaj vč. času + zohledňovat čas při řazení.` - toto funguje jen u dokumentů, jinde nikoli
- [ ] Nefuguje filtrace podle facet:
-- Nález - druh
-- Akce - typ
- [ ] Faceta "Dokument - autor" vypisuje ident_cely místo jmen, pokud mám přepnuto na entitu “Akce”

**Zmizely facety**
_Dokumenty_
- [ ] Nález - kategorie - řešit samostatně
- [ ] Akce - typ
- [ ] Dokument - typ posudku
- [ ] Dokument - formát (asi jen nejsou data)
- [ ] Dokument - zachovalost (asi jen nejsou data)
- [ ] PIAN - *

_Projekt_
- [ ] Komponenta - *
- [ ] Nález - *
- [ ] Akce - typ
- [ ] PIAN - *

_Akce_
- [ ] Akce/lokalita - typ dokumentační jednotky
- [ ] PIAN - *

_Lokality_
- [ ] Lokalita - druh
- [ ] Akce/lokalita - typ dokumentační jednotky
- [ ] PIAN - *

_Samostatné nálezy_
- [ ] Komponenta - období
- [ ] Sam. nález - okolnosti

_Knihovna 3D_
- [ ] Dokument - formát

--------------
Facetu “Nález - kategorie” - budeme muset vyřešit samostatně, protože se to případně musí řešit vazbou přes heslář, což tak původně nebylo; nechávám na samostatné issue

**Comment by motyc** [comment]
### Testování 17. 6. 2024
- [ ] Chyby zobrazení záznamů zaneseny do (viz komentáře): https://docs.google.com/document/d/1dCp9OAEiOq_3zmr-uLziC75eiDAWRDaa/edit
- [ ] https://digiarchiv-test.aiscr.cz/id/C-TX-192000061 - chyba výpisu - detail se nezobrazí, nefunguje ani přihlášení
- [ ] https://digiarchiv-test.aiscr.cz/id/C-TX-202400170 - vypíše se, ale obsah pak ihned zmizí
- [ ] Problémy s výpisem DJ a komponent:
-- https://digiarchiv-test.aiscr.cz/id/M-202100417A?lang=cs - ok
-- https://digiarchiv-test.aiscr.cz/id/M-202100417A-D01?lang=cs - neúplný výsledek
-- https://digiarchiv-test.aiscr.cz/id/M-202100417A-K001?lang=cs - nenajde vůbec
- [ ] https://digiarchiv-test.aiscr.cz/home - ze submenu dokumentů zmizeli letecké foto
- [ ] Faceta `Dokument - zachovalost` - vypisuje se dvakrát
- [ ] Chybí facety `Lokalita - stav dochování` a `Lokalita - jistota určení` (`archeologicky_zaznam/lokalita/zachovalost` a `archeologicky_zaznam/lokalita/jistota`)
- [ ] API - nefunguje GetRecord na záznamy 3D:
-- https://digiarchiv-test.aiscr.cz/id/C-3D-202200001
-- https://digiarchiv-test.aiscr.cz/api/oai?verb=GetRecord&identifier=https://api-test.aiscr.cz/id/C-3D-202200001&metadataPrefix=oai_amcr

**Mapa**
- [ ] Dokument - nezobrazí se tlačítko pro zobrazení mapy (i když data jsou indexována a zobrazena v mapě pořádku)
- [ ] Akce - po kliknutí na ikonu mapy u záznamu se mapa otevře, ale nezoomuje se na PIAN
- [ ] Projekty - body v mapě nejsou vidět
- [ ] 3D - body v mapě nejsou vidět

**Comment by albertoh** [comment]
> https://digiarchiv-test.aiscr.cz/home - ze submenu dokumentů zmizely letecké foto

Prosim o seznam mapovani pres heslo, a ne texty. Ted mame:

`
"nálezová zpráva": "texty",
        "příloha NZ/ZAA": "texty",
        "expertní posudek": "texty",
        "restaurátorská zpráva": "texty",
        "investorská zpráva": "texty",
        "hlášení/ZAA": "texty",
        "text jiný": "texty",
        "kresba předmětu": "texty",

        "data analýzy ekofaktů": "ddata",
        "data geodetická": "ddata",
        "data geofyzikální": "ddata",
        "data GPS": "ddata",
        "data terénního výzkumu": "ddata",
        "data vektorového plánu": "ddata",

        "foto krajiny": "foto",
        "foto lokality": "foto",
        "foto výzkumu/sondy": "foto",
        "foto osobní": "foto",
        "foto události": "foto",
        "foto pracovní": "foto",
        "foto objektu": "foto",
        "foto předmětu": "foto",
        "foto mikro": "foto",
        "foto konzervace": "foto",

        "letecká fotografie krajiny": "lfoto",
        "letecká fotografie lokality": "lfoto",
        "letecká fotografie metoda": "lfoto",
        "letecká fotografie výzkumu": "lfoto",
        "letecká fotografie vegetačních příznaků": "lfoto",
        "letecká fotografie půdních příznaků": "lfoto",
        "letecká fotografie sněžných příznaků": "lfoto",
        "letecká fotografie stínových příznaků": "lfoto",    

        "plán regionu": "mplany",
        "plán lokality": "mplany",
        "plán výzkumu": "mplany",
        "plán sondy": "mplany",
        "plán objektu": "mplany",
        "mapa": "mplany",

        "3D – textura": "ddata3d",
        "3D – rekonstrukce": "ddata3d",
        "3D – dokumentace": "ddata3d",
        "3D textura": "ddata3d",
        "3D rekonstrukce": "ddata3d",
        "3D dokumentace": "ddata3d",

        "-": "neuvedeno"
`

**Comment by motyc** [comment]
@albertoh Upravil jsem v: https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commit/6ebf6a5893b06cbf36f64a601683bd2e1bba9928

**Comment by motyc** [comment]
https://fedora-test.aiscr.cz/rest/AMCR/record/C-202105439/file/247de861-1196-4d77-baee-7509dad60fb7

**Comment by motyc** [comment]
K dodělání zbývají jen komentáře v https://docs.google.com/document/d/1dCp9OAEiOq_3zmr-uLziC75eiDAWRDaa/edit
