### ISSUE TITLE
Mapa - dílčí problémy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#24]
- [x]  když otevřu mapu přes konkrétní záznam, mapa se na chvilku na záznam vycentruje, ale následně se načte výchozí zobrazení mapy, čímž zmizí označení bodu
- [x] maximální zoom mapy je třeba nastavit tak, aby se vždy načetl podklad; nyní v jisté chvíli zmizí
- [x] při otevření mapy na přes konkrétní záznam by bylo dobré nastavit fixní měřítko, aby se mapa neotevřela na celý rozsah, ale např. v měřítku 1:5 000

**Comment by albertoh** [comment]
Ad. 1: Opraveno
Ad. 2: Maximalni zoom nastaven na 18
Ad. 3: Zoom pri otevreni zaznamu nastaven na 16

Na strankach OpenStreetmap je informace o meritkach podle zoom: https://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by motyc** [comment]
Ad 1 - ok
Ad 2 - sneslo by to i těch 20? Třeba v Praze může být PIAN hodně i v rámci jedné parcely:
![image](https://user-images.githubusercontent.com/20186892/100894276-9c8e4e80-34bc-11eb-98f3-c6cd04684bc9.png)

Ad 3 - opravdu je to na 16? To se mi nějak nezdá:
![image](https://user-images.githubusercontent.com/20186892/100894522-deb79000-34bc-11eb-990b-ae60179b0008.png)

**Comment by albertoh** [comment]
Hotovo
