### ISSUE TITLE
Ošetřit zranitelné endpointy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#246]
Detaily viz email.

**Comment by albertoh** [comment]
Problem byl ve zpracovani samostatnych nalezu

**Comment by albertoh** [comment]
Rovnou jsem to dal na produkci

**Comment by motyc** [comment]
Díky za ošetření. Šlo by prosím ještě z té odpovědi odebrat "odpovedny_pracovnik_vlozeni" - stejně to nepoužíváme a právě u samostatných nálezů to je citlivý údaj. Budu řešit i odebrání z API pro AMČR (v nové verzi to pak bude řešeno úplně jinak, tam to problém nebude).

**Comment by motyc** [comment]
@albertoh Testuji to dále a není to problém jen u nálezů. Stejná díra je i u lokalit, akcí, projektů a asi i u dokumentů - zkrátka všude tam, kde údaje skrýváme.

**Comment by albertoh** [comment]
OK, projdu vsechny. Akce, lokalita a projekt mam jasno co fixovat.
Akorat mi rekni pro dokument, protoze ani v rozhrani nemame skryty, napr. katastr

**Comment by motyc** [comment]
U dokumentů údaje skrýváme, jde ale vždy o děděná data z akce/lokality - viz např. zde: https://digiarchiv.aiscr.cz/id/C-DL-201100027

**Comment by albertoh** [comment]
Je to na testu. Bylo potreba reindexovat a novou konf solru

**Comment by motyc** [comment]
Všechny typy (možná kromě nálezu) - sice není vidět katastr, ale zobrazují se souřadnice, takže poloha je stále přímo zjistitelná

Akce - stále vidím katastr (např. pro https://digiarchiv-test.aiscr.cz/id/M-9106228A)

**Comment by albertoh** [comment]
Dalsi kolo proverek ...
Uz se tesim, az to prepisu z noveho API :)

**Comment by motyc** [comment]
Chápu, už se to blíží :)

Katastr u akce zmizel, ale stále všude vidím ty mapové souřadnice (je to vždy v polích lng a lat)
- https://digiarchiv.aiscr.cz/id/M-TX-202100672
- https://digiarchiv.aiscr.cz/id/M-9001150A
- https://digiarchiv.aiscr.cz/id/M-202101690
- https://digiarchiv.aiscr.cz/id/C-L9000004

**Comment by albertoh** [comment]
Ale to jsou odkazy na prod. Ja jsem to dal na testu :)

**Comment by motyc** [comment]
Neboj, já to testoval na testu, jen odkazy dávám na produkci. Posílám do mailu odkazy přímo do API.

**Comment by albertoh** [comment]
Reindexovano na testu.
Mame ale problem s tim stats lat a lng.
Napisu na skype

**Comment by motyc** [comment]
Obecně to funguje dobře, ale něco je špatně s projekty, protože to vrací 0 záznamů (https://digiarchiv-test.aiscr.cz/results?entity=projekt)

**Comment by albertoh** [comment]
Projekty nejsou indexovane. Ted bezi. Az to zkonci napisu

**Comment by albertoh** [comment]
Reindexovano. Uz jsou tam

**Comment by albertoh** [comment]
Je to na prod, reindexovano

**Comment by motyc** [comment]
V pořádku, zavírám.
