### ISSUE TITLE
Aktualizace knihoven

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#250]
Aktualizovat knihovny a následně nastavit dependabot pro sledování jejich aktuálnosti - viz https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

I když automatický update nebude vždy možný, budeme alespoň znát stav oproti aktuálním verzím.

**Comment by motyc** [comment]
@albertoh Zatím patrně neřešeno ve smyslu nastavení dependabot. Jak to mimochodem dopadlo s tou aktualizací materialu? Šlo to, nebo je stará verze?

**Comment by albertoh** [comment]
Material jsme nechali. To by vyzadovalo zkontrolovat uplne vsechny komponenty v angular. Menily se nazvy css classu.

**Comment by motyc** [comment]
@albertoh Jak jsme se spolu bavili, zde stačí nastavit dependabot (viz první příspěvek), aby probíhal monitoring. Nejde o automatické mergování, ale o to, abychom věděli, kdy nové verze vychází a jaké mám zpoždění.
