### ISSUE TITLE
Úprava autentizace uživatelů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#252]
Je třeba připravit pro připojení na nové řešení podle: https://github.com/ARUP-CAS/aiscr-webamcr/issues/934

Jde v podstatě jen o volání `{{amcr_url}}/api/token-auth/` pro získání autentizačního tokenu a `{{amcr_url}}/api/uzivatel-info/` pro získání údajů o uživateli.

Struktura vrácených údajů odpovídá https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/xml_generator/definitions/amcr.xsd

Oprávnění obsahuje element `<amcr:skupina>`
- A = Anonym (tj. uživatel bez autentizace)
- B = `<amcr:skupina>Badatel</amcr:skupina>`
- C = `<amcr:skupina>Archeolog</amcr:skupina>`
- D = `<amcr:skupina>Archivář</amcr:skupina>`
- E = `<amcr:skupina>Administrátor</amcr:skupina>`

**Comment by albertoh** [comment]
Existuje nejaky testovaci server?

**Comment by motyc** [comment]
Lze testovat na http://192.168.254.30:8080/. Uživatele INCAD a heslo lze použít stejné, jako se používá pro současnou produkci.

**Comment by albertoh** [comment]
Uzivatel nefunguje :(

http://192.168.254.30:8080/api/token-auth/

vraci
{
    "non_field_errors": [
        "Zadanými údaji se nebylo možné přihlásit."
    ]
}

**Comment by motyc** [comment]
### Výsledek testování (19. 10. 2023)
- [ ] Nemůže být správně řešeno, protože účtem motyc@centrum.cz se přihlásím, přestože ten není v dané verzi vůbec aktivní a API správně vrací:
```javascript
{
    "non_field_errors": [
        "Účet ješte nebyl aktivován. Pokud ste ho už aktivoval přes link v emailu, vyčkejte prosím na potvrzovací email od admina."
    ]
}
``` 
- [ ] Role u přihlášeného uživatele - je třeba doplnit překlad do lokalizací (nyní se zobrazuje jen klíč)
- [ ] Nevypisuje se organizace uživatele, když rozkliknu detail

**Comment by albertoh** [comment]
Presmerovano. Ted pouziva novy zpusob

**Comment by motyc** [comment]
### Test 25. 11. 2023
- [ ] nějak divně zlobí automatické odhlašování - občas proběhne velmi rychle, jindy mě to odhlásí, ale nevyskočí alert, takže se to pak chová rozbitě (prázdný modal s informacemi o uživateli); prostý refresh okna mne odhlásí
- [ ] pokud jsem přihlášený, většina stránek má problém s načítáním (nefunguje např. již proklik z homepage na jednotlivé typy záznamů)
- [ ] po otevření stránky persistentního odkazu nikdy nejsem přihlášený (i když to otvírám z tabu, kde jsem)

**Comment by albertoh** [comment]
> nějak divně zlobí automatické odhlašování - občas proběhne velmi rychle, jindy mě to odhlásí, ale nevyskočí alert, takže se to pak chová rozbitě (prázdný modal s informacemi o uživateli); prostý refresh okna mne odhlásí

Po dlouheee badani jsem si vsiml, ze v konfiguraci byla nastavena expirace po 18 vterin :o

**Comment by motyc** [comment]
### Test 30. 11. 2023
- [ ] prostý refresh okna mne odhlásí
- [ ] po otevření stránky persistentního odkazu nikdy nejsem přihlášený (i když to otvírám z tabu, kde jsem)

Test v Chrome a Firefox (zkoušel jsem i anonymní okno).

**Comment by motyc** [comment]
Potvrzuji, je to ok!
