### ISSUE TITLE
Úprava adresy podkladových map

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#253]
ČÚZK publikoval informaci, že "Základní mapy" byly nově nahrazeny "Základními topografickými mapami", jako novým státním mapovým dílem (https://geoportal.cuzk.cz/(S(ma3mri5szxeprkfr41bugx0u))/Default.aspx?mode=News&head_tab=&newsTyp=id&newsID=3123).

V této souvislosti dochází i ke změně adres souvisejících mapových služeb (původní přestanou být funkční 31. 12. 2023). Služba ZTM je nově poskytována zde: https://ags.cuzk.cz/arcgis1/rest/services/ZTM_WM/MapServer)

Spolu s tím to vypadá, že se bude měnit i adresa pro ortofotomapu na: https://ags.cuzk.cz/arcgis1/rest/services/ORTOFOTO_WM/MapServer

Je třeba změnit nastavení v Digitálním archivu tak, aby mapa fungovala s novou verzí služeb.

**Comment by albertoh** [comment]
Te dokumentaci moc nerozumim.
Nahradil jsem pro ČÚZK - Ortofotomapa

cuzkOrt = L.tileLayer('http://ags.cuzk.cz/arcgis/rest/services/ortofoto_wm/MapServer/tile/{z}/{y}/{x}?blankTile=false', { layers: 'ortofoto_wm', maxZoom: 25, maxNativeZoom: 19, minZoom: 6 });

 novym url:
  cuzkOrt = L.tileLayer('https://ags.cuzk.cz/arcgis1/rest/services/ORTOFOTO_WM/MapServer/tile/{z}/{y}/{x}?blankTile=false', { layers: 'ortofoto_wm', maxZoom: 25, maxNativeZoom: 19, minZoom: 6 });

Je to na testu

**Comment by motyc** [comment]
@albertoh Ortofoto je ok, ale ještě je třeba změnit adresu pro Základní mapu, tj. toto:
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/0cab4c8f0c1404ebbc284f6df00330be916ef730/web/src/main/ng/src/app/components/mapa/mapa.component.ts#L128

Myslím, že by mělo stačit zaměnit
```typescript
 cuzkZM = L.tileLayer('http://ags.cuzk.cz/arcgis/rest/services/zmwm/MapServer/tile/{z}/{y}/{x}?blankTile=false', { layers: 'zmwm', maxZoom: 25, maxNativeZoom: 19, minZoom: 6 });
``` 
za
```typescript
 cuzkZM = L.tileLayer('https://ags.cuzk.cz/arcgis1/rest/services/ZTM_WM/MapServer/tile/{z}/{y}/{x}?blankTile=false', { layers: 'zmwm', maxZoom: 25, maxNativeZoom: 19, minZoom: 6 });
``` 

Po nasazení a testu to půjde dát na produkci (vše ostatní je ok). Jen jako vždy připomínám, abys nezapomněl změnit verzi na 2.1.6

**Comment by motyc** [comment]
V pořádku, funguje. Tak už jen tu verzi a může to na produkci :)

**Comment by albertoh** [comment]
Verze taky je tam

**Comment by albertoh** [comment]
I na produkci

**Comment by motyc** [comment]
Perfektní, zavírám.
