### ISSUE TITLE
Doplnit endpoint pro stažení souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#256]
Před implementací je nutná příprava v https://github.com/ARUP-CAS/aiscr-webamcr/issues/1167

V návaznosti na #237 je třeba doplnit také endpoint pro stahování dat na základě `soubor/url` (např.: https://digiarchiv.aiscr.cz/id/C-202300529/file/3a1a5793-535a-4352-884f-69756d51d9b2)

- [x] odkaz resolvovat vrácením souboru ke stažení
-- filename = `soubor/nazev`
-- Content-Type = `soubor/mimetype`
-- Content-Disposition = "attachment"
- [x] umožnit autentizované stažení přes `curl -u [usr]:[pswd] [url]` (příklad s uložením: `curl -u usr:pwd -O -J --output-dir "C:\xxx" "url"`
- [x] je třeba domluvit, jak ošetříme ochranu proti nadměrnému přetěžování endpointu hromadným harvestingem dat
-- v rámci tohoto issue začít logovat přístupy a stažení (kdy, odkud, co)
-- nepovolit paralelní stahování z jedné IP
-- umožnit nastavit min. odstup mezi ukončením stahování a dalším zahájením (k zahájení dojde po uplynutí daného limitu)
- [x] zpřístupnit také náhledy a jednotlivé stránky pod:
-- https://digiarchiv.aiscr.cz/id/C-202300529/file/3a1a5793-535a-4352-884f-69756d51d9b2/thumb
-- https://digiarchiv.aiscr.cz/id/C-202300529/file/3a1a5793-535a-4352-884f-69756d51d9b2/thumb/page/1

**Oprávnění**
- [ ] kontrola oprávnění `projekt/soubor`
-- A-B: nikdy
-- C: `projekt/stav` = 1 OR (`projekt/stav` >= 2 AND `projekt/stav` <= 6 AND `projekt/organizace` = `{user}.organizace`)
-- D-E: bez omezení
- [x] kontrola oprávnění `dokument/soubor`
-- A: `dokument/pristupnost` = A AND `dokument/stav` = 3
-- B: (`dokument/pristupnost` <= B AND `dokument/stav` = 3) OR `dokument/historie[typ_zmeny='D01']/uzivatel` = `{user}`
-- C: (`dokument/pristupnost` <= C AND `dokument/stav` = 3) OR `dokument/historie[typ_zmeny='D01']/uzivatel.organizace` = `{user}.organizace`
-- D-E: bez omezení
- [x] kontrola oprávnění `samostatny_nalez/soubor`
-- A: `samostatny_nalez/pristupnost` = A AND `samostatny_nalez/stav` = 4
-- B: (`samostatny_nalez/pristupnost` <= B AND `samostatny_nalez/stav` = 4) OR `samostatny_nalez/historie[typ_zmeny='SN01']/uzivatel` = `{user}`
-- C: (`samostatny_nalez/pristupnost` <= B AND `samostatny_nalez/stav` = 4) OR `samostatny_nalez/historie[typ_zmeny='SN01']/uzivatel` = `{user}` OR `projekt/organizace` = `{user}.organizace`
-- D-E: bez omezení

**Comment by motyc** [comment]
Tímto pak prosím hned navažme, ale nejdřív doděláme opravy atd.

**Comment by albertoh** [comment]
Prosim o testovani. Hlavne opravneni

**Comment by albertoh** [comment]
Pridano do konfigurace novy klic:
"requestInterval": 30,
Ten urci kolik vterin musi minimalne uplynout nez se dovoli stahnout soubor z jedne IP
Zatim to je pro volani pres handle

**Comment by motyc** [comment]
- [ ] časové omezení aplikovat pouze na stažení originálu, ne na stahování náhledů (malého i stránek)
- [ ] potřeboval bych na testu zapnout generátor náhledů, jinak neotestuji pořádně ty stránky
- [ ] https://digiarchiv-test.aiscr.cz/id/C-TX-202400156/file/b0017699-09d6-4e68-bcea-e2e5705bd31c - jde stáhnout i anonymovi, přestože přístupnost je badatel (další případy nekontroluji, protože to asi nedává smysl, když nejde ani to základní ověření)

**Comment by albertoh** [comment]
> potřeboval bych na testu zapnout generátor náhledů, jinak neotestuji pořádně ty stránky

V adresari:

 /usr/share/thumbsgenerator

je ten generator. Muzes ho pustit pro jedenzaznam podle ident_cely. Na priklad pro dokument:

sudo -u tomcat java -Xmx3g -Damcr_app_dir=/var/lib/digiarchiv/digiarchiv3 -jar ThumbnailsGenerator-1.0.jar -ident_cely C-TX-198204189

**Comment by motyc** [comment]
- [ ] došlo mi, že malé náhledy u dokumentů a samostatných nálezů není třeba chránit oprávněními - přinášelo by to spíše komplikace než užitek (velké náhledy stránek samozřejmě ano); u projektů ochranu zachovat, tam je to citlivé i kvůli možným os. údajům
- [ ] `sudo -u tomcat java -Xmx3g -Damcr_app_dir=/var/lib/digiarchiv/digiarchiv3 -jar ThumbnailsGenerator-1.0.jar -ident_cely C-TX-198204189` - příkaz mi nefunguje, přihlásil jsem se přes Putty jako root a hlásí mi to `Unable to access jarfile ThumbnailsGenerator-1.0.jar`
- [ ] na rozdíl od API se nepoužívá session přihlášeného uživatele při zjišťování oprávnění pro danou URL - pokud to není velká komplikace, umožnit to i kvůli snazšímu testování (jinak vše musím dělat ručně přes curl)
- [ ] vrátí prázdný soubor (i po přihlášení, kdy bych měl dostat výsledek; totéž platí i pro pokusy stáhnout náhled):
-- https://digiarchiv-test.aiscr.cz/id/M-202300130-N00150/file/a32b14b0-3771-4511-a084-97d0d249243c
-- https://digiarchiv-test.aiscr.cz/id/C-201119689/file/3423ab9f-3b00-4898-a084-ca027d43c43e
(v pořádku je to pro https://digiarchiv-test.aiscr.cz/id/C-TX-202400156/file/b0017699-09d6-4e68-bcea-e2e5705bd31c, takže to vypadá jako problém souborů u projektů a samostatných nálezů)

**Comment by albertoh** [comment]
> sudo -u tomcat java -Xmx3g -Damcr_app_dir=/var/lib/digiarchiv/digiarchiv3 -jar ThumbnailsGenerator-1.0.jar -ident_cely C-TX-198204189 - příkaz mi nefunguje, přihlásil jsem se přes Putty jako root a hlásí mi to Unable to access jarfile ThumbnailsGenerator-1.0.jar

Jsi ve adresari /usr/share/thumbsgenerator ?
Mne funguje

**Comment by motyc** [comment]
Jo, pardon, já to přehlédl... nebyl jsem tam

**Comment by albertoh** [comment]
M-202300130-N00150 neni hledatelne ma stav = 3

Projekt C-201119689 take neni: pripojene archelogicke zaznamy nejsou dohledatelne

**Comment by albertoh** [comment]
Vsechno ostatne k testovani

**Comment by motyc** [comment]
> M-202300130-N00150 neni hledatelne ma stav = 3
> 
> Projekt C-201119689 take neni: pripojene archelogicke zaznamy nejsou dohledatelne

Tady jde patrně o nedorozumění. Ten endpoint má fungovat čistě podle oprávnění nastavených v tomto issue, nic dalšího se zohledňovat nemá. Proto jsou v oprávnění definovány i ty konkrétní stavy atd. Přímo to tedy nesouvisí se zobrazením záznamu v Digiarchivu. Musíme mít univerzální prostředek, jak se dostat z vnějšku k souborům, bez ohledu na jejich stav atd. Jen se musí správně ošetřit oprávnění, jak je definováno. Je tedy správně, že dané záznamy nedostane anonym. Problém je, že i po autentizaci jako admin přes curl jsem dostal prázdný výsledek.

**Comment by albertoh** [comment]
OK, to jsem nepochopil tak. Uz je to zmenenno

**Comment by motyc** [comment]
- [ ] Zcela náhodou jsem zjistil, že pokud za `*/thumb` doplním ještě `/1`, zcela to obejde oprávnění u dokumentů a sam. nálezů a podá mi to originální soubor místo 404. U projektů je to ok, zjevně to souvisí s tou úpravou pro malé náhledy.
-- https://digiarchiv-test.aiscr.cz/id/C-TX-202400156/file/b0017699-09d6-4e68-bcea-e2e5705bd31c/thumb/1
-- https://digiarchiv-test.aiscr.cz/id/M-202300130-N00150/file/a32b14b0-3771-4511-a084-97d0d249243c/thumb/1
- [ ] sam. nález - funguje stažení originálu i malého náhledu, ale nefunguje stažení náhledu stránky (vrátí 404):
-- https://digiarchiv-test.aiscr.cz/id/M-202300130-N00150/file/a32b14b0-3771-4511-a084-97d0d249243c/thumb/page/0
- [ ] projekt - nefunguje žádná varianta (všude 403, přestože jsem admin):
-- https://digiarchiv-test.aiscr.cz/id/C-201119689/file/3423ab9f-3b00-4898-a084-ca027d43c43e
-- https://digiarchiv-test.aiscr.cz/id/C-201119689/file/3423ab9f-3b00-4898-a084-ca027d43c43e/thumb
-- https://digiarchiv-test.aiscr.cz/id/C-201119689/file/3423ab9f-3b00-4898-a084-ca027d43c43e/thumb/page/0
- [ ] https://digiarchiv-test.aiscr.cz/id/C-TX-202400207/file/d2147697-79d8-43f2-9cc0-21c299e0e113 (totéž i `/thumb/page/0`) - jsem přihlášený jako badatel, nicméně záznam je v chybném stavu - systém soubor sice nepodá, ale vrací 200 místo 403 (pokud se úplně odhlásím, dostanu v pořádku 403)
- [ ] https://digiarchiv-test.aiscr.cz/id/C-TX-202400179/file/a068a7cf-5f64-43a4-b950-3336c5a2d54e - jsem přihlášený jako archeolog ARÚ, je tedy splněna podmínka `dokument/historie[typ_zmeny='D01']/uzivatel.organizace = {user}.organizace`, přesto mi soubor systém nepodá (vrací 200, ale soubor ne)
- [ ] Je trochu nešťastné, že generování náhledů čísluje soubory od 0 a ne od 1, takže to neodpovídá pořadí stránek a bude to i pro vytěžování hrozně matoucí. Je šance to nějak snadno předělat a skriptem přečíslovat soubory, abychom je nemuseli generovat všechny znovu?

**Comment by albertoh** [comment]
> sam. nález - funguje stažení originálu i malého náhledu, ale nefunguje stažení náhledu stránky (vrátí 404):

> -- https://digiarchiv-test.aiscr.cz/id/M-202300130-N00150/file/a32b14b0-3771-4511-a084-97d0d249243c/thumb/page/0

To je obrazek, ne pdf

> projekt - nefunguje žádná varianta (všude 403, přestože jsem admin):
    Tady bylo nutne reindex, uz probiha

> Je trochu nešťastné, že generování náhledů čísluje soubory od 0 a ne od 1, takže to neodpovídá pořadí stránek a bude to i pro vytěžování hrozně matoucí. Je šance to nějak snadno předělat a skriptem přečíslovat soubory, abychom je nemuseli generovat všechny znovu?

Zmenim akorat endpoint pro stazeni (udelam i+1). Nebudeme znovu generovat

**Comment by albertoh** [comment]
> https://digiarchiv-test.aiscr.cz/id/C-201119689/file/3423ab9f-3b00-4898-a084-ca027d43c43e/thumb/page/0

Neni to pdf

**Comment by motyc** [comment]
- [ ] U těch obrázků - ano, je pravda, že to není PDF, ale přesto potřebujeme nějak umět sáhnout na velký náhled. Ten by to tedy mělo na této stránce podat. Není myslím důvod komplikovat to tím, že bychom to dělali v daných případech jiným způsobem.
- [ ] https://digiarchiv-test.aiscr.cz/id/C-TX-202400156/file/b0017699-09d6-4e68-bcea-e2e5705bd31c/thumb/1 - teď vrací 403 bez ohledu na stav autentizace - mělo by to ale vracet spíš 404, když tam ve skutečnosti nic není. To platí i pro jiné varianty, kdy adresa neexistuje.
- [ ] Při podávání konkrétní stránky prosím místo prefixu ve formě ID souboru (`soub-646333_0.jpg`) používat název souboru (`CTX202400156.pdf_0.jpg`)
- [ ] Přo příliš častých dotazech vracet [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) místo 409 a do header `Retry-After` vložit odpovídající počet vteřin, za jak dlouho se API opět odemkne.
- Pro testování souborů projektů musím počkat, než doběhne reindex (dej mi pak prosím vědět).

**Comment by albertoh** [comment]
> U těch obrázků - ano, je pravda, že to není PDF, ale přesto potřebujeme nějak umět sáhnout na velký náhled. Ten by to tedy mělo na této stránce podat. Není myslím důvod komplikovat to tím, že bychom to dělali v daných případech jiným způsobem.

Vracim thumb-large

Projekt dobehl

**Comment by motyc** [comment]
- [ ] C: `projekt/stav` = 1 OR **(`projekt/stav` >= 2 AND `projekt/stav` <= 6 AND `projekt/organizace` = `{user}.organizace`)** - zde je asi drobná chyba v interpretaci podmínky v tučně vyznačené části. Vypadá to, že se nesprávně řeší tato podmínka `projekt/organizace` = `{user}.organizace` a přístup nedostanu ani pro uživatele z dané organizace (testuji pro archeologa ARÚ zde: https://digiarchiv-test.aiscr.cz/id/C-201119689/file/3423ab9f-3b00-4898-a084-ca027d43c43e)
- [ ] Chci se jen ujistit, že generátor náhledů na produkci dělá náhledy i pro soubory, které nejsou přímo vidět v Digiarchivu. Pokud ne, musíme to kvůli fungování endpointu upravit a náhledy dogenerovat.

**Comment by albertoh** [comment]
Chyba v organizaci opravena

Generator na produkci negeneruje nahledy neviditelnych. Opravil jsem ho, aby generoval vsechno.
Muzeme tam pustit dogenerovani pro neviditelne
