### ISSUE TITLE
Po zavření mapy zmizí prostorový filtr

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#258]
Pokud otevřu mapu a udělám výběr boxem, filtr se správně vytvoří. Jakmile zavřu mapu, automaticky však zmizí. Měl by zmizet buď po vypnutí nástroje, nebo cíleným odstraněním z filtrace. Dříve to fungovalo správně.

**Comment by albertoh** [comment]
Opraveno na testu
