### ISSUE TITLE
Automatické odhlášení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#26]
Stává se, že dojde k automatickému odhlášení a místo uživatele se objeví neidentifikovaný uživatel (undefined) a je třeba se odhlásit a opět přihlásit.

**Comment by albertoh** [comment]
Nemuzu reprodukovat.
Stava se to porad? Mohlo se to stat tehdy, kdy jsem zrovna daval novy build na server? Kdyz restartuju aplikace, vsechny session konci

**Comment by motyc** [comment]
Ok, necháme to otevřené a budeme to sledovat. Třeba se to už neobjeví. Narazil na to kolega. Časem to případně zavřu.

**Comment by motyc** [comment]
Přišel jsem na to, kdy se to děje - je to při refreshi okna. Tj. přihlásím se, refreshnu a zobrazí se:
![image](https://user-images.githubusercontent.com/20186892/100904211-175c6700-34c7-11eb-87ca-99565b2308ec.png)

**Comment by motyc** [comment]
Už vím kdy se to stává - je to při refreshi okna. Přihlásím se -> refresh ->
![image](https://user-images.githubusercontent.com/20186892/100904286-280cdd00-34c7-11eb-994d-5772384af25b.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Na refresh už v pořádku, ale ještě jsem na to narazil jinde a to při otevření nového okna (ať už ručně nebo pomocí persistentního odkazu).

**Comment by albertoh** [comment]
Myslim si, ze zrovna ses trefil, kdyz jsem dal novy build.
Uz nic noveho tam nedam dnes. Muzes testovat

**Comment by motyc** [comment]
Ano, asi máš pravdu. Už je to dobré, díky.
