### ISSUE TITLE
Chyba přiřazení polohy dokumentu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#264]
U dokumentu C-TX-202300447 se po zobrazení v mapě ukazuje špatná poloha. Dokument patří k akci C-201442446A a k ní patří PIAN P-1332-101187 až P-1332-101191. Ty se u akce zobrazují správně na správném místě, ale u vlastního dokumentu je připojený PIAN P-1314-011453. Ten patří ale k akci C-201445137A a také se u ní správně zobrazuje.

V API je vše napojeno dobře (resp. chybu nevidím), patrně tak půjde o chybu indexace.

**Comment by albertoh** [comment]
Je to divne... Tam je odkaz na dokumentacni_jednotku C-201442446A-D06. Ta ale neexistuje.
Doslo k odstraneni?
Asi by bylo dobre to cele reindexovat
