### ISSUE TITLE
Doplnit cookie lištu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#265]
Musíme doplnit cookie lištu s odpovídajícími funkcemi (viz např. https://www.pruvodcepodnikanim.cz/clanek/novela-zakona-cookie-lista-2022/)

Udělat obdobně jako na https://amcr.aiscr.cz/

**Comment by albertoh** [comment]
Jake moznosti tam musi byt?
Je mozne, aby uzivatel odmitnul napr. logovani pristupu? Pokud ano, musim i backend pripravit na to.
Jinak, aplikace nepouziva cookies

**Comment by motyc** [comment]
Naše logování přístupů v rámci #412 bych nedovoloval vypnout, protože jde i o bezpečnostní záležitost a lze to myslím považovat za jádrovou funkci. Navíc jestli nepoužívá cookies, tak to s tímto nesouvisí.
Co ale musí jít vypnout je Google Analytika, která sama o sobě cookies používá.

**Comment by albertoh** [comment]
Takze Google Analytics je jedine. 
Ted je videt jak by to vypadalo. Dodelam vypinani GA

**Comment by motyc** [comment]
Bezva. Koukám na to a vidím problém jen v tom, že musí jít také modal zavřít bez odpovědi (např. křížkem v rohu). Dokud to uživatel nepřijme, nesmíme údaje sbírat. Pak upravím textaci. Pokud nepoužívamé cookies na nic jiného než pro GA, tak to sdělení bude trošku jiné a odpadá tím nutnost dalších voleb.

**Comment by motyc** [comment]
Jo a platnost rozhodnutí bych nastavil na 12 měsíců.

**Comment by albertoh** [comment]
Funkcionalita hotova. Zbyva dodelat text

**Comment by motyc** [comment]
Funguje v pořádku.

- [ ] Původní značku ještě prosím nahradit aktualizovanou značkou `G-ZVN4RLK11P`
- [ ] Text CS:
```
Tato stránka využívá analytická cookies od Google Analytics pro sledování návštěvnosti webových stránek. Sbíraná data nám pomáhají pochopit, jak interagujete s webem, umožňují zlepšovat jeho fungování a zajišťují, aby byl pro uživatele co nejpříjemnější a nejužitečnější. Jsou též důležitá pro vykazování využití infrastruktury AIS CR vůči poskytovatelům financí.

Prosíme o laskavé svolení tato důležitá data sbírat.
``` 
- [ ] Text EN:
```
This site uses analytics cookies from Google Analytics to track website traffic. Collected data helps us understand how you interact with the site, helps us improve the way it works and ensures that it is as user-friendly and useful as possible. It is also important for reporting on the use of AIS CR to funders.

We kindly please you to allow us to collect this important data.
```
