### ISSUE TITLE
Nejasné chování facet

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#27]
- [x] když filtruji podle vedoucí akce/projektu faceta vedoucí akce/projektu se neupraví, tj. zůstanou v ní všechny původní hodnoty bez ohledu na provedenou filtraci (dtto autor, okres, organizace, posudek, pozorovatel, zachovalost, startovací letiště, počasí, tvar); původně jsem myslel, že se to nějak cyklí, ale problém je jen s obsahem facet, zobrazené výsledky jsou správné.

- [x] entita AKCE – katastr Benešov u Prahy – ve facetě se po filtraci objeví Benešov u Prahy (28) Jírovice (1) a Jírovice (Benešov) (1) – přitom jde o totožné heslo (Jírovice), jen se patrně v jednom případě špatně parsuje a zůstává jeho součásti okres

- [x] entita LOKALITY – faceta Kategorie (nálezu) – obsahuje pouze 3 záznamy, přestože v Druh nálezu je jich spousta; data musí být chybně (každý nález má druh i kategorii)

- [x] entita LOKALITY – filtr areál „hrad“ – proč je ve výsledku i C-N1000010, kde hrad v areálu není – je sice uveden v poli popis, ale to by nemělo hrát roli

**Comment by albertoh** [comment]
Ad. 1: Toto je spravne chovani, jak bylo vyzadovano: kazdy facet ovlivni ostatni facety, a ne sam sebe. A to tak, aby bylo mozne vybrat vice hodnot v ramci jedne facety.

Ad. 2: Opraveno

Ad. 3: Opraveno

Ad. 4: Tak jsi pozadoval pri poslednich opravach. Hrad se tam dostava z pripojenych dokumentu. Pro "sloucene" facety, (areal je mezi nimi), chtel jsi, aby se dostaly hodnoty z podrazenych entitach

**Comment by motyc** [comment]
Ad 1 - jenže ve skutečnosti neplatí ani toto. Navrhuji si zavolat a ukázat si to.
Ad 2 a 3 - ok
Ad 4 - ano, to by bylo dobře, jenže já ho nevidím ani v těch podřazených entitách, i zde navrhuji ukázat si to

**Comment by albertoh** [comment]
Ad. 1 Opraveno. Facety filtrujou i sebe 
Ad. 4 Opraveno podle tel hovor
