### ISSUE TITLE
Někdy nefunguje zobrazení detailu dokumentů v mapě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#271]
Po kliknutí na výsledek v seznamu u mapy se pro dokumenty v některých případech nezobrazí detail záznamu. Např. zde kliknutí na "íčko" u dokumentů nic nedělá.: https://digiarchiv.aiscr.cz/results?mapa=true&entity=dokument&page=0&sort=datestamp%20desc&loc_rpt=50.088719039135036,14.394554454618673,50.091415959140704,14.405364376291148

**Comment by albertoh** [comment]
To je kvuli tomu, ze uzivatel nema pristup k dokumentu. Jak se mame k tomu chovat?

**Comment by motyc** [comment]
Aha, díky za vysvětlení. Mělo by se to chovat stejně, jako při zobrazení mimo mapu - tj. vidím záznam i detail, jen neotevřu soubor.
