### ISSUE TITLE
Upravit loga

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#28]
Rozhodnout, co zůstane

**Comment by motyc** [comment]
Budou loga (v tomto pořadí)
- [ ] EU [loga_EU.zip](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/files/5630826/loga_EU.zip)
- [ ] MŠMT [MSMT.zip](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/files/5630837/MSMT.zip)
- [ ] AIS CR [AIS CR.ZIP](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/files/5630842/AIS.CR.ZIP)
- [ ] ARIADNE [ARIADNE.zip](https://github.com/ARUP-CAS/aiscr-digiarchiv-2/files/5630847/ARIADNE.zip)
- [ ] Strategie AV 21 https://www.ilaw.cas.cz/upload/web/images/web/Logo_Strategie_21.png

(ostatní loga odstranit a ty stávající zvětšit pro lepší čitelnost)

**Comment by pkudela** [comment]
hotovo, pripraveno k nasazeni, prosim @albertoh 
![image](https://user-images.githubusercontent.com/16591052/101178472-5286a380-3649-11eb-9682-04ff44cf227f.png)
