### ISSUE TITLE
Možnost správy uživatelského účtu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#3]
Navázat správu účtů na webklienta AMČR, kde je účet možné spravovat (např. změnit heslo atd.).

Stačí po přihlášení zobrazit v horní liště položku "Správa účtu" (přesněji domluvit s @pkudela), která povede na https://amcr.aiscr.cz/uzivatel/edit/ (dát do konfigurace).

**Comment by albertoh** [comment]
Pridano
