### ISSUE TITLE
Doladění konfigurace server

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#30]
Zdá se, že se neprodávají pole s hesláři - nebo jak je to definované?

**Comment by albertoh** [comment]
Da se konfigurovat podle entity. Je to klic "indexFieldsByType", kde je seznam poli pres ktere se hleda fulltextove
Na priklad, pro dokument 👍 "dokument": [
      "ident_cely",
      
        "typ_dokumentu",
        "material_originalu",
        "rada",
        "autor",
        "rok_vzniku",
        "organizace",
        "datum_zverejneni",
        "jazyk_dokumentu",
      
        "ulozeni_originalu",
        "child_soubor",
        "kategorie",
        "soubor_nazev",
        "soubor_uzivatelske_oznaceni",
        "jednotka_dokumentu_ident_cely",
        "jednotka_dokumentu_vazba_akce",
        "komponenta_parent",
        "komponenta_ident_cely",
        "komponenta_areal",
        "nalez_druh_nalezu",
        "nalez_kategorie",
        "nalez_specifikace",
        "f_aktivita",
        "pian_id",
      "popis",
      "poznamka", "typ_dokumentu_posudek","oznaceni_originalu", "extra_data_region"
      
    ],

**Comment by motyc** [comment]
@albertoh skvěle, díky za vysvětlení

**Comment by motyc** [comment]
Viz commit https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commit/c45063f87d8353275648f4b35daf3cb938579e38

Potřeba dořešit.

**Comment by motyc** [comment]
Celkové doladění také viz další commity (viz rozdíl oproti master).
