### ISSUE TITLE
Při chybě načítání vrátit chybovou hlášku

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#303]
Při chybě načítání místo nekonečného načítání progres baru vrátit chybovou hlášku

**Comment by albertoh** [comment]
Pripraveno na testu.

**Comment by motyc** [comment]
Nezdá se, že by fungovalo:
- https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0az_dj_negativni_jednotka%3D0:not
- https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0&f_obdob=

**Comment by albertoh** [comment]
Opraveno.
Pripady ruznych typ chyhb musim postupne prichyhtavat.
Je nutne definovat format chybove hlasky

**Comment by motyc** [comment]
Chybové hlášky bych normálně vložil do jako klíč do překladů, kde to přepíšeme do lidské řeči. Nebo to nejde?

**Comment by motyc** [comment]
Za mne je takto chování ok, jen bych upravil nadpis "Info" na "Chyba dotazu", resp. to vložil do překladů, stejně jako popisek tlačítka "Zavřít", pokud tam není.

**Comment by motyc** [comment]
- [ ] Proč je `"search_error": "Chyba při odeslání dotazu"` definováno pod `alert`, ale `"Zkuste zadat jiný dotaz": "Zkuste zadat jiný dotaz`" pod `citation`, kde to moc nedává smysl?
- [ ] `error` - v překladech nikde nevidím, asi doplnit
- [ ] `search_error` - překlad se nepoužije

![image](https://github.com/user-attachments/assets/56e8fc90-09cc-44c7-a518-ea29f118f337)

**Comment by albertoh** [comment]
Opravil jsem to. Kouknio jestli tak staci
