### ISSUE TITLE
Chybí některá data v detailu akce v mapě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#31]
![image](https://user-images.githubusercontent.com/20186892/100901695-694fbd80-34c4-11eb-8b03-2603958393b8.png)

Nechová se to ale všude stejně. Je to jako kdyby se data načetla jen částečně

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Bohužel musím znovu otevřít. Většina údajů tam je dobře, ale přesto to není úplné. Viz zde (chybí část hlavičky souvisejícího záznamu):
![image](https://user-images.githubusercontent.com/20186892/101228943-29dcc900-369e-11eb-8e3b-b4538a6eb485.png)

**Comment by albertoh** [comment]
Opraveno
