### ISSUE TITLE
Fix code scanning alert - HTTP response splitting

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#316]
Tracking issue for:
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/3
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/4
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/41
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/42
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/43

**Comment by albertoh** [comment]
Kod v alertexh je zastaraly
