### ISSUE TITLE
Fix code scanning alert - Cross-site scripting

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#317]
Tracking issue for:
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/8
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/28
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/29
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/30
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/33

**Comment by motyc** [comment]
Potvrdím po merge do main.

**Comment by motyc** [comment]
@albertoh Ještě zbylo 5 nevypořádaných položek.

**Comment by albertoh** [comment]
Vsechny 5 uz byly opravene
