### ISSUE TITLE
Fix code scanning alert - Server-side request forgery

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#334]
Tracking issue for:
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/44
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/45
- [x] https://github.com/ARUP-CAS/aiscr-digiarchiv-2/security/code-scanning/46

**Comment by albertoh** [comment]
Dissmised. url se sklada z hodnoty v konfigurace
