### ISSUE TITLE
Ladění rozhraní po úpravách

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#335]
Issue pro dořešení drobností v: https://docs.google.com/document/d/1dCp9OAEiOq_3zmr-uLziC75eiDAWRDaa/edit

**Comment by albertoh** [comment]
> u akce https://digiarchiv-test.aiscr.cz/id/C-9004591A?lang=cs je uprostřed detailu mezi DJ a komponentami vnořena ještě jedna sekce souvisejících záznamů, kde je stejná akce (tedy C-9004591A). Komentář je i připojen u akcí v tomto dokumentu a sem vkládám screeny, aby to výše nepřekáželo.

Opraveno

**Comment by motyc** [comment]
Potvrdil jsem hotové, ale něco ještě potřebuje doladit + jsem objevil pár nových drobností.
