### ISSUE TITLE
Nefunguje zohlednění příslušnosti k organizaci pro stahování dokumentů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#336]
Přestalo fungovat řešení pro #8. Pravděpodobně souvisí s úpravami heslářů atd. a bude třeba jen znovu provázat.

**Comment by albertoh** [comment]
Opraveno na testu.

**Comment by motyc** [comment]
@albertoh Celkově jsem to reorganizoval (ještě na tom pracuji). Zatím můžeš používat "DONE".

**Comment by albertoh** [comment]
Zatim je jen na testu... Muzu dat i do produkci (oprava je neskodna)

**Comment by albertoh** [comment]
Delam pres ID

**Comment by motyc** [comment]
Pak je tam asi ještě nějaký jiný problém, protože to nejede (viz příklad výše).

**Comment by albertoh** [comment]
Prece jen zustal jedno misto pres stary zpusob organizace

**Comment by albertoh** [comment]
Na testu

**Comment by albertoh** [comment]
Deplojovano na produkci
