### ISSUE TITLE
Chyba listování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#34]
Pokud dolistuji na nějakou stránku, a poté zúžím vyhledávací kritéria pomocí fulltextu (nikoli pomocí facety) tak, aby záznamů ubylo, stránka se nerefreshne správně a zůstane otevřený prázdný list:
![image](https://user-images.githubusercontent.com/20186892/101228644-e03fae80-369c-11eb-8e5d-274ca241c24b.png)

**Comment by albertoh** [comment]
opraveno
