### ISSUE TITLE
Zajistit zobrazování definičního bodu vždy na linii/uvnitř polygonu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#340]
Zejména u linií nyní definiční bod leží mimo samotnou linii. Bylo by vhodné změnit výpočet tak, aby se používal střed linie místo centroidu (nebo nejbližší lomový bod). Tím se zajistí, že to nebude utíkat. U polygonů je také třeba zajistit polohování dovnitř geometrie.

V AMČR na to používáme PostGIS funkci [ST_PointOnSurface](https://postgis.net/docs/ST_PointOnSurface.html) - chtělo by to implementovat její obdobu.

**Comment by albertoh** [comment]
Opraveno. Je nutna reindexace PIANu (na testu bezi)
Oprava je uz videt tady: 
https://digiarchiv-test.aiscr.cz/results?q=P-0232-100507&page=0&entity=akce&sort=datestamp%20desc&mapa=true&loc_rpt=50.64230615975154,13.691219130545234,50.69509212298099,13.908025179187563

**Comment by motyc** [comment]
Pozn. pro mě - až se doindexuje, otestovat, že funguje clustering.

**Comment by motyc** [comment]
Zdá se, že přestal fungovat clustering. Mapa zabliká a vyhodí:
![image](https://github.com/user-attachments/assets/966199b5-35c2-4dee-812f-1ed0f2d361f8)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
@albertoh Clustering je ok, ale to umisťování bodu buď není dotažené pro všechny případy, nebo to nefunguje. Viz: - https://digiarchiv-test.aiscr.cz/results?entity=lokalita&mapa=true&loc_rpt=50.168101438909176,13.91748201407782,50.17143988605205,13.930885639948192&page=0
- https://digiarchiv-test.aiscr.cz/results?entity=akce&mapa=true&loc_rpt=50.18161319054057,13.864160242170753,50.18369707153042,13.872529131497052&page=0&sort=datestamp%20desc

Je zajímavé, že to je pro některé případy ok a pro jiné ne. Není tam nějaký problém s tou indexací?

**Comment by albertoh** [comment]
Vypada ze neprobehla v poradku. To ale muze byt, protoze ja furt neco tam delam, a mozna jsem nasadil a restartoval tomcat driv nez zkoncila :o

**Comment by motyc** [comment]
Ok, tak já to pak prohlédnu znovu, nechávám to v testování.
