### ISSUE TITLE
Filtrace se zobrazuje i pro skryté katastry

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#342]
![image](https://github.com/user-attachments/assets/c52ad334-048e-47fe-bed0-cbf3bc80e51a)

Může se opakovat i na jiných místech, prosím případně prověřit.

**Comment by albertoh** [comment]
Opraveno na testu

**Comment by motyc** [comment]
V principu lepší, ale jsou tam nějaké podivnosti:
- [ ] https://digiarchiv-test.aiscr.cz/id/C-TX-202000451 - nevidím ani okres
- [ ] https://digiarchiv-test.aiscr.cz/results?page=0&entity=dokument&sort=datestamp%20desc&q=C-TX-198603981&f_katastr=Hrad%C4%8Dany:and - nic nenajde, přestože bych měl vidět C-TX-198603981 (na https://digiarchiv-test.aiscr.cz/results?page=0&entity=dokument&sort=datestamp%20desc&q=C-TX-198603981 je katastr vidět, protože je v neident. akci)

**Comment by albertoh** [comment]
Opraveno. Reindexuje se model "dokument"
Dokuemnt C-TX-198603981 je problematicni: ma pripojenou akce s pristupnosti D a neiden_akce (pristupnost A pro neident_akce) se stejnym katastrem

**Comment by motyc** [comment]
Druhý bod budeme řešit na úrovni dat. Jinak v pořádku.
