### ISSUE TITLE
Chyba překladů ve filtrech

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#344]
Pokud vybírám filtrace přes facety, správně se interpretují a zobrazují ve filtrech:

![image](https://github.com/user-attachments/assets/6c7c3d44-f27b-4af9-9ebb-0ee65714aced)

Pokud ale zkopíruji URL a otevřu ji v novém okně (např. https://digiarchiv.aiscr.cz/results?entity=dokument&f_organizace=ORG-000094:and&page=0), překlady se naplikují:

![image](https://github.com/user-attachments/assets/2f76fb20-e9de-4ea3-84dd-75b10bb6268a)

Platí to generálně pro všechny facety a je jedno, zda jde o heslo, organizaci nebo něco jiného.

**Comment by albertoh** [comment]
Opraveno na testu
