### ISSUE TITLE
Stahování velkých souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#345]
Pokud stahují větší soubory (např. https://digiarchiv.aiscr.cz/id/C-TX-202351036) na pomalejším připojení, dojde často k předčasnému ukončení stahování a vrácení neúplného souboru. Z uživatelského pohledu to nevyhodí žádnou chybu, jen to prostě ukončí stahování a soubor je rozbitý. Problém je pravděpodobně s nějakým time-out, ale není jasné, na jaké úrovni. Prosím prověřit, zda to dělá Digiarchiv, nebo zda jde o timeout na jiné úrovni. Podivné je, že se to neděje konzistentně. Mohlo by to být spojené i s nějakým chováním Fedory, ale těžko říci...

**Comment by albertoh** [comment]
Muzes, prosim, nahrat na testovaci fedoru nejaky velky soubor?

**Comment by motyc** [comment]
Tady jsem dal jeden opravdu veliký: https://digiarchiv-test.aiscr.cz/id/C-TX-202400201

**Comment by albertoh** [comment]
Zmenil jsem par veci, vcetne vetsi time-out. Je to na testu.
Me zatim pokazde vratil cely soubor.

**Comment by albertoh** [comment]
Vyresil jsem to. Opravdu byla komunikaci mezi servery a jeste podavani na konecny klient.
Pridal jsem mezikrok, stahovani do souboru na digiarchiv serveru.

**Comment by albertoh** [comment]
Jo, mazu po podani

**Comment by motyc** [comment]
Temp kvůli dostupnému místu ukládat někam do /var/lib/digiarchiv (asi podsložka /temp).

**Comment by albertoh** [comment]
Na testu

**Comment by motyc** [comment]
Testuji na https://digiarchiv-test.aiscr.cz/id/C-TX-202400201 a nyní mi nejde stáhnout vůbec:
![image](https://github.com/user-attachments/assets/bc13e11a-eff0-4457-9ce2-e57a117ec0b1)

**Comment by albertoh** [comment]
Tady byla spatna konfigurace serveru. Tomcat nemel pristup na adresar pro temp soubory. Opraveno

**Comment by motyc** [comment]
Vypadá to dobře (funguje to), ale je tam docela dlouhá prodleva, než se soubor začne stahovat a působí to, že se nic neděje - patrně je to čas, kdy se soubor přenáší mezi servery. Nešlo by tam ještě doplnit nějaký progres bar nebo jinou indikaci aktivity? Jinak myslím, že lidé budou klikat na tlačítko pro stažení opakovaně...

**Comment by albertoh** [comment]
Pridal jsem dialog. 
Progres bar bohuzel nejde v soucasnem stavu. Stahovani se dela primo na browseru, bez javascriptu. To by vyzadalo to delat uplne jinak.
