### ISSUE TITLE
Informace o nedostupném přihlášení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#347]
Pokud zapneme odstávku AMČR, v Digiarchivu se nejde přihlásit (to je v pořádku). Bylo by ale dobré, aby v tu chvíli uživatel nedostal zprávu o neplatných údajích, ale spíše informaci, že přihlášení není momentálně dostupné, ať to zkusí později. Jinak nám budou lidé zběsile psát, obnovovat hesla, apod.

Odpověď API se při neplatných údajích a nedostupnosti liší, takže to lze rozdělit (stačí kontrolovat, že buď dostanu token, nebo informaci o neplatných údajích a cokoli jiného znamená nedostupnost přihlášení jako takového).

**Comment by albertoh** [comment]
Zmeneno. Lze ale radne testovat, az bude server nedostupne :)
Simuloval jsem to zmenou v konfiguraci
