### ISSUE TITLE
Update od zvoleného timestamp

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#349]
Doplnit možnost volání update od zvoleného data a času

**Comment by motyc** [comment]
Moc nerozumím tomu, jak to funguje. I když zadám třeba https://digiarchiv-test.aiscr.cz/api/fedora/index_update?from=2024-09-20, od kdy se záznamy prokazatelně měnily, vrátí mi to (tj. `"updated": 0,`). Čím se ten údaj řídí? Vždyť by se měly všechny updatovat - nebo se pro každý záznam drží poslední timestamp, takže je to přeskočí?

![image](https://github.com/user-attachments/assets/482a65fe-55ac-4403-b48e-ad06090cb6cf)

**Comment by albertoh** [comment]
Chyba byla jen ve vypisu odpovedi. Proces spravne bezel. Spravna odpoved zni, napr

```
{
  "ellapsed time": "00:00:01",
  "deleted": 1,
  "process time": "00:00:00",
  "request time": "00:00:00",
  "updated": 9,
  "items": {
    "pagination": {
      "totalResults": -1,
      "offset": 100,
      "maxResults": 100
    },
    "items": []
  },
  "errors": [],
  "lastDate": "2024-09-24"
}
```
