### ISSUE TITLE
Chybné zobrazení datace provedení akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#35]
Minimálně u části záznamů se chybně zobrazuje vročení akce.

- [x] Např. u C-9104851A je uvedeno "v roce 01.01.1970", přestože API dává správné datum "v roce 2012" (https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-9104851A&metadataPrefix=oai_amcr). 
- [x] Jiný příklad je https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-9001155A&metadataPrefix=oai_amcr, kde se datum nezobrazí vůbec. Jde o příklad specifikace "před rokem".

Chybné jsou i ostatní varianty, tj.:
- [x] "v letech" (C-9103868A)
- [x] "po roce" (C-9000115A)
- [x] "kolem" (C-9000273A)

Půjde o problém chybné interpretace dat ve chvíli, kdy není datum uvedeno přesně. Jednotlivé případy lze rozlišit v poli "specifikace_data". Ty budou mít systemtaticky různým způsobem vyplněná pole "datum_zahajeni" + "datum_ukonceni" (tj. výpisový formát) a "datum_zahajeni_v" + "datum_ukonceni_v" (tj. formát pro řazení a hledání).

**Comment by albertoh** [comment]
Opraveno tak:
pokud specifikace_data je "přesně" zobrazim datum ve formatu dd.MM.yyyy
V opacnem pripade necham to jak je

**Comment by motyc** [comment]
Ještě potřebuje doladit (viz příklady v prvním příspěvku):
- "před rokem" - nezobrazí se vůbec
- "v letech" - začátek je dobře, konec je špatně
