### ISSUE TITLE
Při updatu aktualizovat i navázané záznamy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#350]
Při aktualizaci záznamu je třeba opětovně načíst data i pro navázané záznamy. I když totiž nedojde k jejich změně přímo, může dojít např. k tomu, že:
- se změní podmínky pro zobrazení záznamu a ten nově má/nemá být vidět
- se změní některá agregovaná data (např. katastry u dokumentu)

Možná mohou nastat i jiné situace, kdy bez aktualizace všeho napojeného nedojde ke správnému propsání změny do indexu.

**Comment by albertoh** [comment]
Prosim o testovani.

**Comment by motyc** [comment]
Podle mě je teď něco v indexaci rozbité, protože projekt https://amcr-test.aiscr.cz/projekt/detail/C-202401319 nevidím v Digiarchivu za žádný okolností, i když podmínky pro zobrazení splňuje. Nejde tak testovat ani chování zbytku.

**Comment by albertoh** [comment]
Opraveno.

**Comment by motyc** [comment]
- [ ] projekt - chování nejde testovat kvůli #335 (problém s indexací katastrů u dokumentu + chybějící zobrazení napojeného dokumentu)
- [ ] archeologicky_zaznam
-- projekt - nefunguje, projekt se po posunu akce do jiného stavu neskryl, akce samotná ano (test na https://digiarchiv-test.aiscr.cz/id/C-202109773A + https://digiarchiv-test.aiscr.cz/id/C-202109773) - došlo k tomu až po úpravě přístupnosti akce; naopak po opětovné archivaci akce zůstal projekt skrytý a neobjevil se, i když by měl být k dispozici
-- dokument - nefunguje, po úpravě přístupnosti akce https://digiarchiv-test.aiscr.cz/id/C-202109773A nedošlo ke skrytí katastru u dokumentu https://digiarchiv-test.aiscr.cz/id/C-TX-202100219 (tj. nemohl být reindexován); stalo se to až při posunu akce zpět do stavu 3
-- když nad tím tak přemýšlím, přijde mi to, jak kdyby to vše bylo nějak o krok posunuté, jen moc nechápu, jak je to možné - asi by bylo nejlepší, aby sis to sám prozkoušel na testu, nebo to mohu ukázat... některé změny se stanou hned, něco vždy až při druhém kroku a ve výsledku vlastně chybně
- [ ] samostatný nález - také nefunguje, nález https://digiarchiv-test.aiscr.cz/id/C-202402070-N00001 vidím, ale související projekt https://digiarchiv-test.aiscr.cz/id/C-202402070 nevidím...
- [ ] Ještě jsem zapomněl jednu možnost, a to že při změně `dokumentu` je třeba reindexovat napojený `projekt` (doplněno i do původního postu) - prostý posun stavu dokumentu totiž může mít vliv na zobrazení projektu; zadané to bylo jen opačně. Nyní jsem projekt https://digiarchiv-test.aiscr.cz/id/C-202402035 posunem dokumentu do jiného stavu nějak úplně rozbil...


PIAN teď neotestuju, protože to ovlivní až některé dodělávky v AMČR.

**Comment by albertoh** [comment]
Prosim o test znovu. Problem byl v tom, ze zmeny nebyly ulozene do indexu, nez se zacalo kontrolovat napojene souvislosti.
Pridal jsem zpracovani projektu pri zmene dokumentu

**Comment by motyc** [comment]
- [ ] projekt https://digiarchiv-test.aiscr.cz/id/C-202402035 se po úpravě katastru projektu aktualizoval, ale navázaný dokument nikoli https://digiarchiv-test.aiscr.cz/id/C-TX-202400197 (zůstal katastr Velká Dobrá)
- [ ] archeologicky_zaznam
-- projekt - nefunguje, projekt se po posunu akce do jiného stavu neskryl, akce samotná ano (test na https://digiarchiv-test.aiscr.cz/id/C-202109773A + https://digiarchiv-test.aiscr.cz/id/C-202109773) - došlo k tomu až po úpravě přístupnosti akce; naopak po opětovné archivaci akce zůstal projekt skrytý a neobjevil se, i když by měl být k dispozici - **žádná změna, logika je stále otočená (projekt zmizí po archivaci akce, když ji posunu do 2, naopak se objeví)**
-- dokument - nefunguje, po úpravě přístupnosti akce https://digiarchiv-test.aiscr.cz/id/C-202109773A nedošlo ke skrytí katastru u dokumentu https://digiarchiv-test.aiscr.cz/id/C-TX-202100219 (tj. nemohl být reindexován); stalo se to až při posunu akce zpět do stavu 3 - **také beze změny**
- [ ] samostatný nález - také nefunguje, nález https://digiarchiv-test.aiscr.cz/id/C-202402070-N00001 vidím, ale související projekt https://digiarchiv-test.aiscr.cz/id/C-202402070 nevidím... - **změna v tom smyslu, že projekt nyní naopak nezmizí po posunu nálezu do stavu 3, jen zmizí jeho související záznam; tj. něco se stane, ale chování není v pořádku**
- [ ] Ještě jsem zapomněl jednu možnost, a to že při změně `dokumentu` je třeba reindexovat napojený `projekt` (doplněno i do původního postu) - prostý posun stavu dokumentu totiž může mít vliv na zobrazení projektu; zadané to bylo jen opačně. Nyní jsem projekt https://digiarchiv-test.aiscr.cz/id/C-202402035 posunem dokumentu do jiného stavu nějak úplně rozbil... - **žádná změna, po posunu dokumentu do 2 je projekt opět rozbitý**

**Comment by motyc** [comment]
Perfektní, nenašel jsem problém :)
