### ISSUE TITLE
3D - chyba zobrazení mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#351]
Po otevření mapy v Knihovně 3D se nezobrazí všechna data. Je vidět toto, což působí tak, že data jsou jen v ČR:

![image](https://github.com/user-attachments/assets/43f6e307-1762-4187-958e-8f4f4ea92d78)

Přitom data jsou i na Guinei a v Polsku, což je v pořádku, ale zobrazí se až po prvním posunu mapou:

![image](https://github.com/user-attachments/assets/4c5f7441-e232-4200-942b-32695ad925da)

**Comment by albertoh** [comment]
Opraveno
