### ISSUE TITLE
Opravit export u mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#352]
Nevrací žádná data.

**Comment by motyc** [comment]
Funguje to hodně polovičatě:
- [ ] https://digiarchiv-test.aiscr.cz/export-mapa?entity=dokument&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=49.24477307144992,16.553210745834512,49.261157549675886,16.61776314787992&lang=cs&format=GML - vypsaly se jen dva záznamy (na mapě jich je mnohem více), a to ještě neúplné (chybí většina údajů o PIAN a definiční bod)
- [ ] https://digiarchiv-test.aiscr.cz/export-mapa?entity=dokument&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=49.252523164615454,16.540184932705035,49.26890507077539,16.6047373347504&lang=cs&format=GML - nefunguje vůbec
- [ ] https://digiarchiv-test.aiscr.cz/export-mapa?entity=projekt&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=49.32899184537278,15.725656791327468,49.42445056767163,16.10269620428048&lang=cs&format=GML - nefunguje vůbec
- [ ] https://digiarchiv-test.aiscr.cz/export-mapa?entity=akce&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=49.409110053638706,15.926539960257408,49.42057002221248,15.971839254205166&lang=cs&format=GML - vypisuje správný počet záznamů, ale chybí údaje o PIAN (viz výše); stejné je to pro lokality (https://digiarchiv-test.aiscr.cz/export-mapa?entity=lokalita&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=49.930378656865805,14.032127744890145,49.97649199051896,14.216436450411821&lang=cs&format=GML)
- [ ] https://digiarchiv-test.aiscr.cz/results?entity=samostatny_nalez&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=50.114992448506406,15.12610220148601,50.136006442348105,15.210393818720519 - tlačítko pro export úplně chybí
- [ ] https://digiarchiv-test.aiscr.cz/results?entity=knihovna_3d&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=49.92023531830593,15.15067746950119,49.9601212363982,15.310052169835272 - tlačítko pro export úplně chybí

**Comment by albertoh** [comment]
V kode bylo zakomentovano exporty pro samostatne nalezy a 3d knihovna. Uz si nepamatuju proc.
Totez ve formatovani export maji jine zpracovani (nemaji PIAN)
Od komentoval jsem schoivani tlacitka. Koukni na vysledek.

**Comment by motyc** [comment]
Je to stále trochu zmatečné:
- [ ] https://digiarchiv-test.aiscr.cz/export-mapa?entity=dokument&mapa=true&loc_rpt=49.53993822174833,16.65015399378545,49.54656404080832,16.676413488654095&page=0&lang=cs&format=GML - vypíše se celkem hodně záznamů, přitom v mapě jsou dva (https://digiarchiv-test.aiscr.cz/results?entity=dokument&mapa=true&loc_rpt=49.53993822174833,16.65015399378545,49.54656404080832,16.676413488654095&page=0)
- [ ] https://digiarchiv-test.aiscr.cz/export-mapa?entity=samostatny_nalez&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=50.114992448506406,15.12610220148601,50.136006442348105,15.210393818720519&lang=cs&format=GML - v exportu nesedí pole. V prvním sloupci chybí souřadnice a vše ostatní je o sloupec posunuté. Sloupec s GML chybí úplně.
- [ ] https://digiarchiv-test.aiscr.cz/export-mapa?entity=knihovna_3d&mapa=true&page=0&sort=datestamp%20desc&loc_rpt=49.94466689212126,15.19981220272157,49.9474618088342,15.21098139298812&lang=cs&format=GML - podobný problém jako u předchozího, navíc se nevypisují komponenty.

**Comment by albertoh** [comment]
Opraveno. Ale pozor, knihovna_3d nema geometrie

**Comment by motyc** [comment]
@albertoh Tomu moc nerozumím - měla by obsahovat geometrie v polích `dokument/extra_data/geom...`. V tom se nijak neliší např. od samostatného nálezu.

**Comment by albertoh** [comment]
Mas pravdu. Je to tam

**Comment by albertoh** [comment]
Opraveno
