### ISSUE TITLE
Rychlé filtry v mapě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#353]
Pokud chci použít rychlé přidání filtru z nabídky výsledků v mapě (např. jméno konkrétního archeologa, abych viděl, kde všude měl akce), tak se mi mapa rovnou přiblíží na záznam z nějž filtr použiju, jméno se sice přidá do aktivního filtru, ale abych viděl např. celou republiku s působností daného archeologa, tak musím jeho jméno zadat do filtru ručně.

V při kliknutí na filtrační položkou neotevírat detail záznamu, ale pouze aplikovat filtr.

**Comment by albertoh** [comment]
Pridano
