### ISSUE TITLE
Řazení ve facetě Nález - druh

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#354]
Faceta Nález - druh se špatně řadí podle pořadí v hesláři. Problém je v tom, že jde o dva sloučené hesláře (předměty a objekty - lze poznat podle podle nazev_heslare) a každý má samostatnou řadu. Udělat tak, že se nejdřív vypíše jeden celý heslář a pak druhý celý heslář.

**Comment by albertoh** [comment]
Hotovo.
Nejdriv hesla pro "predmet_druh" a potom pro "objekt_druh"
