### ISSUE TITLE
Matoucí pauza při renderování stránky exportu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#355]
Stránka exportu (např. https://digiarchiv.aiscr.cz/export?entity=projekt&page=0&sort=datestamp%20desc&lang=cs) se poměrně dlouho renderuje, ale nezobrazí se žádný progress bar nebo indikace aktivity. Je to natolik matoucí, že uživatel dříve okno zavře, než dostane výsledky. Je třeba chování nějak upravit.

**Comment by albertoh** [comment]
Pridan "loading bar"
