### ISSUE TITLE
Obnovit generování náhledů stránek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#356]
Aktuálně vypnuté. Je třeba otestovat a následně začít (asi přes noc) generovat.

**Comment by motyc** [comment]
@albertoh Malé i velké náhledy by vždy měly být ve formátu PNG (bez ohledu na formát originálu). Příklad pro originál TIFF zde: https://fedora-test.aiscr.cz/rest/AMCR/record/M-202300130-N00150/file/a32b14b0-3771-4511-a084-97d0d249243c

**Comment by albertoh** [comment]
Prepsano na png.
Napriklad 
https://digiarchiv.aiscr.cz/results?loc_rpt=48.57842428752037,11.40380859375,50.99992885585966,19.588623046875004&page=0&q=C-201119593A

**Comment by MichalKminek** [comment]
Sluzba spustena,

**Comment by motyc** [comment]
Díky oběma, zbývá vyřešit vyčištění od starých dat (z v3 i původní v2).
