### ISSUE TITLE
Akce - export - drobné chyby

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#357]
Při exportu akcí se objevují tři chyby:
- [x] Chybný popisek polí s datem zahájení a ukončení má být `akce_datum_zahajeni` a `akce_datum_ukonceni`, ale je `projekt_datum_zahajeni` a `projekt_datum_ukonceni`
- [x] datum v těchto polích formátovat jako datum (tj. bez času)
- [x] chybí překlad true/false v poli Akce - nahrazuje NZ

![image](https://github.com/user-attachments/assets/a1d27fd8-eab9-4075-8b80-a785b0b0e6b5)

**Comment by albertoh** [comment]
Opraveno
