### ISSUE TITLE
Úprava označení směru řazení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#358]
U řazení záznamů je jako symbol pro to, že se jedná o rozbalovací seznam, použita stejná šipka, která ale znamená uvnitř nabídky i sestupné řazení. Pokud tedy řadím vzestupně, tak to pak po zavření nabídky vypadá sestupně, což je vyloženě matoucí. 

![image](https://github.com/user-attachments/assets/cc762b7d-3edb-4766-b843-d1f6d6306c8e)

![image](https://github.com/user-attachments/assets/85ab9aba-0998-4abd-951c-ea215abaad59)

**Comment by albertoh** [comment]
Pridane jednoduche sipky k nazvum
