### ISSUE TITLE
Zpoždění při zobrazení mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#359]
Pokud ze seznamu výsledků u nějakého záznamu kliknu na ikonu mapy, zobrazí se mapa a dlouho se nic neděje - až po delší době mapa nazoomuje na příslušné místo a záznam (před tím ale není vidět žádný progresbar, takže to vypadá, jako chyba). Po přiblížení se navíc nenačtou ostatní okolní záznamy, ty přiskočí až po první posunu mapou.

**Comment by albertoh** [comment]
Prosim o testovani
