### ISSUE TITLE
Ve sloupcovém zobrazení chybí část detailu záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#36]
Po klinutí na zobrazit detail se ukáže pouze celá hlavička, nikoli zbytek záznamu:
![image](https://user-images.githubusercontent.com/20186892/101229378-3c580200-36a0-11eb-92c4-aed194eeab0f.png)

**Comment by albertoh** [comment]
opraveno

**Comment by motyc** [comment]
Funkčně ok, jen proč se tam zobrazuje ten horizontální posuvník? To mi přijde nadbytečné a vše by se mělo zalamovat, když bude třeba.

![image](https://user-images.githubusercontent.com/20186892/101341696-c612f580-3881-11eb-8f3e-9ec318fe7819.png)

**Comment by pkudela** [comment]
![image](https://user-images.githubusercontent.com/16591052/101372308-0a1af000-38ac-11eb-8a22-7d2eeeb8c32d.png)

**Comment by pkudela** [comment]
@albertoh prosim o nasazeni na server
