### ISSUE TITLE
Dok. jednotka - typ zjištění - chyba filtrace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#360]
Filtrovat podle pole bez hesláře - Dok. jednotka - typ zjištění
- [ ] Mělo by zde být: "pozitivní" pro false a "negativní" pro true
- [ ] Filtr nevrací žádné výsledky, patrně to pracuje s 1/0 místo true/false

![image](https://github.com/user-attachments/assets/053cad41-decf-47fc-ac5e-a39eb7a0582d)

**Comment by albertoh** [comment]
Opraveno na testu

**Comment by motyc** [comment]
Chová se to nějak podivně:

- [ ] jak pro https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0&sort=datestamp%20desc&az_dj_negativni_jednotka=0:or, tak pro https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0&sort=datestamp%20desc&az_dj_negativni_jednotka=1:or se zobrazí aktivních filtrech totéž, přestože jednou je volba "pozitivní" a podruhé "negativní"
- [ ] https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0&f_obdobi=HES-000252:or&az_dj_negativni_jednotka=0:not - i když je tam "not" tak to vrací hodnoty (nemělo by při dané kombinaci vrátit nic, protože pokud AZ nemá pozitivní DJ, nemůže mít, nemůže mít komponenty)

**Comment by albertoh** [comment]
Opraveno.
Reindexovalo se, ted uz jsou spravne vysledky a preklady

**Comment by motyc** [comment]
Funguje to v pořádku pro AZ, ale je mi divné, co [tento dotaz](https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0&az_dj_negativni_jednotka=0:not&sort=datestamp%20desc) dává za výsledky v jiných entitách - v dokumentech či PAS, bych čekal nuly...

**Comment by albertoh** [comment]
To je v poradku. NOT znamena, ze zaznam nema tu hodnotu... a opravdu vsechny ostatni entity nemaji zadnou, ony nemaji to pole.
To se bude dit pro vsechny dotazy typu NOT, nejen pro toto pole
