### ISSUE TITLE
Chyby filtrů bez hesláře

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#361]
Filtrovat podle pole bez hesláře:
- [x] Uživatelské označení - nevrací žádný výsledek
- [x] Kalendáře začínají rokem 0, nejde to nějak upravit aby začínal na nějakém logičtějším roce (letošek)?
-- Dokument - rok vzniku
-- Dokument - rok události od
-- Dokument - rok události do
-- Neident. akce - rok zahájení
-- Neident. akce - rok ukončení
-- ADB - rok popisu:
-- ADB - rok revize:
- [x] Dokument - rok vzniku - filtr nevrací žádné výsledky.
- [x] Dokument - měřítko
-- nevrací žádné výsledky
-- po aktivaci filtru vidím také jen první číslici ze zadaného měřítka
- [x] Let - identifikátor - nevrací žádný výsledek
- [x] Komponenta dok. - přesná datace - nevrací žádný výsledek
- [x] Zvláštní chování - při rozsahu do hodnoty 2 to ukáže i soubor https://digiarchiv-test.aiscr.cz/id/M-TX-202100273. Ten má ale 2,4 MB, při rozsahu 99-100 ukáže i https://digiarchiv-test.aiscr.cz/id/M-TX-201000399. Ten má 65,8 MB. Mělo by být možné zadávat i desetinná čísla.
- [x] Projekt - lokalizace: - nevrací žádné výsledky
- [x] Projekt - parcelní číslo: - nevrací žádné výsledky
- [x] Projekt - plánované zahájení - nevrací žádné výsledky
- [x] Projekt - rejstříkové číslo památky - nevrací žádné výsledky a jen běží loading bar
- [x] Projekt - popis památky - nevrací žádné výsledky a jen běží loading bar
- [x] Projekt - související akce - nevrací žádné výsledky
- [x] Akce - lokalizace: - nevrací žádné výsledky
- [x] Lokalita - název: - nevrací žádné výsledky a jen běží loading bar
- [x] Dok. jednotka - identifikátor - - nevrací žádné výsledky
- [x] Dok. jednotka - název: - nevrací žádné výsledky
- [x] ADB - identifikátor: - nevrací žádné výsledky
- [x] ADB - uživatelské označení - nevrací žádné výsledky a jen běží loading bar
- [x] ADB - ulice/trať - nevrací žádné výsledky a jen běží loading bar
- [x] ADB - číslo popisné - nevrací žádné výsledky a jen běží loading bar
- [x] ADB - parcelní číslo - nevrací žádné výsledky a jen běží loading bar
- [x] ADB - poznámka: - nevrací žádné výsledky a jen běží loading bar
- [x] Výškový bod - identifikátor: - nevrací žádné výsledky
- [x] Za "Výškový bod - identifikátor" jsou položky "Komponenta dok. identifikátor", stejná položka je i výše v seznamu za  "Obsahová část - související lokalita" (poskytují i stejné výsledky)
- [x] Komponenta - jistota: heslář nic nevrací, jaké jsou předpokládáné zadávané hodnoty? Ano/ne? jistá/nejistá? Pak by zde byly asi lepší přednastavené hodnoty než jen pole kam se může zadat cokoliv
- [x] Komponenta - přesná datace: - nevrací žádné výsledky
- [x] Komponenta - poznámka: - nevrací žádné výsledky, z jakého pole má filtr čerpat?
- [x] Nález - počet: - nevrací žádné výsledky
- [x] Nález - poznámka: - nevrací žádné výsledky
- [x] Lokalita - stav dochování: - nevrací žádné výsledky

**Comment by albertoh** [comment]
> Dokument - měřítko
  Musime rozhodnout jak se zachovat. V indexu obcas vidim data s mezerou a bez:
   1 : 1000
   1:1000
Jak mam pripravit index? Jake typy dotazy vrati vysledky? 
   - Presne: musi byt i s mezerami
   - Vyhodit mezery, ale plny format vcetne dvojtecka
   - Staci psat posledni kus, tj 1000

**Comment by motyc** [comment]
@albertoh Jsem pro kombinaci druhé a třetí varianty - tj. brát zápis `1:500` a `1 : 500` jako ekvivalentní a hledat i podle `500`.

**Comment by motyc** [comment]
@svejci Prosím o test všeho odškrtaného.

**Comment by motyc** [comment]
@albertoh Revidoval jsem Ondrův příspěvek tak, aby z něj bylo jasné, co je třeba řešit teď.

**Comment by motyc** [comment]
@albertoh Na https://digiarchiv-test.aiscr.cz/results?entity=dokument se objevila divná faceta `facet.field.f_let_uzivatelske_oznaceni`. V configu ji nevidím, asi je to nějaký bug.

**Comment by albertoh** [comment]
Opraveno. Problem konfigurace SOLRu

**Comment by motyc** [comment]
Zbytky vyčleněny do #397, jinak ok.
