### ISSUE TITLE
Chyby externích zdrojů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#362]
- [x] https://digiarchiv.aiscr.cz/id/BIB-0008876 - tečka za BIB v závorce, chybí mezera za závorkou před stranovým rozsahem
- [x] https://digiarchiv.aiscr.cz/id/BIB-0001649
-- chybí čárka a mezera před stranovým rozsahem
-- také je jedna připojená akce, ale mělo by jich být 33
- [x] pokud u článku v novinách (typ D) chybí název, objeví se tam “-” https://digiarchiv.aiscr.cz/id/BIB-0004812?lang=cs
- [x] https://digiarchiv.aiscr.cz/id/C-9153287A?lang=cs - u externího zdroje chybí rok vydání - Hájek - pak tam není dvojtečka za jménem - BIB-0004916
- [x] https://digiarchiv.aiscr.cz/id/C-9139234A?lang=cs - anonym u externího zdroje má u všech rok 1995 - vypadá to, že když je více anonymů u jednoho záznamu, tak to všem přidělí stejný rok
- [x] https://digiarchiv.aiscr.cz/id/BIB-0008876 - tečka za BIB v závorce, chybí mezera za závorkou před stranovým rozsahem - tady je i BIB na stránce persistentního odkazu, ale třeba u https://digiarchiv.aiscr.cz/id/BIB-0001649 to není - sjednotit
- [x] u článků - článek má svoji paginaci, ale může mít i paginaci odkazu, pokud ale není paginace odkazu uvedena, tak se nezobrazí nic - uvést tedy paginaci zdroje a za ní paginaci odkazu v závorce

**Comment by albertoh** [comment]
> pokud u článku v novinách (typ D) chybí název, objeví se tam “-” https://digiarchiv.aiscr.cz/id/BIB-0004812?lang=cs

Jako nazev je - ve fedore

**Comment by albertoh** [comment]
> https://digiarchiv.aiscr.cz/id/C-9153287A?lang=cs - u externího zdroje chybí rok vydání - Hájek - pak tam není dvojtečka za jménem - BIB-0004916

Nevidim rok vydani ve fedore.

**Comment by albertoh** [comment]
> https://digiarchiv.aiscr.cz/id/BIB-0008876 - tečka za BIB v závorce, chybí mezera za závorkou před stranovým rozsahem - tady je i BIB na stránce persistentního odkazu, ale třeba u https://digiarchiv.aiscr.cz/id/BIB-0001649 to není - sjednotit

Jak sjednotit, pridat nebo odebrat?

**Comment by albertoh** [comment]
> u článků - článek má svoji paginaci, ale může mít i paginaci odkazu, pokud ale není paginace odkazu uvedena, tak se nezobrazí nic - uvést tedy paginaci zdroje a za ní paginaci odkazu v závorce

Prosim o priklad, nejlepe na testu

**Comment by motyc** [comment]
> > https://digiarchiv.aiscr.cz/id/BIB-0008876 - tečka za BIB v závorce, chybí mezera za závorkou před stranovým rozsahem - tady je i BIB na stránce persistentního odkazu, ale třeba u https://digiarchiv.aiscr.cz/id/BIB-0001649 to není - sjednotit
> 
> Jak sjednotit, pridat nebo odebrat?

Je to třeba sjednotit tak, aby:
- ident_cely se na stránce persistentního linku v rámci citace nezobrazovalo (je už v záhlaví záznamu)
- nebyla zdvojená mezera před závorkou s ISSN

Výsledek by měl vypadat takto:
- Siblík, Josef 1926: Z pravěku Blatné. In: Vrána, Martin (ed.), Město Blatná : obraz prehistorický, historický, kulturní, sociální a národohospodářský: prací přátel a rodáků města. Blatná, 3-12.
- Kudrnáč, Jaroslav 1963: Slovanský výzkum v Čechách po roce 1945. Archeologické rozhledy 15/5 (0323-1267), 625-662.

**Comment by motyc** [comment]
> > u článků - článek má svoji paginaci, ale může mít i paginaci odkazu, pokud ale není paginace odkazu uvedena, tak se nezobrazí nic - uvést tedy paginaci zdroje a za ní paginaci odkazu v závorce
> 
> Prosim o priklad, nejlepe na testu

@svejci Prosím, dohledej to nebo vytvoř.

@albertoh Zbylé dvě věci jsou opravdu problém v datech, ne ve výpisu. @svejci prosím, při hlášení to lépe kontroluj.

**Comment by svejci** [comment]
Jako příklad by mohl posloužit https://digiarchiv-test.aiscr.cz/id/BIB-0000037?lang=cs. Jsou k němu připojeny 2 akce, u jedné je i paginace odkazu, u druhé pagiance odkazu není.
Omlouvám se za přehlédnutí a tím způsobené komplikace.

**Comment by albertoh** [comment]
> > > u článků - článek má svoji paginaci, ale může mít i paginaci odkazu, pokud ale není paginace odkazu uvedena, tak se nezobrazí nic - uvést tedy paginaci zdroje a za ní paginaci odkazu v závorce
> > 
> > 
> > Prosim o priklad, nejlepe na testu
> 
> [@svejci](https://github.com/svejci) Prosím, dohledej to nebo vytvoř.
> 
> [@albertoh](https://github.com/albertoh) Zbylé dvě věci jsou opravdu problém v datech, ne ve výpisu. [@svejci](https://github.com/svejci) prosím, při hlášení to lépe kontroluj.

Jsem trochu zmaten... Tam pisete " pokud ale není paginace odkazu uvedena, tak se nezobrazí nic - uvést tedy paginaci zdroje a za ní paginaci odkazu v závorce". Ale paginace odkazu neni, nemujzu ji zobrazit v zavorce.
 V puvodnim dokumentu mel podminku zobrazit paginace titulu jen pokud jsem na strance titulu (napr. akce), ale pokud jsem v handle nikoli

**Comment by motyc** [comment]
> > > > u článků - článek má svoji paginaci, ale může mít i paginaci odkazu, pokud ale není paginace odkazu uvedena, tak se nezobrazí nic - uvést tedy paginaci zdroje a za ní paginaci odkazu v závorce
> > > 
> > > 
> > > Prosim o priklad, nejlepe na testu
> > 
> > 
> > [@svejci](https://github.com/svejci) Prosím, dohledej to nebo vytvoř.
> > [@albertoh](https://github.com/albertoh) Zbylé dvě věci jsou opravdu problém v datech, ne ve výpisu. [@svejci](https://github.com/svejci) prosím, při hlášení to lépe kontroluj.
> 
> Jsem trochu zmaten... Tam pisete " pokud ale není paginace odkazu uvedena, tak se nezobrazí nic - uvést tedy paginaci zdroje a za ní paginaci odkazu v závorce". Ale paginace odkazu neni, nemujzu ji zobrazit v zavorce. V puvodnim dokumentu mel podminku zobrazit paginace titulu jen pokud jsem na strance titulu (napr. akce), ale pokud jsem v handle externiho zdroje nikoli.

Pardon, ještě po úvaze a lepším prohlédnutí píšu znova - udělal bych to tak, že pokud existuje paginace odkazu, zobrazí se u odkazu paginace odkazu. Pokud neexistuje, zobrazí se paginace titulu. Na stránce zdroje pak vždy bude paginace titulu. Je to takto schůdné?

**Comment by albertoh** [comment]
Opraveno (doufam ze jsem to pochopil spravne)

**Comment by motyc** [comment]
@albertoh Ano, vypadá to věcně ok, jen zas zlobí trochu formátování, kdy se tady vypíšou divné zbytečné čárky: https://digiarchiv-test.aiscr.cz/id/C-202402007A?lang=cs
![image](https://github.com/user-attachments/assets/2a1d27c6-9b57-4d57-80c8-389254209082)

**Comment by albertoh** [comment]
Opraveno
