### ISSUE TITLE
Chyba roku u externích zdojů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#363]
Popis od @svejci
Na produkci mám teď takový kombinovaný problém 
- v AMČR máme externí zdroj https://digiarchiv.aiscr.cz/id/BIB-0003364 (https://amcr.aiscr.cz/ext-zdroj/detail/BIB-0003364)
- v AMČR i když si ho zobrazím v Digitálním archivu, tak je vročený do roku 1966
- na stránce persistentního odkazu má v Digitálním archivu připojenou jen jednu akci https://digiarchiv.aiscr.cz/id/C-9150067A - u ní se zobrazí správně s rokem 1966
- v api vidím u externího zdroje správně 1966

- [ ]  v AMČR má ale připojených celkem 8 akcí, které v Digitálním archivu nevidím
- [ ]  u akce https://digiarchiv.aiscr.cz/id/C-9117300A je pak tento externí zdroj zobrazen s rokem 1984 místo 1966

![image](https://github.com/user-attachments/assets/b64beded-c4e6-425c-8e26-d8d183a24003)

U @motyc je pak chování jiné. Já na stejném místě vidím 1966, a to jak ve výpisu záznamů, tak přes link na záznam:
- https://digiarchiv.aiscr.cz/results?q=C-9117300A&page=0&entity=akce&sort=datestamp%20desc
- https://digiarchiv.aiscr.cz/id/C-9117300A

Divné ale je, že to tam je celkově úplně jinak, protože je nějaký problém s jinými roky, kdy je pro všechny Výzkumy v Čechách vypsán rok 1969. Jiné je i pořadí záznamů:

![image](https://github.com/user-attachments/assets/f5e31998-dc5f-4563-8faf-7693c1c2faea)

**Comment by svejci** [comment]
To je opravdu nějaká podivnost, já přes ty linky, které jsi připojil, vidím stále 1984. Naopak ale vidím správně rozepsané ty Výzkumy v Čechách.
![obrazek](https://github.com/user-attachments/assets/e8865d43-dcf8-44c5-9893-7115f79be652)

**Comment by svejci** [comment]
Ještě jsem to teď zkoušel v jiném prohlížeči (chrome) na stejném PC a taky na jiném PC (také v chrome) a tam vidím záznam stejně jako @motyc, tedy správně rok 1966 ale zase problém s roky u Výzkumů v Čechách. Zkoušel jsem i refresh stránky a vymazat cache u původního firefoxu, ale pořád to vidím stejně.

**Comment by albertoh** [comment]
Opraveno na testu. Tam ale nemam ty same zaznamy

**Comment by motyc** [comment]
@svejci Prosím o test

**Comment by svejci** [comment]
Na testu jsem otestoval počty připojovaných akcí a zobrazení let u anonymních autorů (Výzkumy v Čechách). Zatím vypadá oboje OK. Ten záznam co má někdy špatný rok nevím úplně jak pořádně otestovat. Zatím jsem na testu na podobný při náhodném hledání nenarazil.

**Comment by motyc** [comment]
Ok, beru to jako hotové a pak to ještě prohlédneme na produkci.

**Comment by motyc** [comment]
@svejci Ondro, prosím o kontrolu na produkci.

**Comment by svejci** [comment]
Po prvotní kontrole:
- Výzkumy v Čechách zatím všude vidím správně, tedy anonymové s různými roky vydání - **to je OK**
- Problematický záznam Beneš - Vencl 1966 (https://digiarchiv.aiscr.cz/id/BIB-0003364. ) vidím také všude, kde jsem se podíval správně s rokem 1966 - **OK**
- 
- u akce https://digiarchiv.aiscr.cz/id/C-9117300A, kde jsme řešili špatný rok u @svejci, ale u @motyc byl zobrazený správně už tento externí zdroj (https://digiarchiv.aiscr.cz/id/BIB-0003364.) vůbec nevidím a ani v AMČR vazbu mezi ním a akcí nevídím (nevím ani kdo to odpojil)
- u https://digiarchiv.aiscr.cz/id/BIB-0005698.  pak vidím v Digitálním archivu připojeno jen 20 souvisejících záznamů. V AMČR jich ale vidím mnohem více (konkrétně 211). Platí asi i pro další externí zdroje, kde je připojené velké množství akcí (např. BIB-0005697, BIB-0005721 - u obou vidím připojených 20 souvisejících záznamů, jako by to bylo maximální zobrazené číslo).

**Comment by motyc** [comment]
@albertoh Chybějící záznam vysvětlen, šlo o reálnou editaci...

**Comment by albertoh** [comment]
Pocet opraven

**Comment by svejci** [comment]
Kdy nyní koukám na https://digiarchiv.aiscr.cz/id/BIB-0005698 tak vidím počty téměř správně (v aplikaci vidím 211 akcí a v Digiarchivu to ukazuje 210, počet lokalit souhlasí). U  https://digiarchiv.aiscr.cz/id/BIB-0004272. však vidím v aplikaci 133 připojených lokalit, ale Digiarchiv ukazuje jen 65 (počet akcí zde souhlasí).

**Comment by motyc** [comment]
@svejci Není tady problém v tom, že některé akce či lokality nejsou archivované? Prosím mrkni na to ještě.

**Comment by svejci** [comment]
@motyc Ano máš pravdu, problém byl v tom, že některé lokality nebyly archivované. Omlouvám se za zmatky a komplikace.

**Comment by motyc** [comment]
V pohodě, zavírám :)
