### ISSUE TITLE
Umožnit vybraným organizacím přistupovat k archivovaným dokumentům

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#365]
Pokud má organizace v elementu `cteni_dokumentu` hodnotu `true`, umožnit jejím uživatelůn s oprávněním `archeolog` a výše čtení libovolných dokumentů (tj. zpřístupnit soubory k prohlížení a stažení).

**Comment by albertoh** [comment]
Nevidim na testu zadnou organizace s hodnotou cteni_dokumentu  = true

Muzes pridat? Treba "ORG-000091" - tam mam testovaci ucty

**Comment by motyc** [comment]
@albertoh Máš to tam upraveno.
