### ISSUE TITLE
Zobrazení více PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#367]
Pokud má archeologický záznam více napojených PIAN a kliknu na zobrazení polohy v mapě, mapa se přiblíží na první a ostatní nejsou vůbec viditelné. Upravit tak, aby:
- [ ] Mapa zoomovala na všechny PIAN AZ a tyto byly všechny označeny
- [ ] U záznamů, kde se PIAN přebírá z AZ (projekty, dokumenty) byly zobrazeny všechny PIAN všech napojených záznamů

-----------

Postřehy @svejci k v3.0.1:
- Na testu když se prokliknu na zobrazení akce v mapě z okna s výsledky, tak vidím jen jeden PIAN, resp. jeho centroid. Když ale změním měřítko, tak vidím najednou všechny PIAN a centroidy k nim a ty k akci jsou označené jako že k ní patří. Lze to ověřit zadáním identifikátoru do Filtru.
- Když se ale do mapy prokliknu z persistentního odkazu, tak vidím stále jen jeden centroid bez ohledu na změny měřítka (zde identifikátor do filtru přidat nelze)

Postřehy @svejci k v3.0.0:
- Na produkci když se prokliknu z okna výsledků, tak vidím např. u C-202302180A oba (u jiných samozřejmě podle počtu DJ) centroidy. Po změně měřítka vidím už i okolní PIAN a PIAN k akci v plném rozsahu.
- Když se na produkci do mapy prokliknu přes persistentní odkaz, tak vidím opět jen jeden centroid stejně jako na testu.

**Comment by albertoh** [comment]
Testuju tady:

http://localhost:4200/results?entity=akce&page=0&sort=datestamp%20desc&f_katastr=Dub%C3%AD-Byst%C5%99ice:and

Napriklad zaznamy:
   Prvni zaznam ve vysledku: C-202304428A (2 PIANy) 
   Paty zaznam: C-201445745A (4 PIANy)

Pokud jsem to dobre pochopil, chovani je podle zadani

**Comment by motyc** [comment]
Chování jsi pochopil správně a je to dobré, jen se vyskytuje drobná chyba. Po otevření mapy jsou vidět PIAN záznamu a jeden nesouvisející vedle:
![image](https://github.com/user-attachments/assets/a37bbcd2-c5ac-4ef6-b2ab-e094f8ff9ae8)

Těch ostatní nesouvisející přiskočí až po prvním pohybu mapou:
![image](https://github.com/user-attachments/assets/264b6676-b33c-4316-80d8-afbf5e13cefc)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Teď je to tak, že se zobrazí mapa a je vidět pouze vybraný záznam (bez toho nesouvisejícího). Po pohybu mapou přiskočí zbytek z aktuální filtrace. Ideální by bylo, aby se to otevřelo rovnou ve stavu jako po prvním pohybu mapou (tj. vybraný záznam je zvýrazněný, zbytek je vidět normálně podle nastavení filtrace).

**Comment by albertoh** [comment]
Predelano podle tel. domluve

**Comment by motyc** [comment]
Takto je to za mě super.

**Comment by motyc** [comment]
@albertoh Přeci jen jsem jednu chybku našel - funguje to super, pokud je záznamů vyfiltrováno tolik, aby se nezobrazila heatpama. Pokud však záznam vyberu bez předchozí filtrace, otevře se mapa, je tam vidět daný PIAN a heatmapa. Mapa ale nezazoomuje, dokud sám nepřiblížím mapu do té fáze, kdy se mají už zobrazit clustery. Pak automaticky přiskočí na daný PIAN a zvýrazní ho žlutě. Zjevně ta událost čeká na vykreslení geometrií a nepočítá s heatmapou.

**Comment by albertoh** [comment]
A jak bychom tady mely postupovat? To same akorat zoomovat? Ale heapmap muze to delat osklive...
Udelam a uvidime

**Comment by albertoh** [comment]
Je to tam

**Comment by motyc** [comment]
@albertoh No, teď to zas po tom přiblížení nenačte hned ty okolní PIAN, než posunu mapu :) Je to zapeklité...

**Comment by albertoh** [comment]
Ale to nejde... Heatmap nema vysledky jako takove. 
Abych to docilil musim poslat dalsi dotaz do indexu s aktualni viditelnosti mapy... Zkusim

**Comment by motyc** [comment]
Koukám, že už opraveno a je to super!
