### ISSUE TITLE
V prohlížečce se nezobrazuje celý náhled

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#37]
Čekal bych toto (viz starý Digiarchiv):
![image](https://user-images.githubusercontent.com/20186892/101229445-9e186c00-36a0-11eb-989a-139306347faf.png)

Zobrazí se toto (nová verze):
![image](https://user-images.githubusercontent.com/20186892/101229456-b5eff000-36a0-11eb-85af-419793f1413c.png)

**Comment by pkudela** [comment]
@albertoh prosim nasadit na server

**Comment by motyc** [comment]
Chyba se vrátila:
![image](https://user-images.githubusercontent.com/20186892/103916428-b3a00c00-510c-11eb-8391-e1696cf8f581.png)

Správně:
![image](https://user-images.githubusercontent.com/20186892/103916473-c4508200-510c-11eb-8099-bcd70ae1e9cd.png)

**Comment by motyc** [comment]
Resp. doplňuji - spíš se to nedořešilo správně. Příklad https://digiarchiv2.aiscr.cz/id/C-3D-202000001 funguje dobře. Naopak https://digiarchiv2.aiscr.cz/id/C-202009779-N00009 se chová zvláštně.

**Comment by pkudela** [comment]
Fixed, hotovo, nechova se to zvlaste, pro entitu samostatne nalezy chybely parametry ts, @albertoh prosim nasad na testovani.
