### ISSUE TITLE
Pád z důvodu nedostatku paměti

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#383]
Generování náhledů si vzalo paměť, která pak chyběla Tomcatu. Reseni je dat Tomcatu dost pameti pri spusteni.

**Comment by MichalKminek** [comment]
Generator nahledu ma nastaveno:
java -Xmx40g -Damcr_app_dir=/..... -jar /.../thumbnailsgenerator-1.0.jar
omcat ma nastaveno
CATALINA_OPTS=-Xms512M -Xmx1024M
Server ma 55GB, generator max 40GB, tomcat 1G, nevidim, ze by dochazala RAM
pridal jsem sledovani

**Comment by MichalKminek** [comment]
Sluzba thumbsgenerator zrejme nebezi od 11.9.
novy jar soubor ma spatne jmeno ThumbnailsGenerator-1.0.jar misto thumbnailsgenerator-1.0.jar
opravil jsem a spustil generator a bezi, ram je dostatek a sleduji obsazeni

**Comment by MichalKminek** [comment]
RAM serveru navysena na 64GB, tomcatu pridano na start 4GB, max 5GB
