### ISSUE TITLE
Chyba heatmapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#389]
Mapě se nějak rozhodilo nastavení. Nyní po vstupu na https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc&mapa=true vidím (na produkci to nedělá):

![image](https://github.com/user-attachments/assets/51d567dd-d44c-4d85-b6aa-24c689754b5e)

**Comment by albertoh** [comment]
Opraveno.
Problemy byly zpusobeni chyby ze solru. Optimizoval jsem kod, ted i mapa se zobrazuje rychleji
