### ISSUE TITLE
Ve verzi záznamu pro tisk zůstávají ikony pro filtraci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#39]
Bylo by dobré zobrazit spíš verzi jako u persistentního linku, kde ikony pro filtraci nejsou. Už jen proto, že po zavření tisku tam ta obrazovka zůstane a filtry jsou nefunkční.

**Comment by pkudela** [comment]
hotovo -> 
![image](https://user-images.githubusercontent.com/16591052/101623836-491a8400-3a19-11eb-8bb4-9bb5cf2aab7d.png)

@albertoh prosim o nasazeni
