### ISSUE TITLE
Načtení okresů pro další katastry

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#393]
V souvislosti s opravami #335 se ukázal problém s tím, že ne všechny okresy jsou vypsány přímo v XML (vypisuje se vždy pouze okres hlavního záznamu).

V případě následujících elementů je třeba doplnit do indexu okres z vazby v hesláři (`ruian_katastr/okres`):
- `projekt/chranene_udaje/dalsi_katastr`
- `archeologicky_zaznam/chranene_udaje/dalsi_katastr`

**Comment by albertoh** [comment]
Opraveno. Je ale nutne reindexovat dokumenty. 
Tenhle uz je
https://digiarchiv-test.aiscr.cz/id/C-TX-202400197?lang=cs

**Comment by motyc** [comment]
@albertoh Ještě je

**Comment by motyc** [comment]
Ještě je to třeba doplnit do zobrazení u projektů a AZ - viz https://docs.google.com/document/d/1dCp9OAEiOq_3zmr-uLziC75eiDAWRDaa/edit

**Comment by albertoh** [comment]
Pridano

**Comment by motyc** [comment]
- [ ] https://digiarchiv-test.aiscr.cz/id/C-202402035 - vidím prázdnou závorku, ve výpisu projektů je to ok
- [ ] https://digiarchiv-test.aiscr.cz/id/C-9004591A - vidím prázdnou závorku, ve výpisu akcí ani tu závorku
- [ ] https://digiarchiv-test.aiscr.cz/id/C-N9000143 - ani v jednom případě nevidím nic

**Comment by albertoh** [comment]
> https://digiarchiv-test.aiscr.cz/id/C-202402035 - vidím prázdnou závorku, ve výpisu projektů je to ok

Nemuzu testovat. Zaznam ted je neindexovatelny, a nefunguje mi amcr-test.aiscr.cz/
