### ISSUE TITLE
Připravit nástroj na odstranění souborů smazaných z AMČR

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#4]
Po smazání souboru v AMČR tento přestane sice být v Digiarchivu indexován, nicméně náhled zůstane uložen ve filesystému. Generátor náhledů by měl tyto již neexistující soubory a prázdné složky odstraňovat.

**Comment by motyc** [comment]
@albertoh Alberto, jak to prosím vypadá s doplněním?

**Comment by albertoh** [comment]
Zacinam. Dneska, zitra bude

**Comment by albertoh** [comment]
Na testu jsem dal novy jar ThumbnailsGenerator obohaceni novym parametrem "checkDirs"
Volanim:
 java -Xmx3g -Damcr_app_dir=/var/lib/digiarchiv/ -jar ThumbnailsGenerator-1.0.jar -checkDirs report
prochazime strukturu a do souboru toberemoved20220407.txt se vypise seznam souboru a adresare vhodne k odstraneni

 java -Xmx3g -Damcr_app_dir=/var/lib/digiarchiv/ -jar ThumbnailsGenerator-1.0.jar -checkDirs remove
generuje ten report ale i odstrani dane soubory

Zatim jsem to testoval v modu report. Muzes se divat na obsah toho souboru, jestli se ti zda v poradku.

**Comment by motyc** [comment]
Děkuji. Projdu to zítra, dnes to bohužel nestihnu. Ještě se zeptám - odstraní ten skript i případné vyprázdněné složky? To by též nebylo špatné, ať se celkově drží pořádek...

**Comment by albertoh** [comment]
Nemaze. Muzu pridat moznost odstranit veskere prazdne slozky

**Comment by motyc** [comment]
To by bylo super, prosím udělej to.

**Comment by motyc** [comment]
@albertoh Otestováno, je to bez zjevných chyb (sobory v DB skutečně nejsou). Lze to myslím spustit.

**Comment by albertoh** [comment]
Je tam. Pridal jsem do souboru readme.txr jak volat.
Jeste se musi nastavit cron (@MichalKminek)

**Comment by motyc** [comment]
@MichalKminek Prosím, nastavíš to? Volal bych to jednou týdně o víkendu.

**Comment by MichalKminek** [comment]
Jde o nastaveni jen na produkci nebo i na testu? Aktualne mame jednu sluzbu Thumbs Generator Service.  Kdyz nastavim v cronu java -Xmx3g -Damcr_app_dir=/var/lib/digiarchiv/ -jar ThumbnailsGenerator-1.0.jar -checkDirs remove tak to predpokladam nebude mit vliv na existujici sluzbu a aplikace po mazani se ukonci sama? Ulozil bych to do shell skriptu kvuli nastaveni adresaru atd.

**Comment by motyc** [comment]
Stačí na produkci, na zbytek prosím o odpověď @albertoh 
Pokud to dobře chápu a šlo by jen o úpravu parametru exitující služby, tak případně prosím zachovej její stávající periodicitu (nevím ale zda to nebude nějak nadměrně zatěžující pro filesystem - pokud ano, bude to třeba oddělit)

**Comment by albertoh** [comment]
Ano, je to tak, novy parametr. Spustit jako jiny proces, jine casy. Konci samo.

**Comment by MichalKminek** [comment]
Na produkci nastaveno na kazdou sobotu 15:15, po nedeli se podivam do logu. Take prosim zkontrolujte běh.

**Comment by MichalKminek** [comment]
Skript probehl, ale poprosil bych o kontrolu, log z behu je zde /var/log/indexace/remove_deleted.log a obsahuje polozky s chybou  jako napr
Apr 23, 2022 3:15:57 PM cz.incad.arup.thumbnailsgenerator.Indexer checkDirs
SEVERE: null
java.nio.file.NoSuchFileException: /var/lib/digiarchiv/thumbs/xx/xx/xx/xxxxxxxxxxxxx_CTXxxxxxxxxx.pdf_medium.jpg
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1142)
        at org.apache.commons.io.FileUtils.delete(FileUtils.java:1175)
        at cz.incad.arup.thumbnailsgenerator.Indexer.checkDirs(Indexer.java:413)
        at cz.incad.arup.thumbnailsgenerator.ThumbsGenerator.main(ThumbsGenerator.java:59)

soubor /var/lib/digiarchiv/thumbs/toberemoved.20220423.txt obsahuje 770 polozek

vyse zminenych chyb je 155, zrejme chyba, ze soubor neexistuje

**Comment by motyc** [comment]
@albertoh Zdá se mi, že nějaká chyba tam asi bude. Když vezmu jako příklad:
```
Apr 23, 2022 3:15:14 PM cz.incad.arup.thumbnailsgenerator.Indexer checkDirs
SEVERE: null
java.nio.file.NoSuchFileException: /var/lib/digiarchiv/thumbs/4B/20/01/1549018455038_CTX196701204B.pdf_medium.jpg
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1142)
	at org.apache.commons.io.FileUtils.delete(FileUtils.java:1175)
	at cz.incad.arup.thumbnailsgenerator.Indexer.checkDirs(Indexer.java:413)
	at cz.incad.arup.thumbnailsgenerator.ThumbsGenerator.main(ThumbsGenerator.java:59)
```
Jedná se o dokument: https://digiarchiv.aiscr.cz/id/C-TX-196701204

Ten již nemá žádný soubor 1549018455038_CTX196701204B.pdf, přesto na serveru i po mazání nalézám toto:
![image](https://user-images.githubusercontent.com/20186892/165271139-86861788-14d4-4c66-85ba-01a2d88517bb.png)

Samotný soubor /var/lib/digiarchiv/thumbs/4B/20/01/1549018455038_CTX196701204B.pdf_medium.jpg je ale pryč.

**Comment by albertoh** [comment]
Podivam se pristi tyden :)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
@albertoh díky, zkontrolujeme to zase po víkendu.

**Comment by motyc** [comment]
@albertoh Tak chyby v logu sice již nejsou, nic to ale nemění na tom, že stále existuje tato složka i s obsahem, i když daný soubor už v AMČR vůbec není:
![image](https://user-images.githubusercontent.com/20186892/166229276-9e5deaea-acde-4848-9c9d-e52d238bc419.png)

**Comment by motyc** [comment]
@albertoh podle souborů `toberemoved.20220423.txt` a `toberemoved.20220430.txt` se mi zdá, jak kdyby to mazalo jen náhledy samostatných nálezů, ale PDF to vůbec neřeší, což je zvláštní.

**Comment by albertoh** [comment]
Problem vnik kvuli prvnimu  chybnimu behu. Ted adresare maji jinou strukturu, chybeji tam soubory, ktere skript pouziva pro identifikaci.

Opravim

**Comment by albertoh** [comment]
Opraveno.
Spustil jsem to pro report, je tam vygenerovan soubor toberemoved.20220504.txt pro kontrolu.
Zda se mi v poradku

**Comment by motyc** [comment]
@albertoh udělal jsem namátkovou kontrolu a vypadá to opravdu v pořádku, lze realizovat smazání a pak už to necháme běžet automaticky

**Comment by MichalKminek** [comment]
PO sobote jsem narazil jeste na jednu chybu
May 07, 2022 3:15:01 PM cz.incad.arup.thumbnailsgenerator.ThumbsGenerator main
INFO: action: -checkDirs
May 07, 2022 3:15:01 PM cz.incad.arup.thumbnailsgenerator.Indexer getClient
INFO: Getting solr client at http://localhost:8983/solr/soubor/
May 07, 2022 3:15:26 PM cz.incad.arup.thumbnailsgenerator.Indexer checkDirs
SEVERE: null
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: '/var/lib/digiarchiv/thumbs/02/02/20/1650354117314_MTX202200202.pdf_thumb.jpg'
        at org.apache.commons.io.FileUtils.requireDirectory(FileUtils.java:2635)
        at org.apache.commons.io.FileUtils.requireDirectoryExists(FileUtils.java:2651)
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2091)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:319)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
        at cz.incad.arup.thumbnailsgenerator.Indexer.checkDirs(Indexer.java:422)
        at cz.incad.arup.thumbnailsgenerator.ThumbsGenerator.main(ThumbsGenerator.java:59)

**Comment by motyc** [comment]
Potvrzuji, co psal Michal + dodávám, že k odstranění dotčených dat stále nedošlo.

**Comment by albertoh** [comment]
Dalsi oprava. Uvidime o vikendu

**Comment by motyc** [comment]
@albertoh Smazalo se toho tentokrát podstatně více. Obsah souboru toberemoved.20220528.txt se zdá být korektní.

Stále ale z neznámých důvodů zůstává: https://github.com/ARUP-CAS/aiscr-digiarchiv-2/issues/4#issuecomment-1114762159
U dotčeného dokumentu naopak chybí odpovídající nový náhled (https://digiarchiv.aiscr.cz/id/C-TX-196701204).

Celkově se zdá, že bylo ale smazáno spousta náhledů, které být smazány neměly. Po telefonické dohodě @albertoh vypne skript pro mazání a zapne nové generování náhledů. Vše se musí pořádně otestovat na testu před nasazením na produkci.

**Comment by motyc** [comment]
@albertoh Jaký je stav v tomto issue? Zdá se mi to vyřešené, ale nevidím tu žádný commit po svém posledním komentáři...

**Comment by albertoh** [comment]
Melo by to byt vyresene. Ten problem souvisel s #206

**Comment by motyc** [comment]
Ok, pak to také můžeme uzavřít.
