### ISSUE TITLE
Zvláštní výsledky při vyhledávání podle data provedení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#40]
Dotaz: http://192.168.254.3:28080/amcr/results?page=0&entity=akce&datum_provedeni=2010-01-01,2010-12-31:or

Mezi výsledky mne překvapuje např. záznam: http://192.168.254.3:28080/amcr/id/C-200810997A

Na základě čeho se vyhledá, když ani tato akce, ani související projekt v daném intervalu neprobíhali? - viz https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-200810997A&metadataPrefix=oai_amcr

**Comment by albertoh** [comment]
Byla chyba v indexaci pri datum zahajeni a ukonceni v tom samem dne.
Opraveno

**Comment by motyc** [comment]
Původní chyba se zdá opravená, ale ještě jsem narazil na to, že se asi špatně interpretuje údaj roku u Neidentifikované akce. Na dotaz: http://192.168.254.3:28080/amcr/results?entity=dokument&page=0&datum_provedeni=1921-01-01,1921-12-31:or dostanu v entitě dokumenty neočekávaná data (např. hned první - http://192.168.254.3:28080/amcr/id/C-TX-192000062).

**Comment by albertoh** [comment]
Opraveno.
Ale pozor, obcas vysledky jsou spatne, ale to kvuli chybam v datech, kdyz rok ukonceni je pred rokem zahajeni
Napriklad dokument C-TX-199201892
https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-TX-199201892&metadataPrefix=oai_amcr

**Comment by motyc** [comment]
Rozumím, díky, to si opravíme.
