### ISSUE TITLE
Chyba zobrazení katastru ve facetě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#406]
V AMČR máme akci C-9150301A (https://amcr.aiscr.cz/arch-z/akce/detail/C-9150301A). Akce je z katastrálního území Vůsí (Písek; 678325). V AMČR ji normálně pod tímhle katastrem najdu.

Když zadám katastr do našeptávače v Digiarchivu, tak ho mezi výsledky nevidím. Nevidím ho ani když si bez další specifikace jen seřadím katastry v hesláři podle abecedy. Když ale akci vyhledám, tak ten katastr v příslušné facetě k dispozici vidím (https://digiarchiv.aiscr.cz/results?entity=akce&page=0&sort=datestamp%20desc&q=v%C5%AFs%C3%AD). Při použití filtru přímo ze záznamu vidím ve facetě tuto možnost také (https://digiarchiv.aiscr.cz/results?entity=akce&page=0&sort=datestamp%20desc&f_katastr=V%C5%AFs%C3%AD:and).

**Comment by albertoh** [comment]
Opraveno
