### ISSUE TITLE
Chyba filtrace podle mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#407]
Při kombinaci katastru a prostorového výběru v mapě se u příkladu níže rozchází počet vsledků, který vidím v mapovém okně a v klasickém okně výsledků: https://digiarchiv.aiscr.cz/results?entity=akce&page=0&f_katastr=K%C5%99em%C5%BEe:or&loc_rpt=48.83927841186524,14.306929779052734,48.93927841186523,14.406929779052735&vyber=48.88673455656979,14.352009218895269,48.891715062600795,14.36109895215267&mapa=true

V mapovém okně, vidím 12 akcí, ale po zavření mapy je výsledků jen 5 i když parametry zůstávají stejné. Po opětovném otevření mapy vidím opět 12 výsledků.

**Comment by albertoh** [comment]
Opraveno
