### ISSUE TITLE
Chyba - další katastry

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#422]
U připojených záznamů dokumentu je u dalších katastrů prázdná závorka, místo výpisu odpovídajících okresů.

https://digiarchiv.aiscr.cz/id/M-TX-202100538?lang=cs

![image](https://github.com/user-attachments/assets/e3519b53-4d2a-439e-8e4c-ac84eb26bff6)

**Comment by albertoh** [comment]
Otestovano zde
https://digiarchiv-test.aiscr.cz/id/C-TX-202400161?lang=cs

**Comment by motyc** [comment]
Znovu otevírám - ve výpisu výsledků je to ok, ale v mapovém zobrazení záznamu a na stránce pers. linku chybí okres u dalších katastrů:
![image](https://github.com/user-attachments/assets/3919e06c-4225-4914-b6cb-098131594790)

**Comment by albertoh** [comment]
Opraveno
