### ISSUE TITLE
API - doplnit style-sheet pro OAI-PMH

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#423]
Postup pro implementaci zde: https://wiki.eprints.org/w/EPrints_OAI_Stylesheet (odkaz na style-sheet nefunguje - XSL zde: [oai2.zip](https://github.com/user-attachments/files/17803938/oai2.zip))

Výsledek by měl vypadat takto: https://amcr-info.aiscr.cz/oai/oai.xml (statická testovací stránka)

EDIT: Myšleno tak, aby stylesheet byl součástí všech odpovědí.

**Comment by albertoh** [comment]
Jaky chceme url?

Tak?
https://digiarchiv-test.aiscr.cz/oai/oai.xml

**Comment by motyc** [comment]
To je asi úplně jedno. Klidně takto...

**Comment by motyc** [comment]
Funguje to na https://digiarchiv-test.aiscr.cz/api/oai?verb=GetRecord&metadataPrefix=oai_amcr&identifier=https://api-test.aiscr.cz/id/C-9000547A

Ale ne na https://api-test.aiscr.cz/oai?verb=GetRecord&metadataPrefix=oai_amcr&identifier=https://api-test.aiscr.cz/id/C-9000547A

Důvodem bude je blokování cross-origin. Kam to máme umístit na https://api-test.aiscr.cz/ (a produkční https://api.aiscr.cz/), aby to fungovalo správně?

**Comment by motyc** [comment]
@MichalKminek Prosím o vložení souboru https://digiarchiv-test.aiscr.cz/api/oai2.xsl do root adresáře na https://api-test.aiscr.cz/ a https://api.aiscr.cz/

**Comment by MichalKminek** [comment]
nakopirovano na oba servery

**Comment by motyc** [comment]
@MichalKminek Děkuji.
@albertoh Můžeš to prosím prověřit. Na soubor se na přímo dostanu (https://api-test.aiscr.cz/oai2.xsl), ale stejně se stylesheet neaplikuje (vrací 302), přestože soubor na dané adrese je.
![image](https://github.com/user-attachments/assets/ffd2ed53-d220-4312-b009-bde2e9ab6b9e)

**Comment by albertoh** [comment]
Soubory odstranim.

Problem nezobrazeni je mimo me. Pri pokusu otevreni
https://api-test.aiscr.cz/oai?verb=GetRecord&metadataPrefix=oai_amcr&identifier=https://api-test.aiscr.cz/id/C-9000547A
browser hazi chybu:
Unsafe attempt to load URL https://api.aiscr.cz/oai2.xsl from frame with URL 

Podle toho vypada, ze neni spravne nakonfigurovan ten redirect (reverse proxy?)

**Comment by MichalKminek** [comment]
Problem bude asi v zaverecnem redirectu na testu - / -> https://api.aiscr.cz/, kdyz to vypneme, mohlo by to fungovat.

**Comment by MichalKminek** [comment]
Zrusen redirect, nastaveno prepsani hlavicek

**Comment by motyc** [comment]
@MichalKminek Potvrzuji, že funguje, díky moc.

Tak už jen uklidit pozůstatky (@albertoh ) a můžeme to zavřít.

**Comment by albertoh** [comment]
Vycisteno
