### ISSUE TITLE
Chyby náhledů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#424]
https://digiarchiv.aiscr.cz/id/C-TX-201100041?lang=cs

- [ ] Dokument má jako malý náhled soubor CTX201100041A.png, místo správného CTX201100041.png. Při výběru náhledu vždy seřadit soubory daného dokumentu podle názvu a vybrat první
- [ ] Pokud otevřu prohlížečku soborů, překliknu na druhý soubor a následně překliknu zpět na první, někdy zůstane viset původní zobrazení stránky z druhého souboru, místo aby se načetlo správné. Po nějaké chvíli se to aktualizuje, ale mate to.

**Comment by albertoh** [comment]
Testovano zde
https://digiarchiv-test.aiscr.cz/results?lang=cs&page=0&pristupnost=A:or&q=C-DT-202400001
