### ISSUE TITLE
Upravit Title element stránek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#426]
- [x] Popisek zůstává "viset" z předchozí stránky. Když např. jdu na https://digiarchiv.aiscr.cz/home a tam kliknu na Dokumenty, přestože jsem na https://digiarchiv.aiscr.cz/results?entity=dokument, zobrazuje se v záhlaví `Digitální archiv AMČR | Home`

Je třeba upravit popisky stránek na následující možnosti:
- [x] https://digiarchiv-test.aiscr.cz/home
-- cs: `Digitální archiv AMČR`
-- en: `AMCR Digital archive`
- [x] https://digiarchiv-test.aiscr.cz/results
-- cs: `Digitální archiv AMČR | Výsledky - [entities.dokument.title]`
-- en: `AMCR Digital archive | Results - [entities.dokument.title]`
- [x] https://digiarchiv-test.aiscr.cz/results?mapa=true
-- cs: `Digitální archiv AMČR | Mapa - [entities.dokument.title]`
-- en: `AMCR Digital archive | Map - [entities.dokument.title]`
- [x] https://digiarchiv-test.aiscr.cz/export
-- cs: `Digitální archiv AMČR | Export - [entities.dokument.title]`
-- en: `AMCR Digital archive | Export - [entities.dokument.title]`
- [x] https://digiarchiv-test.aiscr.cz/export-mapa
-- cs: `Digitální archiv AMČR | Export mapy  - [entities.dokument.title]`
-- en: `AMCR Digital archive | Map Export - [entities.dokument.title]`
- [x] https://digiarchiv-test.aiscr.cz/id/*
-- cs: `Digitální archiv AMČR | Záznam  - [ID]`
-- en: `AMCR Digital archive | Record - [ID]`

**Comment by albertoh** [comment]
K testovani

**Comment by motyc** [comment]
pro https://digiarchiv-test.aiscr.cz/export jsem udělal drobnou korekci, po nasazení potvrdím:
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commit/a0b972af38106c45a7e9b24b2a3ac3090e19f7b1
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commit/26439320cf09f0b431e057a91745e644e817980d
