### ISSUE TITLE
3D - chyba oprávnění pro stahování souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#429]
https://digiarchiv.aiscr.cz/id/C-3D-202400007/file/9b788770-eedd-4b2d-a8a9-7cb65c681c7a - soubor nejde stáhnout (403), přestože záznam je na úrovni anonyma. Patrně bude problém s interpretací oprávnění pro Knihovnu 3D

**Comment by albertoh** [comment]
Opravneni mam pouzivat jako pro Dokument?

**Comment by motyc** [comment]
Ano, přesně tak.

**Comment by albertoh** [comment]
Opraveno
