### ISSUE TITLE
Automatická volba entity podle výsledků

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#43]
Dávám k uvážení jako možné vylepšení (podle pracnosti) - pokud vyhledám něco fulltextem, často se stane, že výsledek je pouze v jedné z entit. Bylo by dobré, aby se automaticky nastavila ta entita, která má alespoň nějaké výsledky, nikoli ta s nulou.

Typický příklad je hledání http://192.168.254.3:28080/amcr/results?page=0&entity=dokument&q=%22C-9001155A%22

V takové chvíli je výsledkem jediný záznam, který snadno přehlédnu. Uživatel to pak snadno vezme tak, že se nic nenašlo.

**Comment by pkudela** [comment]
@albertoh  prosim o nasazeni
