### ISSUE TITLE
ADB - chybí proklik

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#435]
V detailu záznamu je u ADB nějak divně umístněná ikona s odkazem na Prahu archeologickou a úplně chybí odkaz na persistentní stránku v Digiarchivu. Tuším, že tam bude nějaký překlep v kódu.

![image](https://github.com/user-attachments/assets/9a2b9c6b-b413-4acc-94f7-37a73cb540d8)

Zde je vidět, jak to má být správně: https://digiarchiv-test.aiscr.cz/id/ADB-BERO76-000001-V0001?lang=cs

**Comment by motyc** [comment]
Už je to ok, jen je teď na pesr. stránce nadpis divně nalepený na horní okraj karty:
![image](https://github.com/user-attachments/assets/5b46494c-1932-4c1a-951c-90e3d9f20e02)

Taky jsem si všiml, že u VB se nevypíše obsah závorky u nadpisu na pers. stránce - má tam být typ VB.
![image](https://github.com/user-attachments/assets/89c3d9aa-fec8-4f7b-9c93-73bf10bc88d4)

**Comment by albertoh** [comment]
Opraveno
