### ISSUE TITLE
Soubory - chyba endpointu pro stahování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#436]
Číslování stánek se chová poněkud nekonzistentně.

https://digiarchiv.aiscr.cz/id/M-202305417-N00407/file/f0c5e6a8-ff37-4f47-80b9-162e6ab29e1f/thumb/page/0 vrátí soubor, ale čekal bych, že vrátí 404 (správně je https://digiarchiv.aiscr.cz/id/M-202305417-N00407/file/f0c5e6a8-ff37-4f47-80b9-162e6ab29e1f/thumb/page/1). Oba odkazy vrací totéž.

Pro https://digiarchiv.aiscr.cz/id/C-TX-202400694/file/819d353e-8a37-40e7-8c40-45acc64452a2/thumb/page/0 a https://digiarchiv.aiscr.cz/id/C-TX-202400694/file/819d353e-8a37-40e7-8c40-45acc64452a2/thumb/page/1 je přitom chování správné.

**Comment by albertoh** [comment]
Opraveno
