### ISSUE TITLE
Korektura grafiky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#44]
- [x]  Bylo by dobré, aby text zařezával s nadřazeným nadpisem (pokud pro odsazení není nějaký důvod):
![image](https://user-images.githubusercontent.com/20186892/101557840-18593100-39be-11eb-91e9-ad0c30c9bed8.png)

- [x] Modré nadpisy v detailu - hodně to svítí, až zbytečně - asi nic nebrání tomu, aby byli černé + tučné jako zbytek nadpisů.

- [x] Rozbalovací menu v detailu záznamu "Popis akce" a "Související záznamy" výškově s ničím nekorespondují. Navrhujeme sjednotit na stejnou výšku jako má tlačítko "Zobrazit detail" (tedy zmenšit).

- [x] Čitelnosti titulků by i díky menšímu písmu asi pomohlo, pokud by byly bold:
![image](https://user-images.githubusercontent.com/20186892/101557174-b77d2900-39bc-11eb-9d75-9fc4f33c7f97.png)

- [x] U souvisejících záznamů je zvláštní velká mezera pod náhledem (není stejná jako nad ním):
![image](https://user-images.githubusercontent.com/20186892/101557741-e47e0b80-39bd-11eb-8c32-cbedf7dcc7d3.png)

- [x] Tlačítko pro otevření mapy zalícovat doprava (člověk extrémně často omylem klikne na něj místo potvrzení vyhledávání fulltextem).

**Comment by motyc** [comment]
Původní issue rozšířeno na celkovou korekturu drobností v CSS.

**Comment by pkudela** [comment]
"Čitelnosti titulků by i díky menšímu písmu asi pomohlo, pokud by byly bold:" - to uz bold je, toto formatovani je default materialu, dle meho to citelne je, to ze je mensi a jinou barvou je preci duvod, proc jsme to chteli oddelit od hodnoty, na to jsme se na zacatku shodli

**Comment by pkudela** [comment]
@albertoh prosim o nasazeni

**Comment by albertoh** [comment]
Nasazeno

**Comment by pkudela** [comment]
@albertoh prosim o nasazeni
