### ISSUE TITLE
OAI API  - oprava setu dokument

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#440]
V rámci https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commit/2503b2c0363ad7fc82ad19dc0375a55eb502e3f7 byl smazán set `knihovna_3d`, což ale takto snadno nejde. Nyní totiž set fungoval a zahrnuté záznamy se neobjevovaly v setu `dokument`.

Udělat tak, aby:
- [x] set `dokument` podával vše (tj. dokumenty + 3D)
- [x] set `dokument:3d` podával jen 3D

**Comment by albertoh** [comment]
@motyc  Je nutne zmenit popisny soubor setu, pridat dokument:3d
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/dev/web/src/main/resources/cz/inovatika/arup/digiarchiv/web/oai_ListSets.xml

**Comment by albertoh** [comment]
sety dokument a dokument:3d pripravene

**Comment by motyc** [comment]
> @motyc Je nutne zmenit popisny soubor setu, pridat dokument:3d https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/dev/web/src/main/resources/cz/inovatika/arup/digiarchiv/web/oai_ListSets.xml

Doplněno, finálně zavřu po nasazení. Jinak vše ok.

**Comment by albertoh** [comment]
Je to tam:
https://digiarchiv-test.aiscr.cz/api/oai?verb=ListSets

**Comment by motyc** [comment]
To byl fofr :)
