### ISSUE TITLE
Nejasný původ obsahu facety

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#45]
Dotaz: http://192.168.254.3:28080/amcr/results?q=%22C-9100277A%22&page=0&entity=akce

Ve facetě "Druh nálezu" je uveden zlomek keramiky - ten se ale v tom vyhledaném záznamu nikde neobjevuje a žádné související záznamy tento nemá. Asi to bude chyba.

**Comment by motyc** [comment]
Tak oprava - v datech ve skutečnosti keramika je, ale nálezy se z nějakého důvodu nevypisují: https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-9100277A-D01&metadataPrefix=oai_amcr

**Comment by albertoh** [comment]
Opraveno. Ted nalezy jsou videt
