### ISSUE TITLE
Doladění aplikovaných filtrů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#47]
- [x] Při filtraci z detailu záznamu (in-line filtry) použít místo stávajícího:
http://192.168.254.3:28080/amcr/results?page=0&entity=akce&f_pian_typ=bod
nově (tj. and místo or): http://192.168.254.3:28080/amcr/results?page=0&entity=akce&f_pian_typ=bod:and

- [x] Narážíme (opakovaně) na problém, že není uživatelům jasné, že mezi facetami je pevně nastaveno AND. Nešlo by to zvýraznit takto:
![image](https://user-images.githubusercontent.com/20186892/101555469-04f79700-39b9-11eb-9c38-aa70099264b0.png)

- [x]  Entita Akce, faceta Typ PIAN -> vyberu bod (or) a aplikuji -> vrátím se do facety -> změním na bor (and) a linie (and) -> promítne se jako bod (or) a linie (and) - CHYBA -> udělám totéž znovu -> promítne se jako oboje and - SPRÁVNĚ. Je divné, že se to podaří až napodruhé.

- [x] V aplikovaných filtrech skrýt ikonu "or"

- [x] když hledám fulltextem, nezařadí se query do aplikovaných filtrů (sice se aplikuje, ale není to vidět)

- [x] když použiju in-line filtr, aplikuje se jako AND, nicméně se všechna již aktivní AND/NOT změní na OR - např. posloupnost:
1 - vyberu "OR Hradčany" + "AND Staré Město": http://192.168.254.3:28080/amcr/results?entity=akce&f_katastr=HRAD%C4%8CANY:or&f_katastr=STAR%C3%89%20M%C4%9ASTO:and&page=7&rows=50
2 - Kliknu na Josefov a zmizí mi AND u Starého města (děje se i pro not): http://192.168.254.3:28080/amcr/results?entity=akce&f_katastr=HRAD%C4%8CANY&f_katastr=STAR%C3%89%20M%C4%9ASTO&f_katastr=JOSEFOV:and&page=7&rows=50

**Comment by motyc** [comment]
Upraveno podle Skype

**Comment by pkudela** [comment]
@albertoh prosim nasadit

**Comment by albertoh** [comment]
Velky vyber filtru:
http://192.168.254.3:28080/amcr/results?entity=dokument&f_obdobi=ri.ml:or&f_obdobi=ri.st:or&page=0&f_areal=hradi%C5%A1t%C4%9B:or&f_areal=neur%C4%8Den%C3%BD%20are%C3%A1l:or&f_kategorie=b%C4%9B%C5%BEn%C3%BD%20n%C3%A1lez:or&f_okres=CHOMUTOV:and

**Comment by motyc** [comment]
Do hlavního záznamu doplněny dva nové body (chyby vznikly nově).
