### ISSUE TITLE
Nezobrazuje se správně náhled u souvisejících záznamů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#48]
Stane se toto:

![image](https://user-images.githubusercontent.com/20186892/101557298-0460ff80-39bd-11eb-83fe-fd927e54f28a.png)

K tomu ještě dotaz - proč obecně náhledy jsou jen na středu obrazovky a v podstatě vždy se tak musí zobrazit vertikální posuvník? nešlo by využít víc prostoru výškově na stránce (relativně vůči velikosti okna např. 80-90 %).

**Comment by pkudela** [comment]
Ahoj, s timto jsme nepocitali, neni to uplne jednoduche, jsou 2 moznosti:
-----

- [ ] zakazat otevirani v souvisejicich otevirani do dialogu, zustane jen nahled

- [ ] jit tou slozitejsi a pracnejsi  cestou a nahled zobrazit
-----
Prosim, vyber jednu z variant.

**Comment by pkudela** [comment]
PO kliku na obrazek se otevre persistentni odkaz.

**Comment by pkudela** [comment]
Co se tyce vysky obrazku @albertoh prosim vytahnout do konfigurace, s Davidem jsme nastavil nakonec pevnou vysku dialogu, ktereou si pak jeste bude ladit az to bude v konfiguraci.

**Comment by albertoh** [comment]
Obrazek otevira persistetni link

**Comment by motyc** [comment]
Zobrazení ok, jen prosím posílat ten persistentní link do nového okna/tabu.
