### ISSUE TITLE
Výměna ikon operátorů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#53]
Viz dohoda po Skype, bude to něco jako "∨" (OR), "=" (AND), "≠" (NOT).

Důvodem je, že ikony ve stávající formě neodpovídají funkci, tj. jsou matoucí (jde o práci s množinami, nikoli logické operátory).

--AND-- jako oddělovač facet zůstává.

**Comment by pkudela** [comment]
Toto je textove, jeste udelam variantu s ikonama

![image](https://user-images.githubusercontent.com/16591052/101781622-56f30680-3af8-11eb-87a0-2fe71c0514e2.png)

**Comment by pkudela** [comment]
ikony
![image](https://user-images.githubusercontent.com/16591052/101784824-4e043400-3afc-11eb-8060-5d97e9d51842.png)

**Comment by pkudela** [comment]
Tak je to hotove, snad jsem na nic nezapomel, udelal jsem facety, facety-used, facety-dynamic. @albertoh  prosim o nasazeni.
