### ISSUE TITLE
Chyby lokalizace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#55]
- [x] - 1 - jak přeložit popisky řazení?
- [x] - 2 - u tlačítka pro volbu view se zobrazuje "default.Zobrazení výsledků" (překlad přitom existuje)
- [x] - 3 - Items per page - chybí klíč?
- [x] - 4 - chybí tooltip pro tlačítko persistentního linku
- [x] - 5 - patrně překlep v klíči u entity Lokalita: "Počet dokumentu:" -> "Počet dokumentů"
- [x] - 6 - entita Dokument - Let - všechny in-line filtry jsou špatně mapované (např. se pracuje s "let_pocasi" místo "f_let_pocasi" atd.).
- [x] - 7 - entita Dokument - při použití filtrace podle kategorie_dokument se v aplikovaných filtrech nepoužívají překlady
- [ ] - 8 - nastavení ikon operátorů je v lokalizacích, místo nastavení klienta
- [x] - 9 - "rada" (9a) a "f_aktivita" (9b) mají heslář - proč jsou definovány i v lokalizacích?
- [x] - 10 - nepřekládá se typ PIAN v detailu záznamu
- [x] - 11 - nepřekládá se vedlejší typ v detailu záznamu akce
- [x] - 12 - pro 3D se v záhlaví nepřekládají pole období a areál (zobrazují se klíče)
- [x] - 13 - potřebuji upravit hlášku "sessionTimeout" - funguje jako klíč?

**Comment by motyc** [comment]
Lze průběžně opravovat (budu asi doplňovat).

**Comment by albertoh** [comment]
Ad 2. Opraveno. Klice:
"itemView.row": "Řádkové zobrazení výsledků",
  "itemView.col": "Sloupcové zobrazení výsledků",
  "itemView.default": "Výchozí zobrazení výsledků",

Ad.3 : Pridal jsem tridu pro preklad strankovani. Standardni angular material komponenta to podporuje. V lokalizacnich souborech pribyly klice:
"itemsPerPageLabel" : "Počet záznamů na stránce",
  "nextPageLabel" : "Následující stránka",
  "previousPageLabel" : "Předchozí stránka",
  "firstPageLabel": "První stránka",
  "lastPageLabel": "Poslední stránka",
  "rangeLabel1": "0 z {{length}}",
  "rangeLabel2": "{{startIndex}} - {{endIndex}} z {{length}}"

Ad. 4: Opraveno

Ad. 5: Opraveno

Ad. 6: Opraveno

Ad. 7: Opraveno

Ad. 8: Ikonky jsou v css.

Ad. 9: rada odstranena. f_aktivita nelze. Heslar ma hodnoty (síd, poh, výr), kdyz v indexu mame nazev pole z API (sidlistni, pohrebni, vyrobni...)

**Comment by albertoh** [comment]
Ad. 1: Opraveno. Pridano:
"sortBy": {
    "ident_cely": "Dle idetifikátoru",
    "okres": "Dle okres + katastr",
    "autor": "Dle autora",
    "nalezce": "Dle nalezce",
    "datum_nalezu": "Dle datum nalezu",
    "vedouci_akce": "Dle vedouci akce",
    "vedouci_projektu": "Dle vedouci projektu",
    "rok_vzniku": "Dle data",
    "nazev": "Dle nazev",
    "organizace": "Dle organizace"
  },

**Comment by motyc** [comment]
@albertoh Není mi teď úplně jasné, jak dál správně postupovat. Existují teď mnou editované lokalizace zde:
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/configurations/web/src/main/ng/src/assets/i18n/cs.json
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/configurations/web/src/main/ng/src/assets/i18n/cs.json

Zároveň jsi ale asi dnes dělal commity do main branche. Mám to nějak sjednotit já nebo jak to provedeme? Stejný problém se týká i konfiguračních souborů... Nechci Ti nikde přidělat práci.

**Comment by albertoh** [comment]
Domluvime se.
Ted je vsechno rozbite. Dam to dohromady, a vymyslim nejaky zpusob

**Comment by albertoh** [comment]
V konfiguracnim souboru mas komentare:
   //indexovat překlad místo klíče

Cesky? Anglicky? Oboji? Puvodni klic taky?

**Comment by motyc** [comment]
Ad poslední koment - budeme řešit jako issue #60 jako budoucí rozvoj.

**Comment by motyc** [comment]
Ad 8 - jde o pasáž `"operator": {"or": "check", "and": "drag_handle", "not": "block" },`. Je fajn, že to jde nastavit, jen obdobnou věc už řešíme pro ikony dokumentů, což se ale nastavuje v  `"entityIcons": { ` v souboru https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/configurations/web/src/main/ng/src/assets/config.json. Přijde mi divné, když to je pokaždé jinde (v konfiguraci by to bylo logičtější.

Ad 9 - Rozumím, důvodu, ale nerozumím provedení. Nyní se obsah facety podle lokalizačních souborů nepřekládá (používá se klíč). Navíc je to definováno jak v lokalizačních souborech, tak v https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/configurations/web/src/main/ng/src/assets/config.json. I zde mi není jasné, proč je to na dvou místech (navíc nefunkční).

Přidán bod 10

**Comment by albertoh** [comment]
Aktivity opravene. Ale porad musi zustat v lokalizaci. Akorat, aby se chovaly standardne, tak:

		"f_aktivita_sidlistni": "sídlištní",
		"f_aktivita_pohrebni": "pohřební",
		"f_aktivita_vyrobni": "výrobní",
		"f_aktivita_tezebni": "těžební",
		"f_aktivita_kultovni": "kultovní",
		"f_aktivita_komunikace": "komunikační",
		"f_aktivita_deponovani": "deponování",
		"f_aktivita_boj": "boj",
		"f_aktivita_jina": "jiný druh aktivity",
		"f_aktivita_intruze": "intruze"

Rada je pryc

**Comment by albertoh** [comment]
Preklad PIAN opraveno

**Comment by motyc** [comment]
Potvrzuji opravy, přidán bod 11.

**Comment by albertoh** [comment]
Vedlejsi typ opraven

**Comment by motyc** [comment]
Doplněno 12 (období a areál ve 3D).

**Comment by motyc** [comment]
Doplněno 13 - sessionTimeout

**Comment by albertoh** [comment]
3D Opraveno
pridal jsem sessionTimeout do lokalizacnich souboru. Neni to hezky preklad :)
