### ISSUE TITLE
Typ a kategorie dokumentu jako běžné facety

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#56]
Stávající řešení je poděděné z předchozí verze a je v podstatě zbytečné. Stačí odstranit a mít dvě běžné facety: "kategorie_dokumentu" a "f_typ_dokumentu". O žádnou funkcionalitu tím nepřijdeme a bude to jednotné.

**Comment by motyc** [comment]
@albertoh Funkčně ok, jen se přestaly překládat klíče pro kategorie dokumentu, prosím o opravu.

**Comment by albertoh** [comment]
Pridal jsem do preklady cs.json a en.json odpovidajici klice. Format klicu se zmenil

**Comment by motyc** [comment]
V pořádku
