### ISSUE TITLE
Jaké jsou nastaveny wildcards pro fulltext?

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#57]
Potřeboval bych vědět, jak wildcards lze používat v dotazech. Vím o těchto:
- `*` - libovolný řetězec
- `""` - je přesně

Jsou definované nějaké další? Např. libovolný znak, libovolná číslice, začátek řetězce...?

**Comment by motyc** [comment]
@albertoh Zde prosím o odpověď - popis stávajícího stavu.

**Comment by motyc** [comment]
@albertoh Ještě zde podotknu, že chování v textových polích u "Filtrovat podle pole bez hesláře" je chování jiné (např. nejsou třeba uvozovky). Proč to tak je? Nemělo by to být jednotné?

**Comment by albertoh** [comment]
Pole pro fulltextove hledani je analyzovan. To znamena, ze pri indexaci SOLR analyzuje a tokenizuje hodnotu toho pole. Pri tom, pri hledani SOLR muze najit i casti, tj tokeny.
 Ostatni pole jsou indexovane jako string, tj, v plne delce. A to znamena, ze pri hledani musime najit cely retezec.
 Pro to, pri hledani bez heslare nejsou potreba uvozovky. A bez hvezdicky nenajde zaznam jen podle casti vyrazu. (to je pripad rodinnych)

 Asi by bylo dobre vsechny pole uvedene v "Filtrovat podle pole bez hesláře" konfigurovat v SOLRu tak, aby se tokenizovaly stejne jako fulltextove.

 Process tokenizace rozbije text na kusy, a potom hledani probiha v tech kusech. To znamena, ze wildcard se bere v ramci tokenu.
 
 Jeste mi napada, ze pri fulltextovem hledani, muzu detekovat vyraz bez mezer, a tehdy hledat s automaticky pridane uvozovky. To by vyresil problem hledani identifikatoru.

**Comment by albertoh** [comment]
Pro info, prikladam SOLR dokumentace:
https://solr.apache.org/guide/8_11/the-standard-query-parser.html#wildcard-searches
https://solr.apache.org/guide/8_11/the-standard-query-parser.html#escaping-special-characters

**Comment by motyc** [comment]
Souhlasím s navrženým, tj. že by bylo dobré tokenizovat vše. Pak budeme schopni do nápovědy dát jasné vysvětlení a pokyn, jak s tím pracovat.

S tou vychytávkou pro fulltext souhlasím, to mi přijde jako dobrá varianta. Jen mě napadá, co se pak stane, když použiju nějakou wildcard (třeba hvězdičku)? Muselo by to být dostatečně chytré, aby to v takovém případě uvozovky nepřidalo... Ještě to prosím promysli, abychom si tím nenadělali více zmatků, než by byla přidaná hodnota.

**Comment by albertoh** [comment]
Zmenil jsem solr config. Reindexuju...

**Comment by albertoh** [comment]
Otestuj, prosim, jestli ted to vyhovuje.
Pri zadavani vyraz bez mezer, * a ? hleda se s pridavnimi uvozovkami. Identifikatory se dobre hledaji ted, jak v full textu a i pres identifikator vlevo

**Comment by motyc** [comment]
Chování je myslím o dost lepší, ale mám dojem, že ta popsaná pravidla neplatí vždy. Zkusil jsem do fulltextu zadat:
- `C-200913524A-DT-01` - výsledek ok
- `C-200913524A-DT-0?` - nic nenašlo - proč?
- `C-200913524A-DT-0*` - nic nenašlo - proč?
- Zajímavé je, že když se je řetězec v obsažen v jiném poli než v ID, tak to funguje (testováno `korespondence`, `koresponden*`, `korespondenc?`

**Comment by albertoh** [comment]
Opraveno. Nakonec jsem zmenil konfigurace v SOLRu, tokenizer z StandardTokenizerFactory na WhitespaceTokenizerFactory

Prosim otestuj.

**Comment by motyc** [comment]
Otestováno. Chování mi nyní přijde poměrně logické a jasně popsatelné.

**Comment by motyc** [comment]
@albertoh K tomuto jsme narazili ještě na jednu nešikovnost a prosím o zamyšlení, zda to jde nějak snadno řešit - když zadám Borkovský (https://digiarchiv.aiscr.cz/results?q=Borkovsk%C3%BD&page=0), nalezne se jen minimální část reálných výskytů toho jména. Podobně je to s vyhledávání slova (https://digiarchiv.aiscr.cz/results?q=korespondence&page=0). V obou případech je problém v tom, že vyhledávání nedá výsledek ve chvíli, kdy hned za slovem (tokenem) následuje interpunkční znaménko. To je dost problém, protože nikoho podobné chování nenapadne a nedojde mu, že musí hledat takto: https://digiarchiv.aiscr.cz/results?q=Borkovsk%C3%BD*&page=0, resp. https://digiarchiv.aiscr.cz/results?q=korespondence*&page=0.

Nešlo by s tím něco udělat? Přijde mi to jako hodně problematická vlastnost. Podotýkám, že to tak bylo v původní verzi i v té nově nasazené...

**Comment by albertoh** [comment]
Zmenil jsem tokenizace solru. Nove po rozdeleni textu na tokeny podle mezer, odstranime Interpunkční znaménka z tokenu krome "-" a "_"
Reindexoval jsem na testu. Zkontroluj, jestli ted je to tak, jak si predstavujes

**Comment by motyc** [comment]
Potvrzuji, toto je přesně to, co jsme potřebovali. Moc děkuji.

**Comment by albertoh** [comment]
Nasadim na produkcni, a reindexuju tehdy

**Comment by motyc** [comment]
Funguje, zavírám.
