### ISSUE TITLE
Řádkové zobrazení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#58]
Funguje teď trošku nešikovně (část dat není vůbec vidět a zároveň to moc místa nešetří):
- [x] - zobrazit pouze ikonu, nadpis a ovládací tlačítka (tj. skrýt náhled a zbytek popisu v hlavičce). Např.:
![image](https://user-images.githubusercontent.com/20186892/101954373-42983200-3bfc-11eb-9227-1bf7f758fb8f.png)

- [x] - Po rozbalení detailu zobrazit celou hlavičku a zbytek detailu (tj. jako normálně). Např.:
![image](https://user-images.githubusercontent.com/20186892/101954584-a15dab80-3bfc-11eb-859f-9f266497d45a.png)

Pokud je to hodně práce, dáme jako enhancement.

**Comment by pkudela** [comment]
Hotovo
