### ISSUE TITLE
Krok zpět - mizející data

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#59]
Entita Dokumenty (patrně ale platí i pro ostatní) -> u libovolného dokumentu kliknout na tlačítko Zobrazit na mapě -> mapa se otevře (vše ok) -> krok zpět v prohlížeči -> záznamy se načtou jen částečně:

![image](https://user-images.githubusercontent.com/20186892/102086087-d09c3480-3e17-11eb-8407-28088cbfa0b6.png)

Kolega mi psal, že se mu to stalo i použitím tlačítka Zavřít mapu, to se mi ale nepodařilo reprodukovat.

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Zde se mi zdá, že nedošlo ke změně (testováno nyní, chová se to stejně).

**Comment by albertoh** [comment]
Mel jsi pravdu. Uz to je

**Comment by albertoh** [comment]
Jeste neni. Pokracuju
