### ISSUE TITLE
U volby zobrazení se popisky nevejdou do okna

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#61]
Nevím jak je to nastavené, ale je potřeba je zobrazit celé:
![image](https://user-images.githubusercontent.com/20186892/102411588-70adb580-3ff2-11eb-8773-768a44454201.png)

**Comment by pkudela** [comment]
hotovo, opraveno - @albertoh prosim o nasazeni

![image](https://user-images.githubusercontent.com/16591052/104046579-95a3db80-51e0-11eb-81b0-4aa18f01ca4d.png)
