### ISSUE TITLE
Let - pozorovatel a pilot - chybí in-line filtry v záznamu + špatný formát datumu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#62]
![image](https://user-images.githubusercontent.com/20186892/102414251-7a391c80-3ff6-11eb-84c3-64362d0458e9.png)

**Comment by albertoh** [comment]
Jaky mam pouzivat heslar pro pilot a pozorovatel?

**Comment by motyc** [comment]
Jména. Mělo by to korespondovat.

**Comment by motyc** [comment]
Ale ještě k tomu doplňuji - bral jsem to tak, že když k tomu jsou facety (ty už existují, proto mne to trklo), tak by to mělo jít filtrovat i ze záznamu. Nebo je v tom nějaký rozdíl?
