### ISSUE TITLE
Zmizela část facet

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#63]
Jmenovitě:
- [x] - f_okres
- [x] - f_adb_typ_sondy
- [x] - f_adb_podnet
- [x] - f_pian_typ
- [x] - f_pian_presnost
- [x] - f_pian_zm10

**Comment by motyc** [comment]
Stalo se znovu - asi bude třeba zjistit, proč se to děje

**Comment by albertoh** [comment]
To byla moje chyba pri oprave.
