### ISSUE TITLE
Chyba ve facetě druhu u samostatného nálezu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#64]
Nějak se plete s druhem lokality:

![image](https://user-images.githubusercontent.com/20186892/102424028-96df4f80-400a-11eb-9974-57d0d3881732.png)

**Comment by motyc** [comment]
Ta jedna faceta zmizela, nicméně divný je obsah té, co tam zbyla - nejsou tam všechna data, co jsou obsažená v záznamech... Ve skutečnosti obsahem byla správně ta faceta označovaná jako "Druh lokality"

**Comment by motyc** [comment]
A ještě jedna věc - oprava asi způsobila, že faceta "Lokalita - druh" úplně zmizela (není ani u lokalit).

**Comment by albertoh** [comment]
Opraveno

**Comment by albertoh** [comment]
Obsah facety je v poradku. Ten vetsi zaznam uvidis pokud se prihlasis. Ta faceta je v seznamu "secured".

**Comment by motyc** [comment]
Aha, už rozumím. Ono u samostatných nálezů, je nález součástí hlavičky, takže tam by to tak být nemuselo. Ale proto udělám samostatné issue na později.
