### ISSUE TITLE
Pole chybějící v indexu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#65]
- [x] adb_uzivatelske_oznaceni_sondy
- [ ] extra_data_meritko
- [ ] extra_data_pocet_variant_originalu
- [ ] extra_data_sirka
- [ ] extra_data_udalost
- [ ] extra_data_vyska
- [ ] jednotka_dokumentu_poznamka
- [ ] let_fotoaparat
- [ ] let_uzivatelske_oznaceni
- [x] nalez_pocet
- [x] nalez_poznamka
- [ ] neident_akce_pian
- [ ] neident_akce_popis
- [ ] neident_akce_poznamka
- [x] pian_ident_cely
- [x] tvar_poznamka
- [x] vazba_projekt_akce_id_projekt

**Comment by albertoh** [comment]
adb_uzivatelske_oznaceni_sondy: nevidim v API
ext_zdroj: existuje pole "ext_zdroj" jako JSON. Tam najdeme veskerou informaci. Pokud chceme primo hledat musime je primo pridat. Po tvych zmenach v server_config je to nutne. Zmenim indexer.
extra_data: chybejici pole nejsou v datech
jednotka_dokumentu_poznamka: neni v datech
let: chybejici pole nejsou v datech
pian_ident_cely -> pian_id
tvar_poznamka: nevidim v datech
