### ISSUE TITLE
Upraveno řazení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#68]
Do https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/main/web/src/main/ng/src/assets/config.json jsem přidal řazení podle "katastr" a podle "datum_ukonceni_v". Prosím o kontrolu a nasazení.

**Comment by motyc** [comment]
@albertoh včera jsme se bavili též o tom, jak nastavit defaultní řazení a říkal jsi mi, že se to dělá pořadím těch řazení. Nepřijde mi, že by to byla pravda - pokud by to platilo, tak by se nyní dokumenty měly defaultně řadit podle roku vzniku sestupně a akce podle katastru. To se ale neděje. Jak to tedy je?

**Comment by albertoh** [comment]
Byla chyba pri zmene entity bez zvoleneho typu razeni. Opraveno
