### ISSUE TITLE
Exporty - ladění

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#69]

**Comment by motyc** [comment]
Nastavení jsem doladil, při tom odhaleno několik chyb?
- [ ] - akce - katastr, okres a organizace se nezobrazují, přestože nastavení vypadá v pořádku
- [ ] - lokalita - nezobrazuje se katastr
- [ ] - projekt - datum zahájení a ukončení ve špatném formátu
- [ ] - projekt - nezobrazuje se katastr

Prosím o nasazení změn v konfiguraci.

**Comment by motyc** [comment]
- [ ] - akce, lokalita - katastry se zobrazují divně (je tam dvakrát hlavní katastr a poté všechny katastry z dalších katastrů; dobře je to u projektů, to lze brát jako vzor (možná je to jen věc nastavení, ale nevím, jak na to)
- [ ] - 3D - nezobrazuje se období a areál

**Comment by motyc** [comment]
Vše v pořádku s výjimkou katastru u dokumentu, kde je to správně tak na půl. Má dojem, že problém je v přístupnosti, kdy se pro zobrazení katastru bere v úvahu přístupnost dokumentu, nikoli přístupnost akce/lokality (podobné jako problém mapy řešený v #78.

**Comment by albertoh** [comment]
Tim padem mame chybu, katastr pro dokumenty neni chranen v seznamu vysledku.

**Comment by motyc** [comment]
@albertoh Katastry u dokumentů pochází ze třech zdrojů:
- neidentifikovaná akce - zde se přístupnost nijak nezohledňuje, tj. vše je "A" (jedná se o součást popisu dokumentu)
- akce - měla by se zohlednit přístupnost související entity akce
- lokalita - měla by se zohlednit přístupnost související entity lokality

Je to v podstatě totéž, jako chování pro PIAN.

**Comment by motyc** [comment]
V exportu se to již myslím chová dobře, ale je to chybně v hlavičce záznamu. Viz tento příklad: https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&jednotka_dokumentu_vazba_akce=M-202000541A:or (katastr by bez oprávnění neměl být vidět).

![image](https://user-images.githubusercontent.com/20186892/103660713-38a0ef00-4f6e-11eb-9b3e-febd74ac5c07.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Skrývání v pořádku, jen tam zůstává viset nikam nevedoucí filtrační ikona.

**Comment by albertoh** [comment]
Opraveno
