### ISSUE TITLE
Doladit konfigurace podle komentářů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#71]
Viz náš Skype a soubory:

https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/configurations/web/src/main/resources/cz/inovatika/arup/digiarchiv/web/server_config.json

https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/configurations/web/src/main/ng/src/assets/config.json

**Comment by albertoh** [comment]
Pro client config:

"dateFacets" odstranim

"objekt_kategorie": ["f_kategorie", "nalez_kategorie"], //DN: proč je tady mapováno také f_kategorie a u predmet_kategorie nikoli?  
predmet_kategorie  ma svuj heslar


"specifikace_objektu_druha": "nalez_kategorie", //DN: nemělo by být f_specifikace?
pro pole "nalez_kategorie" najde hesla v ruznych heslarich: "specifikace_objektu_druha", "predmet_kategorie" a "objekt_kategorie"

//DN: Co to je? In-line filtry?
  "urlFields" jsou jednoducha pole, ktere drzime v url a je potreba zpracovat

**Comment by albertoh** [comment]
"indexovat překlad místo klíče"
Asi staci hodnoty indexovat do fulltextoveho hledani, ne? Myslim, ze pro konkretni pole filtrujeme pomoci rozhrani, kde pouzivame presne heslo.
Jinak bych musel vytvaret pro kazde pole, pro ktere chceme indexovat preklad, 2 nova lokalizovana pole, cs a en

Souhlas?

**Comment by motyc** [comment]
> "indexovat překlad místo klíče" Asi staci hodnoty indexovat do fulltextoveho hledani, ne? Myslim, ze pro konkretni pole filtrujeme pomoci rozhrani, kde pouzivame presne heslo. Jinak bych musel vytvaret pro kazde pole, pro ktere chceme indexovat preklad, 2 nova lokalizovana pole, cs a en
> 
> Souhlas?

Na tohle máme samostatné issue, to můžeš ignorovat, viz: #60

**Comment by albertoh** [comment]
Mas pravdu. Udelam jsem zmeny podle komentaru.
Smysl te klice je, ze pri sestaveni json pro preklady z heslaru, vytvareji se klice z heslaru s prefixem pro dane pole, aby v rozhrani se nasli. Tj, klic 
"predmet_kategorie": ["f_kategorie", "nalez_kategorie"],

vyvari prokazde heslo z heslare predmet_kategorie klice:
  f_kategorie_heslo
  nalez_kategorie_heslo

**Comment by motyc** [comment]
@albertoh Jak jsme na tom s tímto issue? Koukám, že to má být done, ale nevidím k tomu žádný commit. Kam se můžu podívat na výsledek?

**Comment by albertoh** [comment]
To jsem asi komitnul spolu s jinou zmenou jineho issue, a tady neni odkaz. Ale konfigurace ted odpovida komentaru.

Pri otevreni config.json tady, muzes se divat na commity, ktere souvisi s dannim souborem.
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commits/dev_v.2.1.0/web/src/main/ng/src/assets/config.json

Tenhle commit ma ty zmeny:
https://github.com/ARUP-CAS/aiscr-digiarchiv-2/commit/8ec300d38c48562262c5ab1baca55e805cb4806a#diff-06cf266d3976333c0ba6b072a4e03604a284d0b869c5b7f1ac343c240b2db42d

Je napsan na issue #78 proto ze tam byly zmeny k nemu, a config jel tam s nimi dohromady.

**Comment by motyc** [comment]
Ok, zde tedy poslední ladění, protože tam něco ještě zbylo:

Ad https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/dev_v.2.1.0/web/src/main/ng/src/assets/config.json
- [ ] - opravdu ještě potřebujeme `"numberFacets": ["hloubka"]`, když to je zároveň definováno jako `"filterFields": [{"type": "number", "field": "hloubka"}]`?

Ad https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/dev_v.2.1.0/web/src/main/resources/cz/inovatika/arup/digiarchiv/web/server_config.json
- [ ] stále tam je myslím navíc položka `"heslare": ["povrch"]` - netuším, o jaký heslář by mělo jít; pokud se používá, prosím o informaci, o co jde
- [ ] nerozumím položce `"pasSecuredFields": ["lokalizace", "katastr"] ` - buď je neúplná (chráníme mnohem více polí), nebo se už nepoužívá

Nakonec pak dotaz - jak se liší položka `"maxDocsForCluster": 10000` v konfiguraci serveru a `"mapOptions": {"docsForCluster": 10000}` v konfiguraci klienta? Není jedno z toho nadbytečné?

**Comment by albertoh** [comment]
Mas pravdu ve vsem :)
 numberFacets odstraneno
 povrh: odstraneno
 pasSecuredFields je zastarale, v kodu bylo zakomentovano, odstraneno
 maxDocsForCluster ma byt jen v clientu, odstraneno ze serveru
