### ISSUE TITLE
Celkové zpomalení odezvy a záseky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#73]
Po nasazení na novou URL dochází opakovaně k zásekům - běží stále dokola načítání a stránka se načte až ve chvíli, kdy udělám refresh (F5).

**Comment by motyc** [comment]
Problém bude někde v tomto (výpis z konzole):
`main.4a1be49….js:1 ERROR 
n {headers: t, status: 403, statusText: "Forbidden", url: "https://digiarchiv-test.aiscr.cz/amcr/api/search/query?entity=dokument&page=0", ok: false, …}
error: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">↵<html><head>↵<title>403 Forbidden</title>↵</head><body>↵<h1>Forbidden</h1>↵<p>You don't have permission to access /amcr/api/search/query↵on this server.</p>↵</body></html>↵"
headers: t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure response for https://digiarchiv-test.aiscr.cz/amcr/api/search/query?entity=dokument&page=0: 403 Forbidden"
name: "HttpErrorResponse"
ok: false
status: 403
statusText: "Forbidden"
url: "https://digiarchiv-test.aiscr.cz/amcr/api/search/query?entity=dokument&page=0"
__proto__: t`

**Comment by motyc** [comment]
@MichalKminek nemůže to být nějaká chyba v nastavení na Tvé straně?

**Comment by MichalKminek** [comment]
Presun proxy na tyz stroj, kde je Tomcat vyresilo problem.
