### ISSUE TITLE
Důsledněji oddělit klíče

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#74]
- [x] popisky v detailu
- [x] názvy polí
- [x] popis ve facetách
- [x] názvy tlačítek
- [x] ostatní součásti interface

**Comment by pkudela** [comment]
Toto je zatim me posledni issue, az dodelam ty drobnosti ve #128. @motyc je nutne mit toto issue hotove do konce roku, nebo staci po novem roce? Dej prosim vedet.

**Comment by motyc** [comment]
@pkudela Stačí po novém roce. To bych dodělal poslední věci, vše otestoval a nasadili bychom to celé najednou. Do poloviny ledna bych to rád měl na produkci.

**Comment by pkudela** [comment]
@motyc strucny dotaz: "dusledneji oddelit klice" to znamena napr. u facetu staci aby bylo oddeleno v json napr. uzlem facets a v tom vse co se tyka facetu - titulky facetu, placeholders inputu, buttony, tooltpy atd. cili bude  jedna uroven, nebo chces aby pod uzlem facets byly jeste dalsi uzly, ktere jsem vyjmenoval vyse?
Je to osemetna otazka kam az sahnout s oddelenim klice, jestli jedna uroven napr. facets {}, card {}, navbar {}, nebo pak jeste podurovne. Asi bude dobre si kvuli tomu zavolat, nez se do toho pustim.

**Comment by pkudela** [comment]
Po telefonickem rozhovoru rozdeleno jinak:

- navbar
- searchbar
- facet
- sortbar
- card
- pagination
- footer
- a pripadne jine ....

**Comment by pkudela** [comment]
hotovo, prosim o otestovani

**Comment by pkudela** [comment]
@motyc akorat jedna polozka v sortovani neni prelozena, protoze ji nemam na lokale, Alberto rikal, ze sis ji pridal asi do konfigurace, takze si ji musis do prekladu pridat sam, az budes mit chvilku zavolej, vysvetlim preklady a celou novou strukturu - strucne

**Comment by motyc** [comment]
Prošel jsem to, doplnil některé chybějící položky a revidoval syntaxi (někde zůstaly špatně čárky). V dev branchi jsou commitnuté změny.

Zatím jsem odhalil jediný drobný problém s překladem:
- [ ] -  faceta Dokument - kategorie (v lokalizacích viz řádky 634-643)
![image](https://user-images.githubusercontent.com/20186892/150562138-5ee0780c-729d-417e-805b-dfd241f36342.png)

**Comment by motyc** [comment]
Další nalezené chyby (@pkudela):
- [ ] https://digiarchiv-test.aiscr.cz/results?entity=projekt&page=0&sort=datestamp%20desc: + https://digiarchiv-test.aiscr.cz/results?entity=samostatny_nalez&page=0&sort=datestamp%20desc
![image](https://user-images.githubusercontent.com/20186892/151174194-76f33a47-7073-4557-9f98-21ef0f80ab8f.png)

- [ ] https://digiarchiv-test.aiscr.cz/results?entity=projekt&page=0&sort=datestamp%20desc
![image](https://user-images.githubusercontent.com/20186892/151174351-238c4fb9-012d-49e1-83d8-c08abe9c04ff.png)

- [ ] https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0&sort=datestamp%20desc
![image](https://user-images.githubusercontent.com/20186892/151174538-339c584d-d677-4cdc-8317-0f78191cc881.png)

- [ ] https://digiarchiv-test.aiscr.cz/results?entity=lokalita&page=0&sort=datestamp%20desc
![image](https://user-images.githubusercontent.com/20186892/151174723-7526337d-941e-48dc-b263-ef963869d736.png)

- [ ] https://digiarchiv-test.aiscr.cz/results?entity=samostatny_nalez&page=0&sort=datestamp%20desc
![image](https://user-images.githubusercontent.com/20186892/151175128-db65dfd0-ff7a-4b2a-b211-0f4ae761cfac.png)

- [ ] problém se záhlavím sloupců mají všechny exporty (projekty, akce, lokality, sam. nálezy, knihovna 3D), kromě exportu dokumentů

- [ ] https://digiarchiv-test.aiscr.cz/results?entity=akce&page=0&sort=datestamp%20desc&mapa=true&loc_rpt=48.745202524947885,13.293953978407067,50.96869183044938,19.99475081857298
![image](https://user-images.githubusercontent.com/20186892/151176187-98b3e74c-48ba-4ce5-8825-9f0cda0254c5.png)

**Comment by motyc** [comment]
- [ ] Nepřekládají se do angličtiny hesla ve facetě fieldwork type

**Comment by pkudela** [comment]
@albertoh vse je opravene, podivej se prosim na ten posledni bod s neprekladanim hesel, dik

**Comment by albertoh** [comment]
Nepřekládají se do angličtiny hesla ve facetě Fieldwork - type (https://digiarchiv-test.aiscr.cz/results?entity=dokument&page=0&sort=datestamp%20desc)

@motyc  Bere se to z heslare typ_akce_druha?

**Comment by motyc** [comment]
@albertoh Ano, přesně tak

**Comment by pkudela** [comment]
@motyc export ok, ale ten preklad jsem opravil, na lokale to mam spravne a na testu jsem to pred tim videl take spravne, kdyz jsem tam dopoledne dal novou verzi, ale neco se muselo zmenit, protoze ted se mi na testu zobrazuje uplne neco jineho, jiny nazev pole viz. screenshot

![image](https://user-images.githubusercontent.com/16591052/151400400-d6e330fa-87ad-4d52-a004-a3300b766eff.png)

**Comment by motyc** [comment]
V tom bude mít prsty @albertoh v souvislosti s https://github.com/ARUP-CAS/aiscr-digiarchiv-2/issues/117#issuecomment-1022242706

**Comment by pkudela** [comment]
hotovo, nize dukaz z lokalu a uz at se to nemeni

![image](https://user-images.githubusercontent.com/16591052/151443967-5c11e483-6b14-481a-a040-23e62a659642.png)

**Comment by motyc** [comment]
Už ok, díky

**Comment by motyc** [comment]
- [ ] Nalezen jeden chybějící překlad (položku nelze definovat - jde o tu první část řetězce před pomlčkou, v kódu chybí translate, bude to u všech entit):
![image](https://user-images.githubusercontent.com/20186892/152514115-257b26af-0a38-4324-a6c8-5e3dce53a82a.png)
- [ ] Při této příležitost připomínám prosbu o zvětšení písma v tooltipu.

**Comment by pkudela** [comment]
hotovo, prosim o kontrolu, nasazeno na testu
