### ISSUE TITLE
Dokumenty nejsou v mapě - chybně interpretovaná přístupnost

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#78]
Něco se patrně rozbilo v propojení dokumentů s PIAN. V mapě jich je viditelných podezřele málo a při kliknutí na "Zobrazit na mapě" např. u C-TX-202000005 se nic nestane. Pokud ale tentýž otevřu přes persistentní link, mapové zobrazení funguje dobře.

**Comment by motyc** [comment]
Doplňuji, že se patrně někde špatně zohledňuje přístupnost a na PIAN se přenáší přístupnost dokumentu, nikoli akce/lokality. Po přihlášení se to totiž zobrazuje dobře.

**Comment by albertoh** [comment]
Opraveno
