### ISSUE TITLE
Filtruj podle - doladění

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#79]
Některé filtrace se zaseknou nebo nevrací výsledky:
- [x] - Dokument - rok události od (zasekne se)
- [x] - Dokument - rok události do (zasekne se)
- [x] - Dokument - důvěryhodnost (nevrací správné výsledky)
- [x] - Komponenta dok. - nejistá datace (nevrací správné výsledky)
- [x] - Neident. akce - rok zahájení (nevrací správné výsledky)
- [x] - Neident. akce - rok ukončení (nevrací správné výsledky)
- [x] - Soubor - počet stran (zasekne se)
- [x] - Soubor - velikost (B) (nevrací správné výsledky)
- [x] - Projekt - datum zahájeni (nevrací správné výsledky)
- [x] - Projekt - datum ukončení (nevrací správné výsledky)
- [x] - Akce - datum zahájení (nevrací správné výsledky)
- [x] - Akce - datum ukončení (nevrací správné výsledky)
- [x] - Akce - související projekt (nevrací správné výsledky)
- [x] - Dok. jednotka - související PIAN (nepřidá se do aplikovaných filtrů, přestože filtrace proběhne dobře)
- [x] - Komponenta - jistota (nevrací správné výsledky)
- [x] - ADB - rok popisu (nevrací správné výsledky)
- [x] - ADB - rok revize (nevrací správné výsledky)
- [x] - Výškový bod - niveleta (nevrací správné výsledky)
- [x] - Nález - počet (nevrací správné výsledky)
- [x] - Nález - poznámka (nevrací správné výsledky)

**Comment by albertoh** [comment]
Komponenta dok. - nejistá datace (nevrací správné výsledky) -> v datech vidim akorat 54 zaznamu s hodnotou "?" Co to znamena? Ano? Ne? A kdyz nemaji nic?

**Comment by albertoh** [comment]
Neident. akce - popis (nevrací správné výsledky) 
Nevidim zadne zaznamy v indexu. Mas nejaky priklad?

**Comment by motyc** [comment]
Komponenta dok. - nejistá datace - v databázi jde o boolean a zde jsem si neuvědomil, že se již vypisuje přímo "?". Pokud to není komplikace, tak "?" lze považovat za "ano". Pokud je to zbytečně složité, tak podle pole filtrovat nutně nemusíme (nebo z něj udělám text).
Neident. akce - * - máš pravdu, data opravdu nikde nejsou. Mažu ze seznamu.

**Comment by albertoh** [comment]
Niveleta je definovan jako string xsd. Pokud jsme si jisti, ze API vraci cislo, muzu menit typ v SOLRu

**Comment by motyc** [comment]
Je to vždy číslo. V XSD to opravíme.
