### ISSUE TITLE
Zohlednění příslušnosti k organizaci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#8]

**Comment by motyc** [comment]
@albertoh Našel jsem cestu, jak to otestovat a podle mne to nefunguje.
- Jak by se to mělo chovat: pokud jsem přihlášený jako archeolog a zároveň platí, že entita Dokument má v pole organizace totéž tutéž organizaci, za kterou jsem přihlášen, pak by mělo být možné otevřít soubor daného dokumentu.
- Test: zkoušel jsem jako archeolog z organizace "ZČU Plzeň - Filozofická fakulta" otevřít soubor dokumentu "C-TX-201701399" a nepodařilo se mi to.
- Jaké je stávající nastavení této funkce a jak se liší od popsaného?

**Comment by albertoh** [comment]
Nasel jsem problem, ale budu potrebovat upresneni.
Pri prihlaseni uzivatel ziska id organizace (v danem pripade 315768). Podle id hledam v heslare nazev organizace ( v dannem pripade "Západočeská univerzita v Plzni - Filozofická fakulta"), ktery musi souhlasit s hodnotou organizace u dokumentu (pro danni dokument "ZČU Plzeň - Filozofická fakulta").

Ale jak je videt, nazvy jsou jine. 
Nasel jsem v heslari jeste hodnotu pole  "nazev_zkraceny":"ZČU Plzeň - Filozofická fakulta". Ten by tady odpovidal.

Otazka zni: bude to vzdy tak? musim hledat "nazev_zkraceny"?

**Comment by motyc** [comment]
Ano, to bude ono. V API se používá "nazev_zkraceny".

A ty v tomto případě saháš přímo do databáze? Neměli bychom to spíš nějak zohlednit v CSV hesláři organizací, co indexujeme z FTP, aby to bylo nějak jednotné?

**Comment by albertoh** [comment]
CSV soubory pouzivam pro preklady, maji jednotnou strukturu)
Pouzivam heslare z API AMCR pro organizaci a obdobi. Tady kazdy heslar ma jinou strukturu.
V indexu jsou oba, jak z CSV (core "translations), jak z API (core "heslar").

**Comment by motyc** [comment]
V pořádku, rozumím.
