### ISSUE TITLE
Nedořešená grafika při více souborech v prohlížečce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#82]
Původní řešení:
![image](https://user-images.githubusercontent.com/20186892/103897664-2ea8f880-50f4-11eb-843f-150f2be8e830.png)

Nové rozbité řešení:
![image](https://user-images.githubusercontent.com/20186892/103897595-19cc6500-50f4-11eb-9181-b25f4f8615ec.png)

**Comment by pkudela** [comment]
Hotovo, @albertoh prosim o nasazeni. Screenshot s extremnim poctem posilam nize.

![image](https://user-images.githubusercontent.com/16591052/104049344-1e247b00-51e5-11eb-8e9b-b9ade1a3af21.png)
