### ISSUE TITLE
U samostatných nálezů se nenačítají náhledy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#83]
Může jít pouze o rozpracovaný stav implementace produkčního serveru, ale raději na to upozorňuji.

**Comment by albertoh** [comment]
Ted jsem reindexoval soubory. Zadne z nich nema vyplnen pole samostatny_nalez, pres ktery se referencuje.

**Comment by motyc** [comment]
Musí být chyba v indexaci, protože takové soubory existují a v API jsou dobře - např. tento pár nález a soubor (oběma směry je reference validní):
https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-202009779-N00001&metadataPrefix=oai_amcr
https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/1600211909373_C-202009779-N00001F1.jpg&metadataPrefix=oai_amcr

**Comment by albertoh** [comment]
Je to tak. Opraveno.

**Comment by albertoh** [comment]
Ted ale vidim problemy pri zobrazeni.

**Comment by albertoh** [comment]
Uz je to
