### ISSUE TITLE
Soubory nejde stahovat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#84]
I zde může jít jen o problém rozpracované produkce. Nyní se však jen otevře prázdná stránka a nic se nestáhne.

**Comment by albertoh** [comment]
Cesta k souborum je nastavena na /var/lib/amcr/data, stejne jako byla na testovacim.
Ta cesta ale neni na serveru. Predavam Michalovi

**Comment by motyc** [comment]
Máš pravdu, složka va/lib/amcr se tváří být zcela prázdná, jak kdyby to bylo špatně připojené na megalitdr

**Comment by MichalKminek** [comment]
Byl problem s casovanim sluzby. Opraveno.
