### ISSUE TITLE
Nefunkční přihlašování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#95]
Pravděpodobně v souvislosti se včerejším přechodem na zabezpečenou verzi backendu (https://backend.aiscr.cz/) se rozbilo přihlašování (nejde se přihlásit). Prosím o vyřešení - asi bude třeba upravit volání XML-RPC.

**Comment by albertoh** [comment]
Opraveno.
Stacilo menit v konfiguracnim soubor url klice "amcrapi"

**Comment by motyc** [comment]
Rozumím a děkuji za rychlé vyřešení.
