### ISSUE TITLE
Oprava BibTeX

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#96]
Definice (naše zadání) je třeba syntakticky opravit, aby bylo validní.

**Comment by motyc** [comment]
Viz https://github.com/ARUP-CAS/aiscr-digiarchiv-2/pulls

**Comment by motyc** [comment]
Potvrzuji, prosím nasadit na produkci release v2.0.1 (@albertoh prosím, obecně už upravuj verze release i na testu tak, aby se shodovaly s milestone, který k issue vždy dám; jde o to, abychom snadno poznali, co je zrovna nasazené)

**Comment by albertoh** [comment]
Verze opravena.
Je to na produkci
