### ISSUE TITLE
V side menu (responsivní verze) chybí položka registrovat uživatele

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#98]
![image](https://user-images.githubusercontent.com/20186892/108043565-89156d00-7041-11eb-9fc6-584473f41362.png)

**Comment by pkudela** [comment]
doplneno
----
![image](https://user-images.githubusercontent.com/16591052/114134246-b1b23880-9907-11eb-848d-c0082fda56ef.png)
----
