### ISSUE TITLE
Nastavení reindexu?

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv-2#99]
Zdá se mi, že reindexace pouze přidává nová data, ale nemaže ta, která již v systému nejsou. Měl jsem za to, že index se před novou indexací vždy vymaže, ale zjevně to tak není.

Příkladem je lokalita: https://digiarchiv.aiscr.cz/id/C-L9000008

V AMČR ji už nemám, v API také ne, přesto však zůstala v Digitálním archivu. Je třeba to doladit.

**Comment by albertoh** [comment]
Prosim, @MichalKminek, pridat parametr clean do nastaveni sluzby:

curl http(...)/api/index/full?clean=true

**Comment by MichalKminek** [comment]
Aktualizoval jsem na prod a test serverech, zitra by se to melo projevit.

**Comment by motyc** [comment]
Díky, zítra potvrdím.
